// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ShopeeApi.Datas;

#nullable disable

namespace ShopeeApi.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20221011080054_AddSeedFood12")]
    partial class AddSeedFood12
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("ShopeeApi.Models.Category", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CategoryId"), 1L, 1);

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("CategoryTag")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("RestaurantId")
                        .HasColumnType("int");

                    b.HasKey("CategoryId");

                    b.HasIndex("RestaurantId");

                    b.HasIndex("CategoryTag", "RestaurantId")
                        .IsUnique();

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            CategoryId = 1,
                            CategoryName = "MENU",
                            CategoryTag = "menu",
                            RestaurantId = 1
                        },
                        new
                        {
                            CategoryId = 2,
                            CategoryName = "FREESHIP XTRA SIÊU ƯU ĐÃI - GIẢM 50%",
                            CategoryTag = "freeship50%",
                            RestaurantId = 2
                        },
                        new
                        {
                            CategoryId = 3,
                            CategoryName = "NOWFOOD DAY",
                            CategoryTag = "nowfoodday",
                            RestaurantId = 2
                        },
                        new
                        {
                            CategoryId = 4,
                            CategoryName = "NEW",
                            CategoryTag = "new",
                            RestaurantId = 2
                        },
                        new
                        {
                            CategoryId = 5,
                            CategoryName = "ROYAL BLACK TIGER",
                            CategoryTag = "royalblacktiger",
                            RestaurantId = 2
                        },
                        new
                        {
                            CategoryId = 6,
                            CategoryName = "ROYAL CHEESE TEA",
                            CategoryTag = "royalcheesetea",
                            RestaurantId = 2
                        },
                        new
                        {
                            CategoryId = 7,
                            CategoryName = "MILK TEA",
                            CategoryTag = "milktea",
                            RestaurantId = 2
                        },
                        new
                        {
                            CategoryId = 8,
                            CategoryName = "FRESH FRUIT TEA",
                            CategoryTag = "freshfruittea",
                            RestaurantId = 2
                        },
                        new
                        {
                            CategoryId = 9,
                            CategoryName = "MATCHA & CHOCOLATE",
                            CategoryTag = "matchachocolate",
                            RestaurantId = 2
                        },
                        new
                        {
                            CategoryId = 10,
                            CategoryName = "SMOOTHIE CHEESE",
                            CategoryTag = "smoothiecheese",
                            RestaurantId = 2
                        },
                        new
                        {
                            CategoryId = 11,
                            CategoryName = "BÁNH MÌ",
                            CategoryTag = "banhmi",
                            RestaurantId = 3
                        },
                        new
                        {
                            CategoryId = 12,
                            CategoryName = "BÚN",
                            CategoryTag = "bun",
                            RestaurantId = 3
                        },
                        new
                        {
                            CategoryId = 13,
                            CategoryName = "MÓN THÊM",
                            CategoryTag = "monthem",
                            RestaurantId = 3
                        },
                        new
                        {
                            CategoryId = 14,
                            CategoryName = "THỨC UỐNG",
                            CategoryTag = "thucuong",
                            RestaurantId = 3
                        },
                        new
                        {
                            CategoryId = 15,
                            CategoryName = "KHUYẾN MÃI HOT",
                            CategoryTag = "khuyenmaihot",
                            RestaurantId = 4
                        },
                        new
                        {
                            CategoryId = 16,
                            CategoryName = "COMBO HOT NƯỚC NGỌT",
                            CategoryTag = "combohotnuocngot",
                            RestaurantId = 4
                        },
                        new
                        {
                            CategoryId = 17,
                            CategoryName = "MÌ QUẢNG",
                            CategoryTag = "miquang",
                            RestaurantId = 4
                        },
                        new
                        {
                            CategoryId = 18,
                            CategoryName = "COMBO SIÊU TIẾT KIỆM 1 NGƯỜI",
                            CategoryTag = "combosieutietkiem1nguoi",
                            RestaurantId = 4
                        },
                        new
                        {
                            CategoryId = 19,
                            CategoryName = "COMBO 3 TÔ",
                            CategoryTag = "combo3to",
                            RestaurantId = 4
                        },
                        new
                        {
                            CategoryId = 20,
                            CategoryName = "MÓN THÊM",
                            CategoryTag = "monthem",
                            RestaurantId = 4
                        },
                        new
                        {
                            CategoryId = 21,
                            CategoryName = "NƯỚC UỐNG",
                            CategoryTag = "nuocuong",
                            RestaurantId = 4
                        },
                        new
                        {
                            CategoryId = 22,
                            CategoryName = "ĐẶC SẢN MIỀN TRUNG",
                            CategoryTag = "dacsanmientrung",
                            RestaurantId = 4
                        },
                        new
                        {
                            CategoryId = 23,
                            CategoryName = "NOWFOOD DAY",
                            CategoryTag = "nowfoodday",
                            RestaurantId = 5
                        },
                        new
                        {
                            CategoryId = 24,
                            CategoryName = "COMBO TRÀ SỮA",
                            CategoryTag = "combotrasua",
                            RestaurantId = 5
                        },
                        new
                        {
                            CategoryId = 25,
                            CategoryName = "TRÀ TRÁI CÂY NHIỆT ĐỚI",
                            CategoryTag = "tratraicaynhietdoi",
                            RestaurantId = 5
                        },
                        new
                        {
                            CategoryId = 26,
                            CategoryName = "SỮA TƯƠI ĐƯỜNG ĐEN",
                            CategoryTag = "suatuoiduongden",
                            RestaurantId = 5
                        },
                        new
                        {
                            CategoryId = 27,
                            CategoryName = "TRÀ SỮA",
                            CategoryTag = "trasua",
                            RestaurantId = 5
                        },
                        new
                        {
                            CategoryId = 28,
                            CategoryName = "LỤC TRÀ",
                            CategoryTag = "luctra",
                            RestaurantId = 5
                        },
                        new
                        {
                            CategoryId = 29,
                            CategoryName = "NƯỚC ÉP TRÁI CÂY TƯƠI",
                            CategoryTag = "nuoceptraicaytuoi",
                            RestaurantId = 5
                        },
                        new
                        {
                            CategoryId = 30,
                            CategoryName = "COMBO COUPLE",
                            CategoryTag = "combocouple",
                            RestaurantId = 5
                        },
                        new
                        {
                            CategoryId = 31,
                            CategoryName = "MÌ CỰC PHẨM",
                            CategoryTag = "micucpham",
                            RestaurantId = 6
                        },
                        new
                        {
                            CategoryId = 32,
                            CategoryName = "SỦI CẢO / HOÀNH THÁNH",
                            CategoryTag = "suicaohoanhthanh",
                            RestaurantId = 6
                        },
                        new
                        {
                            CategoryId = 33,
                            CategoryName = "MÌ KHÔ",
                            CategoryTag = "mikho",
                            RestaurantId = 6
                        },
                        new
                        {
                            CategoryId = 34,
                            CategoryName = "MÌ NƯỚC",
                            CategoryTag = "minuoc",
                            RestaurantId = 6
                        },
                        new
                        {
                            CategoryId = 35,
                            CategoryName = "HỦ TIẾU KHÔ",
                            CategoryTag = "hutieukho",
                            RestaurantId = 6
                        },
                        new
                        {
                            CategoryId = 36,
                            CategoryName = "MÓN ĂN THÊM",
                            CategoryTag = "monanthem",
                            RestaurantId = 6
                        },
                        new
                        {
                            CategoryId = 37,
                            CategoryName = "TRÀ THANH NHIỆT",
                            CategoryTag = "trathanhnhiet",
                            RestaurantId = 6
                        },
                        new
                        {
                            CategoryId = 38,
                            CategoryName = "SIÊU SALE MÙA LỄ HỘI",
                            CategoryTag = "sieusalemualehoi",
                            RestaurantId = 7
                        },
                        new
                        {
                            CategoryId = 39,
                            CategoryName = "BÁNH BÒ",
                            CategoryTag = "banhbo",
                            RestaurantId = 7
                        },
                        new
                        {
                            CategoryId = 40,
                            CategoryName = "BÁNH DA LỢN",
                            CategoryTag = "banhdalon",
                            RestaurantId = 7
                        },
                        new
                        {
                            CategoryId = 41,
                            CategoryName = "RAU CÂU FLAN CHEESE",
                            CategoryTag = "raucauflancheese",
                            RestaurantId = 7
                        },
                        new
                        {
                            CategoryId = 42,
                            CategoryName = "RAU CÂU SƠN THỦY",
                            CategoryTag = "raucausonthuy",
                            RestaurantId = 7
                        },
                        new
                        {
                            CategoryId = 43,
                            CategoryName = "RAU CÂU DỪA",
                            CategoryTag = "raucaudua",
                            RestaurantId = 7
                        },
                        new
                        {
                            CategoryId = 44,
                            CategoryName = "KEM",
                            CategoryTag = "kem",
                            RestaurantId = 7
                        },
                        new
                        {
                            CategoryId = 45,
                            CategoryName = "COMBO",
                            CategoryTag = "combo",
                            RestaurantId = 7
                        },
                        new
                        {
                            CategoryId = 46,
                            CategoryName = "YOGHURT",
                            CategoryTag = "yoghurt",
                            RestaurantId = 7
                        },
                        new
                        {
                            CategoryId = 47,
                            CategoryName = "BÁNH FLAN",
                            CategoryTag = "banhflan",
                            RestaurantId = 7
                        },
                        new
                        {
                            CategoryId = 48,
                            CategoryName = "CHÈ",
                            CategoryTag = "che",
                            RestaurantId = 7
                        },
                        new
                        {
                            CategoryId = 49,
                            CategoryName = "CỐT DỪA",
                            CategoryTag = "cotdua",
                            RestaurantId = 7
                        },
                        new
                        {
                            CategoryId = 50,
                            CategoryName = "COMBO",
                            CategoryTag = "combo",
                            RestaurantId = 8
                        },
                        new
                        {
                            CategoryId = 51,
                            CategoryName = "MÓN CƠM",
                            CategoryTag = "moncom",
                            RestaurantId = 8
                        },
                        new
                        {
                            CategoryId = 52,
                            CategoryName = "MÓN SỢI",
                            CategoryTag = "monsoi",
                            RestaurantId = 8
                        },
                        new
                        {
                            CategoryId = 53,
                            CategoryName = "MÓN LẨU",
                            CategoryTag = "monlau",
                            RestaurantId = 8
                        },
                        new
                        {
                            CategoryId = 54,
                            CategoryName = "BANH1 BISCOTTI",
                            CategoryTag = "banhbiscotti",
                            RestaurantId = 9
                        });
                });

            modelBuilder.Entity("ShopeeApi.Models.Food", b =>
                {
                    b.Property<int>("FoodId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FoodId"), 1L, 1);

                    b.Property<string>("FoodDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FoodImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("FoodPrice")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<float>("FoodPriceLess")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("real")
                        .HasDefaultValue(0f);

                    b.Property<string>("FoodTitle")
                        .IsRequired()
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("RestaurantId")
                        .HasColumnType("int");

                    b.HasKey("FoodId");

                    b.HasIndex("RestaurantId");

                    b.HasIndex("FoodTitle", "RestaurantId")
                        .IsUnique();

                    b.ToTable("Foods");

                    b.HasData(
                        new
                        {
                            FoodId = 1,
                            FoodDescription = "Hộp đã được nâng cấp lên từ 300->400 gram vẫn nguyên giá cux",
                            FoodImageUrl = "./ImageForSeedData/Food/Restaurant1/food1.jpeg",
                            FoodPrice = 85000,
                            FoodPriceLess = 0f,
                            FoodTitle = "Pate bơ béo (400gram)",
                            RestaurantId = 1
                        },
                        new
                        {
                            FoodId = 2,
                            FoodDescription = "Hộp đã được nâng cấp từ 300->400 gram với giá giữ nguyên",
                            FoodImageUrl = "./ImageForSeedData/Food/Restaurant1/food2.jpeg",
                            FoodPrice = 85000,
                            FoodPriceLess = 0f,
                            FoodTitle = "Pate sate (400gram)",
                            RestaurantId = 1
                        },
                        new
                        {
                            FoodId = 3,
                            FoodDescription = "1 hủ/ 150gr",
                            FoodImageUrl = "./ImageForSeedData/Food/Restaurant1/food3.jpeg",
                            FoodPrice = 44000,
                            FoodPriceLess = 0f,
                            FoodTitle = "Muối nguyễn thần thánh",
                            RestaurantId = 1
                        },
                        new
                        {
                            FoodId = 4,
                            FoodDescription = "",
                            FoodImageUrl = "./ImageForSeedData/Food/Restaurant2/food4.jpeg",
                            FoodPrice = 50000,
                            FoodPriceLess = 30000f,
                            FoodTitle = "Trà sữa trân châu hoàng kim",
                            RestaurantId = 2
                        },
                        new
                        {
                            FoodId = 5,
                            FoodDescription = "",
                            FoodImageUrl = "./ImageForSeedData/Food/Restaurant2/food5.jpeg",
                            FoodPrice = 45000,
                            FoodPriceLess = 27000f,
                            FoodTitle = "Trà sữa Hongkong Royal",
                            RestaurantId = 2
                        },
                        new
                        {
                            FoodId = 6,
                            FoodDescription = "",
                            FoodImageUrl = "./ImageForSeedData/Food/Restaurant2/food6.jpeg",
                            FoodPrice = 45000,
                            FoodPriceLess = 27000f,
                            FoodTitle = "Trà sữa lúa mạch",
                            RestaurantId = 2
                        },
                        new
                        {
                            FoodId = 7,
                            FoodDescription = "",
                            FoodImageUrl = "./ImageForSeedData/Food/Restaurant2/food7.jpeg",
                            FoodPrice = 45000,
                            FoodPriceLess = 27000f,
                            FoodTitle = "Hồng trà sữa",
                            RestaurantId = 2
                        },
                        new
                        {
                            FoodId = 8,
                            FoodDescription = "",
                            FoodImageUrl = "./ImageForSeedData/Food/Restaurant2/food7.jpeg",
                            FoodPrice = 45000,
                            FoodPriceLess = 27000f,
                            FoodTitle = "Trà sữa hoa nhài",
                            RestaurantId = 2
                        },
                        new
                        {
                            FoodId = 9,
                            FoodDescription = "",
                            FoodImageUrl = "./ImageForSeedData/Food/Restaurant2/food7.jpeg",
                            FoodPrice = 45000,
                            FoodPriceLess = 27000f,
                            FoodTitle = "Trà sữa olong kim phượng",
                            RestaurantId = 2
                        },
                        new
                        {
                            FoodId = 10,
                            FoodDescription = "",
                            FoodImageUrl = "./ImageForSeedData/Food/Restaurant2/food7.jpeg",
                            FoodPrice = 45000,
                            FoodPriceLess = 27000f,
                            FoodTitle = "Trà sữa olong bạch đào",
                            RestaurantId = 2
                        },
                        new
                        {
                            FoodId = 11,
                            FoodDescription = "không chọn được mức đá",
                            FoodImageUrl = "./ImageForSeedData/Food/Restaurant2/food11.png",
                            FoodPrice = 50000,
                            FoodPriceLess = 30000f,
                            FoodTitle = "Sữa tươi trân châu hoàng kim",
                            RestaurantId = 2
                        },
                        new
                        {
                            FoodId = 12,
                            FoodDescription = "",
                            FoodImageUrl = "./ImageForSeedData/Food/Restaurant2/food11.png",
                            FoodPrice = 50000,
                            FoodPriceLess = 30000f,
                            FoodTitle = "Đường Đen Sầu Riêng",
                            RestaurantId = 2
                        },
                        new
                        {
                            FoodId = 13,
                            FoodDescription = "không thể để đá riêng",
                            FoodImageUrl = "./ImageForSeedData/Food/Restaurant2/food13.jpeg",
                            FoodPrice = 50000,
                            FoodPriceLess = 30000f,
                            FoodTitle = "Sữa tươi trân châu đường đen",
                            RestaurantId = 2
                        },
                        new
                        {
                            FoodId = 14,
                            FoodDescription = "",
                            FoodImageUrl = "./ImageForSeedData/Food/Restaurant2/food14.jpeg",
                            FoodPrice = 50000,
                            FoodPriceLess = 30000f,
                            FoodTitle = "Trà sữa trân châu đường đen",
                            RestaurantId = 2
                        },
                        new
                        {
                            FoodId = 15,
                            FoodDescription = "Size M",
                            FoodImageUrl = "./ImageForSeedData/Food/Restaurant2/food15.jpeg",
                            FoodPrice = 57000,
                            FoodPriceLess = 34200f,
                            FoodTitle = "Matcha đường đen",
                            RestaurantId = 2
                        },
                        new
                        {
                            FoodId = 16,
                            FoodDescription = "Thơm ngon",
                            FoodImageUrl = "./ImageForSeedData/Food/Restaurant2/food16.jpeg",
                            FoodPrice = 65000,
                            FoodPriceLess = 39000f,
                            FoodTitle = "Trà táo xanh kiwi",
                            RestaurantId = 2
                        },
                        new
                        {
                            FoodId = 17,
                            FoodDescription = "SizeM",
                            FoodImageUrl = "./ImageForSeedData/Food/Restaurant2/food17.jpeg",
                            FoodPrice = 69000,
                            FoodPriceLess = 41400f,
                            FoodTitle = "Matcha đường đen kem cheese",
                            RestaurantId = 2
                        },
                        new
                        {
                            FoodId = 18,
                            FoodDescription = "",
                            FoodImageUrl = "./ImageForSeedData/Food/Restaurant2/food11.png",
                            FoodPrice = 55000,
                            FoodPriceLess = 33000f,
                            FoodTitle = "Trà sữa khoai môn đường đen",
                            RestaurantId = 2
                        },
                        new
                        {
                            FoodId = 19,
                            FoodDescription = "",
                            FoodImageUrl = "./ImageForSeedData/Food/Restaurant2/food19.jpeg",
                            FoodPrice = 54000,
                            FoodPriceLess = 32400f,
                            FoodTitle = "Trà lúa mạch kem cheese",
                            RestaurantId = 2
                        },
                        new
                        {
                            FoodId = 20,
                            FoodDescription = "",
                            FoodImageUrl = "./ImageForSeedData/Food/Restaurant2/food20.jpeg",
                            FoodPrice = 54000,
                            FoodPriceLess = 32400f,
                            FoodTitle = "Hồng trà Royal kem cheese",
                            RestaurantId = 2
                        },
                        new
                        {
                            FoodId = 21,
                            FoodDescription = "",
                            FoodImageUrl = "./ImageForSeedData/Food/Restaurant2/food21.jpeg",
                            FoodPrice = 57000,
                            FoodPriceLess = 34200f,
                            FoodTitle = "Trà sương mù London kem cheese",
                            RestaurantId = 2
                        },
                        new
                        {
                            FoodId = 22,
                            FoodDescription = "",
                            FoodImageUrl = "./ImageForSeedData/Food/Restaurant2/food22.jpeg",
                            FoodPrice = 54000,
                            FoodPriceLess = 34200f,
                            FoodTitle = "Trà xanh Golden kem cheese",
                            RestaurantId = 2
                        },
                        new
                        {
                            FoodId = 23,
                            FoodDescription = "",
                            FoodImageUrl = "./ImageForSeedData/Food/Restaurant2/food23.jpeg",
                            FoodPrice = 54000,
                            FoodPriceLess = 32400f,
                            FoodTitle = "Trà ô long bạch đào kem cheese",
                            RestaurantId = 2
                        },
                        new
                        {
                            FoodId = 24,
                            FoodDescription = "",
                            FoodImageUrl = "./ImageForSeedData/Food/Restaurant2/food24.jpeg",
                            FoodPrice = 54000,
                            FoodPriceLess = 32400f,
                            FoodTitle = "Trà bách hoa kem cheese",
                            RestaurantId = 2
                        },
                        new
                        {
                            FoodId = 25,
                            FoodDescription = "",
                            FoodImageUrl = "./ImageForSeedData/Food/Restaurant2/food25.jpeg",
                            FoodPrice = 54000,
                            FoodPriceLess = 32400f,
                            FoodTitle = "Trà ô long mộc hoa kem cheese",
                            RestaurantId = 2
                        },
                        new
                        {
                            FoodId = 26,
                            FoodDescription = "",
                            FoodImageUrl = "./ImageForSeedData/Food/Restaurant2/food25.jpeg",
                            FoodPrice = 54000,
                            FoodPriceLess = 32400f,
                            FoodTitle = "Trà oolong Kim Phượng kem cheese",
                            RestaurantId = 2
                        },
                        new
                        {
                            FoodId = 27,
                            FoodDescription = "",
                            FoodImageUrl = "./ImageForSeedData/Food/Restaurant2/food27.jpeg",
                            FoodPrice = 59000,
                            FoodPriceLess = 35400f,
                            FoodTitle = "Trà sữa oreo cake cream",
                            RestaurantId = 2
                        },
                        new
                        {
                            FoodId = 28,
                            FoodDescription = "",
                            FoodImageUrl = "./ImageForSeedData/Food/Restaurant2/food28.jpeg",
                            FoodPrice = 55000,
                            FoodPriceLess = 33000f,
                            FoodTitle = "Trà sữa trân châu ngọc trai trắng",
                            RestaurantId = 2
                        },
                        new
                        {
                            FoodId = 29,
                            FoodDescription = "",
                            FoodImageUrl = "./ImageForSeedData/Food/Restaurant2/food29.jpeg",
                            FoodPrice = 55000,
                            FoodPriceLess = 33000f,
                            FoodTitle = "Trà sữa trân châu ngọc trai đen",
                            RestaurantId = 2
                        },
                        new
                        {
                            FoodId = 30,
                            FoodDescription = "",
                            FoodImageUrl = "./ImageForSeedData/Food/Restaurant2/food30.jpeg",
                            FoodPrice = 68000,
                            FoodPriceLess = 40800f,
                            FoodTitle = "Trà hoa quả Royaltea đặc biệt",
                            RestaurantId = 2
                        },
                        new
                        {
                            FoodId = 31,
                            FoodDescription = "",
                            FoodImageUrl = "./ImageForSeedData/Food/Restaurant2/food31.jpeg",
                            FoodPrice = 65000,
                            FoodPriceLess = 39000f,
                            FoodTitle = "Trà xanh cam bưởi dâu tây",
                            RestaurantId = 2
                        },
                        new
                        {
                            FoodId = 32,
                            FoodDescription = "",
                            FoodImageUrl = "./ImageForSeedData/Food/Restaurant2/food32.jpeg",
                            FoodPrice = 65000,
                            FoodPriceLess = 39000f,
                            FoodTitle = "Trà xanh cam bưởi nhiệt đới",
                            RestaurantId = 2
                        },
                        new
                        {
                            FoodId = 33,
                            FoodDescription = "",
                            FoodImageUrl = "./ImageForSeedData/Food/Restaurant2/food33.jpeg",
                            FoodPrice = 58000,
                            FoodPriceLess = 34800f,
                            FoodTitle = "Scola kem cheese",
                            RestaurantId = 2
                        },
                        new
                        {
                            FoodId = 34,
                            FoodDescription = "",
                            FoodImageUrl = "./ImageForSeedData/Food/Restaurant2/food34.jpeg",
                            FoodPrice = 55000,
                            FoodPriceLess = 33000f,
                            FoodTitle = "Scola cake cream",
                            RestaurantId = 2
                        },
                        new
                        {
                            FoodId = 35,
                            FoodDescription = "",
                            FoodImageUrl = "./ImageForSeedData/Food/Restaurant2/food35.jpeg",
                            FoodPrice = 67000,
                            FoodPriceLess = 40200f,
                            FoodTitle = "Smoothie xoài kem cheese",
                            RestaurantId = 2
                        },
                        new
                        {
                            FoodId = 36,
                            FoodDescription = "",
                            FoodImageUrl = "./ImageForSeedData/Food/Restaurant2/food36.jpeg",
                            FoodPrice = 67000,
                            FoodPriceLess = 40200f,
                            FoodTitle = "Smoothie dưa hấu kem cheese",
                            RestaurantId = 2
                        },
                        new
                        {
                            FoodId = 37,
                            FoodDescription = "",
                            FoodImageUrl = "./ImageForSeedData/Food/Restaurant2/food37.jpeg",
                            FoodPrice = 67000,
                            FoodPriceLess = 40200f,
                            FoodTitle = "Smoothie ruby",
                            RestaurantId = 2
                        });
                });

            modelBuilder.Entity("ShopeeApi.Models.RelationCategoryFood", b =>
                {
                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<int>("FoodId")
                        .HasColumnType("int");

                    b.HasKey("CategoryId", "FoodId");

                    b.HasIndex("FoodId");

                    b.ToTable("RelationCategoryFoods");
                });

            modelBuilder.Entity("ShopeeApi.Models.Restaurant", b =>
                {
                    b.Property<int>("RsId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RsId"), 1L, 1);

                    b.Property<string>("RsAddress")
                        .IsRequired()
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("RsImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(600)");

                    b.Property<string>("RsOpenTime")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("RsPrinceRange")
                        .IsRequired()
                        .HasColumnType("nvarchar(800)");

                    b.Property<int>("RsPromotion")
                        .HasColumnType("int");

                    b.Property<string>("RsProvince")
                        .IsRequired()
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("RsRefeLike")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<int>("RsReviews")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<float>("RsStar")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("real")
                        .HasDefaultValue(1f);

                    b.Property<string>("RsTitle")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("RsType")
                        .IsRequired()
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("RsId");

                    b.HasIndex("RsTitle")
                        .IsUnique();

                    b.ToTable("Restaurants");

                    b.HasData(
                        new
                        {
                            RsId = 1,
                            RsAddress = "606/52 Đường 3 Tháng 2, P. 14, Quận 10, TP. HCM",
                            RsImageUrl = "./ImageForSeedData/Restaurant/restaurant1.jpg",
                            RsOpenTime = "6:00 - 22:00",
                            RsPrinceRange = "44,000 - 85,000",
                            RsPromotion = 0,
                            RsProvince = "TP.HCM",
                            RsRefeLike = false,
                            RsReviews = 1,
                            RsStar = 5f,
                            RsTitle = "Bếp Bà Muối - Ăn Vặt Online",
                            RsType = "QUANAN"
                        },
                        new
                        {
                            RsId = 2,
                            RsAddress = "35 Sơn Kỳ, P. Sơn Kỳ, Tân Phú, TP. HCM",
                            RsImageUrl = "./ImageForSeedData/Restaurant/restaurant2.jpg",
                            RsOpenTime = "8:15 - 22:20",
                            RsPrinceRange = "45,000 - 60,000",
                            RsPromotion = 50,
                            RsProvince = "TP.HCM",
                            RsRefeLike = false,
                            RsReviews = 500,
                            RsStar = 4.5f,
                            RsTitle = "Royaltea Vietnam By Hongkong - Sơn Kỳ",
                            RsType = "CAFE/DESSERT"
                        },
                        new
                        {
                            RsId = 3,
                            RsAddress = "115B Tôn Đản, P. 14, Quận 4, TP. HCM",
                            RsImageUrl = "./ImageForSeedData/Restaurant/restaurant3.jpg",
                            RsOpenTime = "6:00 - 20:11",
                            RsPrinceRange = "15,000 - 30,000",
                            RsPromotion = 0,
                            RsProvince = "TP.HCM",
                            RsRefeLike = false,
                            RsReviews = 999,
                            RsStar = 4.5f,
                            RsTitle = "Anh Thư - Bánh Mì & Bún Thịt Nướng",
                            RsType = "ANVAT/VIAHE"
                        },
                        new
                        {
                            RsId = 4,
                            RsAddress = "322 Phạm Hùng, P. 4, Quận 8, TP. HCM",
                            RsImageUrl = "./ImageForSeedData/Restaurant/restaurant4.jpeg",
                            RsOpenTime = "7:00 - 21:30",
                            RsPrinceRange = "30,000 - 50,000",
                            RsPromotion = 5,
                            RsProvince = "TP.HCM",
                            RsRefeLike = true,
                            RsReviews = 100,
                            RsStar = 4.5f,
                            RsTitle = "Mì Quảng 3 Anh Em - Phạm Hùng",
                            RsType = "QUANAN"
                        },
                        new
                        {
                            RsId = 5,
                            RsAddress = "38 Đường Số 13, P. Bình Thọ, Thủ Đức, TP. HCM",
                            RsImageUrl = "./ImageForSeedData/Restaurant/restaurant5.jpg",
                            RsOpenTime = "9:00 - 21:00",
                            RsPrinceRange = "14,000 - 30,000",
                            RsPromotion = 10,
                            RsProvince = "TP.HCM",
                            RsRefeLike = false,
                            RsReviews = 999,
                            RsStar = 4.5f,
                            RsTitle = "Kim Milk Tea - Trà Sữa, Nước Ép & Ăn Vặt",
                            RsType = "CAFE/DESSERT"
                        },
                        new
                        {
                            RsId = 6,
                            RsAddress = "122 Nguyễn Khoái, P. 2, Quận 4, TP. HCM",
                            RsImageUrl = "./ImageForSeedData/Restaurant/restaurant6.jpg",
                            RsOpenTime = "7:20 - 21:45",
                            RsPrinceRange = "15,000 - 69,000",
                            RsPromotion = 10,
                            RsProvince = "TP.HCM",
                            RsRefeLike = false,
                            RsReviews = 999,
                            RsStar = 4.5f,
                            RsTitle = "Min Kee - Mì Khô & Trà Hong Kong",
                            RsType = "QUANAN"
                        },
                        new
                        {
                            RsId = 7,
                            RsAddress = "18A/29 Nguyễn Thị Minh Khai, P. Đa Kao, Quận 1, TP. HCM",
                            RsImageUrl = "./ImageForSeedData/Restaurant/restaurant7.jpg",
                            RsOpenTime = "8:30 - 20:25",
                            RsPrinceRange = "95,000 - 150,000",
                            RsPromotion = 5,
                            RsProvince = "TP.HCM",
                            RsRefeLike = true,
                            RsReviews = 999,
                            RsStar = 4.5f,
                            RsTitle = "Bánh Bò Thốt Nốt COCOCake - Lò Bánh Minh Khai",
                            RsType = "QUANAN"
                        },
                        new
                        {
                            RsId = 8,
                            RsAddress = "26 Huỳnh Lan Khanh, P. 2, Tân Bình, TP. HCM",
                            RsImageUrl = "./ImageForSeedData/Restaurant/restaurant8.jpg",
                            RsOpenTime = "7:00 - 20:45",
                            RsPrinceRange = "20,000 - 100,000",
                            RsPromotion = 5,
                            RsProvince = "TP.HCM",
                            RsRefeLike = false,
                            RsReviews = 999,
                            RsStar = 4.5f,
                            RsTitle = "Việt - Cơm Chay",
                            RsType = "ANCHAY"
                        },
                        new
                        {
                            RsId = 9,
                            RsAddress = "420/11 Huỳnh Văn Bánh, P. 14, Phú Nhuận, TP. HCM",
                            RsImageUrl = "./ImageForSeedData/Restaurant/restaurant9.jpeg",
                            RsOpenTime = "9:00 - 19:00",
                            RsPrinceRange = "105,000 - 150,000",
                            RsPromotion = 0,
                            RsProvince = "TP.HCM",
                            RsRefeLike = false,
                            RsReviews = 50,
                            RsStar = 4.5f,
                            RsTitle = "Bánh Quế Hà Lan - Huỳnh Văn Bánh",
                            RsType = "TIEMBANH"
                        });
                });

            modelBuilder.Entity("ShopeeApi.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<byte[]>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<byte[]>("PasswordSalt")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("UserName")
                        .IsUnique();

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            PasswordHash = new byte[] { 120, 86, 104, 9, 108, 249, 146, 54, 159, 86, 56, 115, 199, 181, 98, 213, 15, 88, 71, 98, 164, 60, 255, 173, 35, 252, 210, 102, 202, 188, 227, 92, 150, 73, 102, 143, 49, 97, 174, 183, 190, 165, 140, 164, 100, 84, 112, 109, 166, 121, 77, 110, 213, 18, 103, 17, 59, 83, 136, 45, 114, 17, 77, 181 },
                            PasswordSalt = new byte[] { 190, 134, 222, 235, 131, 75, 50, 109, 214, 219, 34, 30, 73, 95, 197, 44, 9, 149, 145, 106, 233, 104, 16, 216, 133, 31, 68, 219, 7, 82, 62, 87, 156, 255, 179, 209, 168, 141, 170, 81, 100, 222, 205, 178, 195, 166, 19, 254, 50, 31, 51, 247, 32, 24, 98, 131, 94, 19, 214, 185, 133, 63, 188, 43, 184, 122, 235, 58, 29, 63, 238, 197, 91, 25, 127, 58, 88, 129, 233, 178, 191, 200, 206, 220, 182, 165, 46, 180, 232, 14, 254, 211, 179, 185, 206, 116, 233, 147, 37, 222, 53, 132, 230, 236, 120, 247, 215, 167, 95, 25, 219, 237, 209, 116, 121, 179, 219, 2, 250, 231, 108, 160, 84, 5, 122, 208, 220, 91 },
                            Role = 928399,
                            UserName = "nhoxhieuro5@gmail.com"
                        },
                        new
                        {
                            Id = 2,
                            PasswordHash = new byte[] { 182, 4, 130, 68, 255, 109, 209, 204, 187, 252, 109, 141, 49, 201, 166, 140, 48, 11, 115, 162, 212, 127, 162, 196, 194, 243, 116, 24, 155, 158, 247, 114, 62, 191, 214, 238, 235, 230, 43, 115, 237, 183, 188, 44, 231, 102, 163, 84, 244, 161, 43, 105, 44, 90, 120, 84, 129, 103, 122, 167, 178, 176, 233, 242 },
                            PasswordSalt = new byte[] { 172, 159, 243, 123, 67, 104, 85, 234, 235, 146, 13, 32, 148, 229, 25, 4, 155, 207, 130, 171, 3, 211, 85, 99, 172, 147, 110, 188, 60, 8, 127, 144, 85, 162, 132, 101, 253, 104, 106, 141, 12, 231, 156, 196, 60, 197, 173, 89, 36, 133, 68, 118, 38, 7, 55, 196, 95, 173, 43, 20, 4, 14, 27, 82, 1, 92, 201, 131, 96, 209, 158, 227, 116, 51, 182, 186, 169, 180, 23, 40, 235, 247, 235, 23, 31, 33, 51, 2, 58, 63, 187, 65, 68, 102, 88, 200, 236, 106, 146, 81, 73, 29, 86, 217, 181, 28, 3, 109, 31, 77, 174, 216, 233, 223, 85, 90, 251, 65, 124, 255, 144, 157, 188, 141, 93, 60, 69, 35 },
                            Role = 468255,
                            UserName = "chaymetwa"
                        },
                        new
                        {
                            Id = 3,
                            PasswordHash = new byte[] { 77, 59, 185, 154, 193, 87, 126, 32, 202, 183, 255, 253, 154, 191, 53, 238, 46, 135, 103, 82, 237, 155, 6, 63, 255, 114, 234, 57, 240, 144, 172, 73, 169, 54, 199, 37, 34, 253, 205, 254, 86, 190, 231, 159, 66, 213, 245, 41, 84, 73, 177, 15, 148, 64, 178, 44, 160, 152, 109, 40, 36, 196, 39, 248 },
                            PasswordSalt = new byte[] { 18, 106, 176, 168, 91, 250, 7, 134, 237, 210, 108, 51, 191, 74, 87, 5, 193, 64, 167, 37, 91, 255, 67, 103, 86, 54, 36, 62, 114, 67, 168, 214, 64, 248, 89, 237, 192, 120, 38, 117, 235, 91, 144, 28, 226, 175, 38, 5, 193, 6, 105, 140, 192, 98, 55, 26, 134, 127, 193, 253, 20, 86, 192, 32, 82, 44, 106, 83, 84, 116, 213, 108, 137, 67, 63, 123, 242, 244, 90, 125, 130, 209, 234, 197, 203, 56, 98, 150, 72, 143, 181, 162, 3, 57, 138, 215, 39, 12, 125, 125, 119, 173, 100, 176, 113, 170, 76, 194, 22, 155, 5, 41, 209, 44, 212, 152, 62, 215, 4, 146, 48, 55, 20, 208, 116, 207, 67, 97 },
                            Role = 468255,
                            UserName = "metmoichua"
                        },
                        new
                        {
                            Id = 4,
                            PasswordHash = new byte[] { 2, 104, 223, 13, 253, 116, 155, 122, 133, 168, 90, 83, 109, 79, 194, 230, 161, 47, 240, 56, 36, 69, 124, 168, 232, 42, 93, 179, 31, 62, 219, 74, 111, 188, 223, 69, 24, 115, 212, 172, 80, 166, 184, 177, 154, 153, 110, 113, 17, 83, 37, 166, 135, 202, 211, 184, 189, 181, 28, 159, 180, 111, 111, 218 },
                            PasswordSalt = new byte[] { 212, 156, 69, 0, 149, 220, 169, 239, 45, 103, 114, 101, 99, 25, 102, 217, 240, 250, 16, 111, 207, 72, 104, 11, 118, 31, 146, 68, 173, 251, 137, 67, 129, 100, 150, 195, 209, 197, 0, 138, 87, 250, 237, 232, 214, 131, 16, 105, 78, 210, 42, 156, 244, 92, 135, 63, 209, 35, 104, 20, 165, 110, 219, 175, 118, 164, 86, 52, 217, 56, 105, 247, 224, 167, 177, 123, 197, 25, 33, 202, 113, 27, 33, 195, 214, 123, 158, 246, 222, 247, 233, 60, 116, 207, 110, 87, 167, 145, 60, 155, 57, 162, 106, 230, 46, 121, 109, 101, 218, 212, 44, 24, 79, 99, 186, 13, 248, 73, 240, 182, 193, 89, 51, 178, 152, 41, 139, 80 },
                            Role = 468255,
                            UserName = "hoiaita"
                        });
                });

            modelBuilder.Entity("ShopeeApi.Models.Category", b =>
                {
                    b.HasOne("ShopeeApi.Models.Restaurant", "Restaurant")
                        .WithMany("Categories")
                        .HasForeignKey("RestaurantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Restaurant");
                });

            modelBuilder.Entity("ShopeeApi.Models.Food", b =>
                {
                    b.HasOne("ShopeeApi.Models.Restaurant", "Restaurant")
                        .WithMany("Foods")
                        .HasForeignKey("RestaurantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Restaurant");
                });

            modelBuilder.Entity("ShopeeApi.Models.RelationCategoryFood", b =>
                {
                    b.HasOne("ShopeeApi.Models.Category", "Category")
                        .WithMany("RelationCategoryFoods")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ShopeeApi.Models.Food", "Food")
                        .WithMany("RelationCategoryFoods")
                        .HasForeignKey("FoodId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("Food");
                });

            modelBuilder.Entity("ShopeeApi.Models.Category", b =>
                {
                    b.Navigation("RelationCategoryFoods");
                });

            modelBuilder.Entity("ShopeeApi.Models.Food", b =>
                {
                    b.Navigation("RelationCategoryFoods");
                });

            modelBuilder.Entity("ShopeeApi.Models.Restaurant", b =>
                {
                    b.Navigation("Categories");

                    b.Navigation("Foods");
                });
#pragma warning restore 612, 618
        }
    }
}
