// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ShopeeApi.Datas;

#nullable disable

namespace ShopeeApi.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("ShopeeApi.Models.Category", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CategoryId"), 1L, 1);

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("CategoryTag")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("RestaurantId")
                        .HasColumnType("int");

                    b.HasKey("CategoryId");

                    b.HasIndex("RestaurantId");

                    b.HasIndex("CategoryTag", "RestaurantId")
                        .IsUnique();

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            CategoryId = 1,
                            CategoryName = "MENU",
                            CategoryTag = "menu",
                            RestaurantId = 1
                        },
                        new
                        {
                            CategoryId = 2,
                            CategoryName = "FREESHIP XTRA SIÊU ƯU ĐÃI - GIẢM 50%",
                            CategoryTag = "freeship50%",
                            RestaurantId = 2
                        },
                        new
                        {
                            CategoryId = 3,
                            CategoryName = "NOWFOOD DAY",
                            CategoryTag = "nowfoodday",
                            RestaurantId = 2
                        },
                        new
                        {
                            CategoryId = 4,
                            CategoryName = "NEW",
                            CategoryTag = "new",
                            RestaurantId = 2
                        },
                        new
                        {
                            CategoryId = 5,
                            CategoryName = "ROYAL BLACK TIGER",
                            CategoryTag = "royalblacktiger",
                            RestaurantId = 2
                        },
                        new
                        {
                            CategoryId = 6,
                            CategoryName = "ROYAL CHEESE TEA",
                            CategoryTag = "royalcheesetea",
                            RestaurantId = 2
                        },
                        new
                        {
                            CategoryId = 7,
                            CategoryName = "MILK TEA",
                            CategoryTag = "milktea",
                            RestaurantId = 2
                        },
                        new
                        {
                            CategoryId = 8,
                            CategoryName = "FRESH FRUIT TEA",
                            CategoryTag = "freshfruittea",
                            RestaurantId = 2
                        },
                        new
                        {
                            CategoryId = 9,
                            CategoryName = "MATCHA & CHOCOLATE",
                            CategoryTag = "matchachocolate",
                            RestaurantId = 2
                        },
                        new
                        {
                            CategoryId = 10,
                            CategoryName = "SMOOTHIE CHEESE",
                            CategoryTag = "smoothiecheese",
                            RestaurantId = 2
                        },
                        new
                        {
                            CategoryId = 11,
                            CategoryName = "BÁNH MÌ",
                            CategoryTag = "banhmi",
                            RestaurantId = 3
                        },
                        new
                        {
                            CategoryId = 12,
                            CategoryName = "BÚN",
                            CategoryTag = "bun",
                            RestaurantId = 3
                        },
                        new
                        {
                            CategoryId = 13,
                            CategoryName = "MÓN THÊM",
                            CategoryTag = "monthem",
                            RestaurantId = 3
                        },
                        new
                        {
                            CategoryId = 14,
                            CategoryName = "THỨC UỐNG",
                            CategoryTag = "thucuong",
                            RestaurantId = 3
                        },
                        new
                        {
                            CategoryId = 15,
                            CategoryName = "KHUYẾN MÃI HOT",
                            CategoryTag = "khuyenmaihot",
                            RestaurantId = 4
                        },
                        new
                        {
                            CategoryId = 16,
                            CategoryName = "COMBO HOT NƯỚC NGỌT",
                            CategoryTag = "combohotnuocngot",
                            RestaurantId = 4
                        },
                        new
                        {
                            CategoryId = 17,
                            CategoryName = "MÌ QUẢNG",
                            CategoryTag = "miquang",
                            RestaurantId = 4
                        },
                        new
                        {
                            CategoryId = 18,
                            CategoryName = "COMBO SIÊU TIẾT KIỆM 1 NGƯỜI",
                            CategoryTag = "combosieutietkiem1nguoi",
                            RestaurantId = 4
                        },
                        new
                        {
                            CategoryId = 19,
                            CategoryName = "COMBO 3 TÔ",
                            CategoryTag = "combo3to",
                            RestaurantId = 4
                        },
                        new
                        {
                            CategoryId = 20,
                            CategoryName = "MÓN THÊM",
                            CategoryTag = "monthem",
                            RestaurantId = 4
                        },
                        new
                        {
                            CategoryId = 21,
                            CategoryName = "NƯỚC UỐNG",
                            CategoryTag = "nuocuong",
                            RestaurantId = 4
                        },
                        new
                        {
                            CategoryId = 22,
                            CategoryName = "ĐẶC SẢN MIỀN TRUNG",
                            CategoryTag = "dacsanmientrung",
                            RestaurantId = 4
                        },
                        new
                        {
                            CategoryId = 23,
                            CategoryName = "NOWFOOD DAY",
                            CategoryTag = "nowfoodday",
                            RestaurantId = 5
                        },
                        new
                        {
                            CategoryId = 24,
                            CategoryName = "COMBO TRÀ SỮA",
                            CategoryTag = "combotrasua",
                            RestaurantId = 5
                        },
                        new
                        {
                            CategoryId = 25,
                            CategoryName = "TRÀ TRÁI CÂY NHIỆT ĐỚI",
                            CategoryTag = "tratraicaynhietdoi",
                            RestaurantId = 5
                        },
                        new
                        {
                            CategoryId = 26,
                            CategoryName = "SỮA TƯƠI ĐƯỜNG ĐEN",
                            CategoryTag = "suatuoiduongden",
                            RestaurantId = 5
                        },
                        new
                        {
                            CategoryId = 27,
                            CategoryName = "TRÀ SỮA",
                            CategoryTag = "trasua",
                            RestaurantId = 5
                        },
                        new
                        {
                            CategoryId = 28,
                            CategoryName = "LỤC TRÀ",
                            CategoryTag = "luctra",
                            RestaurantId = 5
                        },
                        new
                        {
                            CategoryId = 29,
                            CategoryName = "NƯỚC ÉP TRÁI CÂY TƯƠI",
                            CategoryTag = "nuoceptraicaytuoi",
                            RestaurantId = 5
                        },
                        new
                        {
                            CategoryId = 30,
                            CategoryName = "COMBO COUPLE",
                            CategoryTag = "combocouple",
                            RestaurantId = 5
                        },
                        new
                        {
                            CategoryId = 31,
                            CategoryName = "MÌ CỰC PHẨM",
                            CategoryTag = "micucpham",
                            RestaurantId = 6
                        },
                        new
                        {
                            CategoryId = 32,
                            CategoryName = "SỦI CẢO / HOÀNH THÁNH",
                            CategoryTag = "suicaohoanhthanh",
                            RestaurantId = 6
                        },
                        new
                        {
                            CategoryId = 33,
                            CategoryName = "MÌ KHÔ",
                            CategoryTag = "mikho",
                            RestaurantId = 6
                        },
                        new
                        {
                            CategoryId = 34,
                            CategoryName = "MÌ NƯỚC",
                            CategoryTag = "minuoc",
                            RestaurantId = 6
                        },
                        new
                        {
                            CategoryId = 35,
                            CategoryName = "HỦ TIẾU KHÔ",
                            CategoryTag = "hutieukho",
                            RestaurantId = 6
                        },
                        new
                        {
                            CategoryId = 36,
                            CategoryName = "MÓN ĂN THÊM",
                            CategoryTag = "monanthem",
                            RestaurantId = 6
                        },
                        new
                        {
                            CategoryId = 37,
                            CategoryName = "TRÀ THANH NHIỆT",
                            CategoryTag = "trathanhnhiet",
                            RestaurantId = 6
                        },
                        new
                        {
                            CategoryId = 38,
                            CategoryName = "SIÊU SALE MÙA LỄ HỘI",
                            CategoryTag = "sieusalemualehoi",
                            RestaurantId = 7
                        },
                        new
                        {
                            CategoryId = 39,
                            CategoryName = "BÁNH BÒ",
                            CategoryTag = "banhbo",
                            RestaurantId = 7
                        },
                        new
                        {
                            CategoryId = 40,
                            CategoryName = "BÁNH DA LỢN",
                            CategoryTag = "banhdalon",
                            RestaurantId = 7
                        },
                        new
                        {
                            CategoryId = 41,
                            CategoryName = "RAU CÂU FLAN CHEESE",
                            CategoryTag = "raucauflancheese",
                            RestaurantId = 7
                        },
                        new
                        {
                            CategoryId = 42,
                            CategoryName = "RAU CÂU SƠN THỦY",
                            CategoryTag = "raucausonthuy",
                            RestaurantId = 7
                        },
                        new
                        {
                            CategoryId = 43,
                            CategoryName = "RAU CÂU DỪA",
                            CategoryTag = "raucaudua",
                            RestaurantId = 7
                        },
                        new
                        {
                            CategoryId = 44,
                            CategoryName = "KEM",
                            CategoryTag = "kem",
                            RestaurantId = 7
                        },
                        new
                        {
                            CategoryId = 45,
                            CategoryName = "COMBO",
                            CategoryTag = "combo",
                            RestaurantId = 7
                        },
                        new
                        {
                            CategoryId = 46,
                            CategoryName = "YOGHURT",
                            CategoryTag = "yoghurt",
                            RestaurantId = 7
                        },
                        new
                        {
                            CategoryId = 47,
                            CategoryName = "BÁNH FLAN",
                            CategoryTag = "banhflan",
                            RestaurantId = 7
                        },
                        new
                        {
                            CategoryId = 48,
                            CategoryName = "CHÈ",
                            CategoryTag = "che",
                            RestaurantId = 7
                        },
                        new
                        {
                            CategoryId = 49,
                            CategoryName = "CỐT DỪA",
                            CategoryTag = "cotdua",
                            RestaurantId = 7
                        },
                        new
                        {
                            CategoryId = 50,
                            CategoryName = "COMBO",
                            CategoryTag = "combo",
                            RestaurantId = 8
                        },
                        new
                        {
                            CategoryId = 51,
                            CategoryName = "MÓN CƠM",
                            CategoryTag = "moncom",
                            RestaurantId = 8
                        },
                        new
                        {
                            CategoryId = 52,
                            CategoryName = "MÓN SỢI",
                            CategoryTag = "monsoi",
                            RestaurantId = 8
                        },
                        new
                        {
                            CategoryId = 53,
                            CategoryName = "MÓN LẨU",
                            CategoryTag = "monlau",
                            RestaurantId = 8
                        },
                        new
                        {
                            CategoryId = 54,
                            CategoryName = "BANH1 BISCOTTI",
                            CategoryTag = "banhbiscotti",
                            RestaurantId = 9
                        });
                });

            modelBuilder.Entity("ShopeeApi.Models.Food", b =>
                {
                    b.Property<int>("FoodId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FoodId"), 1L, 1);

                    b.Property<string>("FoodDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FoodImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("FoodPrice")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<float>("FoodPriceLess")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("real")
                        .HasDefaultValue(0f);

                    b.Property<string>("FoodTitle")
                        .IsRequired()
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("RestaurantId")
                        .HasColumnType("int");

                    b.HasKey("FoodId");

                    b.HasIndex("RestaurantId");

                    b.HasIndex("FoodTitle", "RestaurantId")
                        .IsUnique();

                    b.ToTable("Foods");

                    b.HasData(
                        new
                        {
                            FoodId = 1,
                            FoodDescription = "Hộp đã được nâng cấp lên từ 300->400 gram vẫn nguyên giá cux",
                            FoodImageUrl = "./ImageForSeedData/Food/Restaurant1/food1.jpeg",
                            FoodPrice = 85000,
                            FoodPriceLess = 0f,
                            FoodTitle = "Pate bơ béo (400gram)",
                            RestaurantId = 1
                        },
                        new
                        {
                            FoodId = 2,
                            FoodDescription = "Hộp đã được nâng cấp từ 300->400 gram với giá giữ nguyên",
                            FoodImageUrl = "./ImageForSeedData/Food/Restaurant1/food2.jpeg",
                            FoodPrice = 85000,
                            FoodPriceLess = 0f,
                            FoodTitle = "Pate sate (400gram)",
                            RestaurantId = 1
                        },
                        new
                        {
                            FoodId = 3,
                            FoodDescription = "1 hủ/ 150gr",
                            FoodImageUrl = "./ImageForSeedData/Food/Restaurant1/food3.jpeg",
                            FoodPrice = 44000,
                            FoodPriceLess = 0f,
                            FoodTitle = "Muối nguyễn thần thánh",
                            RestaurantId = 1
                        },
                        new
                        {
                            FoodId = 4,
                            FoodDescription = "",
                            FoodImageUrl = "./ImageForSeedData/Food/Restaurant2/food4.jpeg",
                            FoodPrice = 50000,
                            FoodPriceLess = 30000f,
                            FoodTitle = "Trà sữa trân châu hoàng kim",
                            RestaurantId = 2
                        },
                        new
                        {
                            FoodId = 5,
                            FoodDescription = "",
                            FoodImageUrl = "./ImageForSeedData/Food/Restaurant2/food5.jpeg",
                            FoodPrice = 45000,
                            FoodPriceLess = 27000f,
                            FoodTitle = "Trà sữa Hongkong Royal",
                            RestaurantId = 2
                        },
                        new
                        {
                            FoodId = 6,
                            FoodDescription = "",
                            FoodImageUrl = "./ImageForSeedData/Food/Restaurant2/food6.jpeg",
                            FoodPrice = 45000,
                            FoodPriceLess = 27000f,
                            FoodTitle = "Trà sữa lúa mạch",
                            RestaurantId = 2
                        },
                        new
                        {
                            FoodId = 7,
                            FoodDescription = "",
                            FoodImageUrl = "./ImageForSeedData/Food/Restaurant2/food7.jpeg",
                            FoodPrice = 45000,
                            FoodPriceLess = 27000f,
                            FoodTitle = "Hồng trà sữa",
                            RestaurantId = 2
                        },
                        new
                        {
                            FoodId = 8,
                            FoodDescription = "",
                            FoodImageUrl = "./ImageForSeedData/Food/Restaurant2/food7.jpeg",
                            FoodPrice = 45000,
                            FoodPriceLess = 27000f,
                            FoodTitle = "Trà sữa hoa nhài",
                            RestaurantId = 2
                        },
                        new
                        {
                            FoodId = 9,
                            FoodDescription = "",
                            FoodImageUrl = "./ImageForSeedData/Food/Restaurant2/food7.jpeg",
                            FoodPrice = 45000,
                            FoodPriceLess = 27000f,
                            FoodTitle = "Trà sữa olong kim phượng",
                            RestaurantId = 2
                        },
                        new
                        {
                            FoodId = 10,
                            FoodDescription = "",
                            FoodImageUrl = "./ImageForSeedData/Food/Restaurant2/food7.jpeg",
                            FoodPrice = 45000,
                            FoodPriceLess = 27000f,
                            FoodTitle = "Trà sữa olong bạch đào",
                            RestaurantId = 2
                        },
                        new
                        {
                            FoodId = 11,
                            FoodDescription = "không chọn được mức đá",
                            FoodImageUrl = "./ImageForSeedData/Food/Restaurant2/food11.png",
                            FoodPrice = 50000,
                            FoodPriceLess = 30000f,
                            FoodTitle = "Sữa tươi trân châu hoàng kim",
                            RestaurantId = 2
                        },
                        new
                        {
                            FoodId = 12,
                            FoodDescription = "",
                            FoodImageUrl = "./ImageForSeedData/Food/Restaurant2/food11.png",
                            FoodPrice = 50000,
                            FoodPriceLess = 30000f,
                            FoodTitle = "Đường Đen Sầu Riêng",
                            RestaurantId = 2
                        },
                        new
                        {
                            FoodId = 13,
                            FoodDescription = "không thể để đá riêng",
                            FoodImageUrl = "./ImageForSeedData/Food/Restaurant2/food13.jpeg",
                            FoodPrice = 50000,
                            FoodPriceLess = 30000f,
                            FoodTitle = "Sữa tươi trân châu đường đen",
                            RestaurantId = 2
                        },
                        new
                        {
                            FoodId = 14,
                            FoodDescription = "",
                            FoodImageUrl = "./ImageForSeedData/Food/Restaurant2/food14.jpeg",
                            FoodPrice = 50000,
                            FoodPriceLess = 30000f,
                            FoodTitle = "Trà sữa trân châu đường đen",
                            RestaurantId = 2
                        },
                        new
                        {
                            FoodId = 15,
                            FoodDescription = "Size M",
                            FoodImageUrl = "./ImageForSeedData/Food/Restaurant2/food15.jpeg",
                            FoodPrice = 57000,
                            FoodPriceLess = 34200f,
                            FoodTitle = "Matcha đường đen",
                            RestaurantId = 2
                        },
                        new
                        {
                            FoodId = 16,
                            FoodDescription = "Thơm ngon",
                            FoodImageUrl = "./ImageForSeedData/Food/Restaurant2/food16.jpeg",
                            FoodPrice = 65000,
                            FoodPriceLess = 39000f,
                            FoodTitle = "Trà táo xanh kiwi",
                            RestaurantId = 2
                        },
                        new
                        {
                            FoodId = 17,
                            FoodDescription = "SizeM",
                            FoodImageUrl = "./ImageForSeedData/Food/Restaurant2/food17.jpeg",
                            FoodPrice = 69000,
                            FoodPriceLess = 41400f,
                            FoodTitle = "Matcha đường đen kem cheese",
                            RestaurantId = 2
                        },
                        new
                        {
                            FoodId = 18,
                            FoodDescription = "",
                            FoodImageUrl = "./ImageForSeedData/Food/Restaurant2/food11.png",
                            FoodPrice = 55000,
                            FoodPriceLess = 33000f,
                            FoodTitle = "Trà sữa khoai môn đường đen",
                            RestaurantId = 2
                        },
                        new
                        {
                            FoodId = 19,
                            FoodDescription = "",
                            FoodImageUrl = "./ImageForSeedData/Food/Restaurant2/food19.jpeg",
                            FoodPrice = 54000,
                            FoodPriceLess = 32400f,
                            FoodTitle = "Trà lúa mạch kem cheese",
                            RestaurantId = 2
                        },
                        new
                        {
                            FoodId = 20,
                            FoodDescription = "",
                            FoodImageUrl = "./ImageForSeedData/Food/Restaurant2/food20.jpeg",
                            FoodPrice = 54000,
                            FoodPriceLess = 32400f,
                            FoodTitle = "Hồng trà Royal kem cheese",
                            RestaurantId = 2
                        },
                        new
                        {
                            FoodId = 21,
                            FoodDescription = "",
                            FoodImageUrl = "./ImageForSeedData/Food/Restaurant2/food21.jpeg",
                            FoodPrice = 57000,
                            FoodPriceLess = 34200f,
                            FoodTitle = "Trà sương mù London kem cheese",
                            RestaurantId = 2
                        },
                        new
                        {
                            FoodId = 22,
                            FoodDescription = "",
                            FoodImageUrl = "./ImageForSeedData/Food/Restaurant2/food22.jpeg",
                            FoodPrice = 54000,
                            FoodPriceLess = 34200f,
                            FoodTitle = "Trà xanh Golden kem cheese",
                            RestaurantId = 2
                        },
                        new
                        {
                            FoodId = 23,
                            FoodDescription = "",
                            FoodImageUrl = "./ImageForSeedData/Food/Restaurant2/food23.jpeg",
                            FoodPrice = 54000,
                            FoodPriceLess = 32400f,
                            FoodTitle = "Trà ô long bạch đào kem cheese",
                            RestaurantId = 2
                        },
                        new
                        {
                            FoodId = 24,
                            FoodDescription = "",
                            FoodImageUrl = "./ImageForSeedData/Food/Restaurant2/food24.jpeg",
                            FoodPrice = 54000,
                            FoodPriceLess = 32400f,
                            FoodTitle = "Trà bách hoa kem cheese",
                            RestaurantId = 2
                        },
                        new
                        {
                            FoodId = 25,
                            FoodDescription = "",
                            FoodImageUrl = "./ImageForSeedData/Food/Restaurant2/food25.jpeg",
                            FoodPrice = 54000,
                            FoodPriceLess = 32400f,
                            FoodTitle = "Trà ô long mộc hoa kem cheese",
                            RestaurantId = 2
                        },
                        new
                        {
                            FoodId = 26,
                            FoodDescription = "",
                            FoodImageUrl = "./ImageForSeedData/Food/Restaurant2/food25.jpeg",
                            FoodPrice = 54000,
                            FoodPriceLess = 32400f,
                            FoodTitle = "Trà oolong Kim Phượng kem cheese",
                            RestaurantId = 2
                        },
                        new
                        {
                            FoodId = 27,
                            FoodDescription = "",
                            FoodImageUrl = "./ImageForSeedData/Food/Restaurant2/food27.jpeg",
                            FoodPrice = 59000,
                            FoodPriceLess = 35400f,
                            FoodTitle = "Trà sữa oreo cake cream",
                            RestaurantId = 2
                        },
                        new
                        {
                            FoodId = 28,
                            FoodDescription = "",
                            FoodImageUrl = "./ImageForSeedData/Food/Restaurant2/food28.jpeg",
                            FoodPrice = 55000,
                            FoodPriceLess = 33000f,
                            FoodTitle = "Trà sữa trân châu ngọc trai trắng",
                            RestaurantId = 2
                        },
                        new
                        {
                            FoodId = 29,
                            FoodDescription = "",
                            FoodImageUrl = "./ImageForSeedData/Food/Restaurant2/food29.jpeg",
                            FoodPrice = 55000,
                            FoodPriceLess = 33000f,
                            FoodTitle = "Trà sữa trân châu ngọc trai đen",
                            RestaurantId = 2
                        },
                        new
                        {
                            FoodId = 30,
                            FoodDescription = "",
                            FoodImageUrl = "./ImageForSeedData/Food/Restaurant2/food30.jpeg",
                            FoodPrice = 68000,
                            FoodPriceLess = 40800f,
                            FoodTitle = "Trà hoa quả Royaltea đặc biệt",
                            RestaurantId = 2
                        },
                        new
                        {
                            FoodId = 31,
                            FoodDescription = "",
                            FoodImageUrl = "./ImageForSeedData/Food/Restaurant2/food31.jpeg",
                            FoodPrice = 65000,
                            FoodPriceLess = 39000f,
                            FoodTitle = "Trà xanh cam bưởi dâu tây",
                            RestaurantId = 2
                        },
                        new
                        {
                            FoodId = 32,
                            FoodDescription = "",
                            FoodImageUrl = "./ImageForSeedData/Food/Restaurant2/food32.jpeg",
                            FoodPrice = 65000,
                            FoodPriceLess = 39000f,
                            FoodTitle = "Trà xanh cam bưởi nhiệt đới",
                            RestaurantId = 2
                        },
                        new
                        {
                            FoodId = 33,
                            FoodDescription = "",
                            FoodImageUrl = "./ImageForSeedData/Food/Restaurant2/food33.jpeg",
                            FoodPrice = 58000,
                            FoodPriceLess = 34800f,
                            FoodTitle = "Scola kem cheese",
                            RestaurantId = 2
                        },
                        new
                        {
                            FoodId = 34,
                            FoodDescription = "",
                            FoodImageUrl = "./ImageForSeedData/Food/Restaurant2/food34.jpeg",
                            FoodPrice = 55000,
                            FoodPriceLess = 33000f,
                            FoodTitle = "Scola cake cream",
                            RestaurantId = 2
                        },
                        new
                        {
                            FoodId = 35,
                            FoodDescription = "",
                            FoodImageUrl = "./ImageForSeedData/Food/Restaurant2/food35.jpeg",
                            FoodPrice = 67000,
                            FoodPriceLess = 40200f,
                            FoodTitle = "Smoothie xoài kem cheese",
                            RestaurantId = 2
                        },
                        new
                        {
                            FoodId = 36,
                            FoodDescription = "",
                            FoodImageUrl = "./ImageForSeedData/Food/Restaurant2/food36.jpeg",
                            FoodPrice = 67000,
                            FoodPriceLess = 40200f,
                            FoodTitle = "Smoothie dưa hấu kem cheese",
                            RestaurantId = 2
                        },
                        new
                        {
                            FoodId = 37,
                            FoodDescription = "",
                            FoodImageUrl = "./ImageForSeedData/Food/Restaurant2/food37.jpeg",
                            FoodPrice = 67000,
                            FoodPriceLess = 40200f,
                            FoodTitle = "Smoothie ruby",
                            RestaurantId = 2
                        },
                        new
                        {
                            FoodId = 38,
                            FoodDescription = "",
                            FoodImageUrl = "./ImageForSeedData/Food/Restaurant3/food38.jpeg",
                            FoodPrice = 26000,
                            FoodPriceLess = 0f,
                            FoodTitle = "Bánh mì thịt nướng",
                            RestaurantId = 3
                        },
                        new
                        {
                            FoodId = 39,
                            FoodDescription = "",
                            FoodImageUrl = "./ImageForSeedData/Food/Restaurant3/food39.jpeg",
                            FoodPrice = 32000,
                            FoodPriceLess = 0f,
                            FoodTitle = "Bánh mì thịt nướng đặc biệt",
                            RestaurantId = 3
                        },
                        new
                        {
                            FoodId = 40,
                            FoodDescription = "",
                            FoodImageUrl = "./ImageForSeedData/Food/Restaurant3/food40.jpeg",
                            FoodPrice = 47000,
                            FoodPriceLess = 0f,
                            FoodTitle = "Bún thịt nướng đặc biệt",
                            RestaurantId = 3
                        },
                        new
                        {
                            FoodId = 41,
                            FoodDescription = "",
                            FoodImageUrl = "./ImageForSeedData/Food/Restaurant3/food41.jpeg",
                            FoodPrice = 33000,
                            FoodPriceLess = 0f,
                            FoodTitle = "Bún thịt nướng",
                            RestaurantId = 3
                        },
                        new
                        {
                            FoodId = 42,
                            FoodDescription = "",
                            FoodImageUrl = "./ImageForSeedData/Food/Restaurant3/food42.jpeg",
                            FoodPrice = 33000,
                            FoodPriceLess = 0f,
                            FoodTitle = "Bún nem nướng",
                            RestaurantId = 3
                        },
                        new
                        {
                            FoodId = 43,
                            FoodDescription = "",
                            FoodImageUrl = "./ImageForSeedData/Food/Restaurant3/food43.jpeg",
                            FoodPrice = 30000,
                            FoodPriceLess = 0f,
                            FoodTitle = "Bún Chả giò",
                            RestaurantId = 3
                        },
                        new
                        {
                            FoodId = 44,
                            FoodDescription = "Cái",
                            FoodImageUrl = "./ImageForSeedData/Food/Restaurant3/food44.jpeg",
                            FoodPrice = 6000,
                            FoodPriceLess = 0f,
                            FoodTitle = "Chả giò",
                            RestaurantId = 3
                        },
                        new
                        {
                            FoodId = 45,
                            FoodDescription = "Xiên",
                            FoodImageUrl = "./ImageForSeedData/Food/Restaurant3/food45.jpeg",
                            FoodPrice = 18000,
                            FoodPriceLess = 0f,
                            FoodTitle = "Thịt xiên",
                            RestaurantId = 3
                        },
                        new
                        {
                            FoodId = 46,
                            FoodDescription = "Viên",
                            FoodImageUrl = "./ImageForSeedData/Food/Restaurant3/food46.jpeg",
                            FoodPrice = 6000,
                            FoodPriceLess = 0f,
                            FoodTitle = "Thịt viên",
                            RestaurantId = 3
                        },
                        new
                        {
                            FoodId = 47,
                            FoodDescription = "",
                            FoodImageUrl = "./ImageForSeedData/Food/Restaurant3/food47.jpeg",
                            FoodPrice = 12000,
                            FoodPriceLess = 0f,
                            FoodTitle = "Nem nướng",
                            RestaurantId = 3
                        },
                        new
                        {
                            FoodId = 48,
                            FoodDescription = "",
                            FoodImageUrl = "./ImageForSeedData/Food/Restaurant3/food48.jpeg",
                            FoodPrice = 3000,
                            FoodPriceLess = 0f,
                            FoodTitle = "Bún thêm",
                            RestaurantId = 3
                        },
                        new
                        {
                            FoodId = 49,
                            FoodDescription = "",
                            FoodImageUrl = "./ImageForSeedData/Food/Restaurant3/food49.jpeg",
                            FoodPrice = 3000,
                            FoodPriceLess = 0f,
                            FoodTitle = "Rau thêm",
                            RestaurantId = 3
                        },
                        new
                        {
                            FoodId = 50,
                            FoodDescription = "Thành phần: bí đao, hạt chia, thục địa, la hán quả, bông cóc ... Đường phèn",
                            FoodImageUrl = "./ImageForSeedData/Food/Restaurant3/food50.jpeg",
                            FoodPrice = 15000,
                            FoodPriceLess = 0f,
                            FoodTitle = "Sâm Bí Đao Hạt Chia",
                            RestaurantId = 3
                        },
                        new
                        {
                            FoodId = 51,
                            FoodDescription = "Thành phần: BÍ ĐAOM THỤC ĐỊA, LA HÁN QUẢ, BÔNG CÚC ... ĐƯỜNG PHÈN",
                            FoodImageUrl = "./ImageForSeedData/Food/Restaurant3/food51.jpeg",
                            FoodPrice = 12000,
                            FoodPriceLess = 0f,
                            FoodTitle = "Sâm Bí Đao Đường Phền",
                            RestaurantId = 3
                        },
                        new
                        {
                            FoodId = 52,
                            FoodDescription = "Gọi 0906743795 Hổ trợ nhanh nhất nhé cảm ơn ạ ^^",
                            FoodImageUrl = "./ImageForSeedData/Food/Restaurant4/food52.jpeg",
                            FoodPrice = 55000,
                            FoodPriceLess = 49500f,
                            FoodTitle = "Mì Quảng thịt, trứng cút",
                            RestaurantId = 4
                        },
                        new
                        {
                            FoodId = 53,
                            FoodDescription = "",
                            FoodImageUrl = "./ImageForSeedData/Food/Restaurant4/food53.jpeg",
                            FoodPrice = 50000,
                            FoodPriceLess = 45000f,
                            FoodTitle = "Mì Quảng Chả Nhỏ",
                            RestaurantId = 4
                        },
                        new
                        {
                            FoodId = 54,
                            FoodDescription = "Gọi 0906743795 Hỗ trợ nha",
                            FoodImageUrl = "./ImageForSeedData/Food/Restaurant4/food54.jpeg",
                            FoodPrice = 55000,
                            FoodPriceLess = 49500f,
                            FoodTitle = "Mì Quảng Chả cua",
                            RestaurantId = 4
                        },
                        new
                        {
                            FoodId = 55,
                            FoodDescription = "",
                            FoodImageUrl = "./ImageForSeedData/Food/Restaurant4/food55.jpeg",
                            FoodPrice = 60000,
                            FoodPriceLess = 54000f,
                            FoodTitle = "Mì Quảng bắp bò + chả",
                            RestaurantId = 4
                        },
                        new
                        {
                            FoodId = 56,
                            FoodDescription = "",
                            FoodImageUrl = "./ImageForSeedData/Food/Restaurant4/food56.jpeg",
                            FoodPrice = 60000,
                            FoodPriceLess = 54000f,
                            FoodTitle = "Mì Quảng sườn non + chả",
                            RestaurantId = 4
                        },
                        new
                        {
                            FoodId = 57,
                            FoodDescription = "",
                            FoodImageUrl = "./ImageForSeedData/Food/Restaurant4/food57.jpeg",
                            FoodPrice = 50000,
                            FoodPriceLess = 45000f,
                            FoodTitle = "Chén tôm thêm",
                            RestaurantId = 4
                        },
                        new
                        {
                            FoodId = 58,
                            FoodDescription = "0906743795 Hổ trợ nhanh nhất nhé cảm ơn ạ ^^",
                            FoodImageUrl = "./ImageForSeedData/Food/Restaurant4/food58.jpeg",
                            FoodPrice = 70000,
                            FoodPriceLess = 63000f,
                            FoodTitle = "Mì Quảng Đặt biệt",
                            RestaurantId = 4
                        },
                        new
                        {
                            FoodId = 59,
                            FoodDescription = "0906743795 Hổ trợ nhanh nhất nhé cảm ơn ạ ^^",
                            FoodImageUrl = "./ImageForSeedData/Food/Restaurant4/food59.jpeg",
                            FoodPrice = 60000,
                            FoodPriceLess = 54000f,
                            FoodTitle = "Mì Quảng gà chọi rút xương",
                            RestaurantId = 4
                        },
                        new
                        {
                            FoodId = 60,
                            FoodDescription = "0906743795 Hổ trợ nhanh nhất nhé cảm ơn ạ ^^",
                            FoodImageUrl = "./ImageForSeedData/Food/Restaurant4/food60.jpeg",
                            FoodPrice = 55000,
                            FoodPriceLess = 49500f,
                            FoodTitle = "Mì Quảng tôm thịt",
                            RestaurantId = 4
                        },
                        new
                        {
                            FoodId = 61,
                            FoodDescription = "TẶNG KÈM TƯƠNG ỚT HỘI AN SIÊU NGON",
                            FoodImageUrl = "./ImageForSeedData/Food/Restaurant4/food61.jpg",
                            FoodPrice = 65000,
                            FoodPriceLess = 58500f,
                            FoodTitle = "Combo 1 tô mì quảng chọn món + 1 pepsi/nước suối",
                            RestaurantId = 4
                        },
                        new
                        {
                            FoodId = 62,
                            FoodDescription = "0906743795 Hổ trợ nhanh nhất nhé cảm ơn ạ ^^",
                            FoodImageUrl = "./ImageForSeedData/Food/Restaurant4/food62.jpeg",
                            FoodPrice = 215000,
                            FoodPriceLess = 193500f,
                            FoodTitle = "Combo 3 tô mì quảng đặc biệt 3 anh em",
                            RestaurantId = 4
                        },
                        new
                        {
                            FoodId = 63,
                            FoodDescription = "Hổ trợ nhanh nhất nhé cảm ơn ạ ^^",
                            FoodImageUrl = "./ImageForSeedData/Food/Restaurant4/food63.jpeg",
                            FoodPrice = 180000,
                            FoodPriceLess = 162000f,
                            FoodTitle = "Combo 3 tô mì Quảng gà chọi rút xương",
                            RestaurantId = 4
                        },
                        new
                        {
                            FoodId = 64,
                            FoodDescription = "0906743795 Hổ trợ nhanh nhất nhé cảm ơn ạ ^^",
                            FoodImageUrl = "./ImageForSeedData/Food/Restaurant4/food64.jpeg",
                            FoodPrice = 165000,
                            FoodPriceLess = 148500f,
                            FoodTitle = "Combo 3 tô mì Quảng Thit trứng cút",
                            RestaurantId = 4
                        },
                        new
                        {
                            FoodId = 65,
                            FoodDescription = "",
                            FoodImageUrl = "./ImageForSeedData/Food/Restaurant4/food65.jpg",
                            FoodPrice = 10000,
                            FoodPriceLess = 9000f,
                            FoodTitle = "Bánh tráng thêm",
                            RestaurantId = 4
                        },
                        new
                        {
                            FoodId = 66,
                            FoodDescription = "",
                            FoodImageUrl = "./ImageForSeedData/Food/Restaurant4/food66.jpg",
                            FoodPrice = 10000,
                            FoodPriceLess = 9000f,
                            FoodTitle = "Rau thêm",
                            RestaurantId = 4
                        },
                        new
                        {
                            FoodId = 67,
                            FoodDescription = "",
                            FoodImageUrl = "./ImageForSeedData/Food/Restaurant4/food67.jpg",
                            FoodPrice = 20000,
                            FoodPriceLess = 18000f,
                            FoodTitle = "Pepsi",
                            RestaurantId = 4
                        },
                        new
                        {
                            FoodId = 68,
                            FoodDescription = "",
                            FoodImageUrl = "./ImageForSeedData/Food/Restaurant4/food68.jpg",
                            FoodPrice = 20000,
                            FoodPriceLess = 18000f,
                            FoodTitle = "7up",
                            RestaurantId = 4
                        },
                        new
                        {
                            FoodId = 69,
                            FoodDescription = "",
                            FoodImageUrl = "./ImageForSeedData/Food/Restaurant4/food69.jpeg",
                            FoodPrice = 55000,
                            FoodPriceLess = 49500f,
                            FoodTitle = "Bánh tráng gạo 300gram",
                            RestaurantId = 4
                        },
                        new
                        {
                            FoodId = 70,
                            FoodDescription = "1 hủ",
                            FoodImageUrl = "./ImageForSeedData/Food/Restaurant4/food70.jpeg",
                            FoodPrice = 90000,
                            FoodPriceLess = 81000f,
                            FoodTitle = "Tương ớt hội an",
                            RestaurantId = 4
                        },
                        new
                        {
                            FoodId = 71,
                            FoodDescription = "Trà sữa, trân châu, bánh flan size L",
                            FoodImageUrl = "./ImageForSeedData/Food/Restaurant5/food71.jpeg",
                            FoodPrice = 32000,
                            FoodPriceLess = 25600f,
                            FoodTitle = "Combo 3",
                            RestaurantId = 5
                        },
                        new
                        {
                            FoodId = 72,
                            FoodDescription = "Trà sữa + 1 topping (trân châu/sương sáo/thạch dẻo) size L",
                            FoodImageUrl = "./ImageForSeedData/Food/Restaurant5/food72.jpeg",
                            FoodPrice = 24000,
                            FoodPriceLess = 19200f,
                            FoodTitle = "Trà sữa + 1 topping (trân châu/sương sáo/thạch dẻo) size L",
                            RestaurantId = 5
                        },
                        new
                        {
                            FoodId = 73,
                            FoodDescription = "",
                            FoodImageUrl = "./ImageForSeedData/Food/Restaurant5/food73.jpeg",
                            FoodPrice = 34000,
                            FoodPriceLess = 27200f,
                            FoodTitle = "Dưa hấu ép",
                            RestaurantId = 5
                        },
                        new
                        {
                            FoodId = 74,
                            FoodDescription = "4 ly Trà sữa full topping size XL",
                            FoodImageUrl = "./ImageForSeedData/Food/Restaurant5/food74.jpeg",
                            FoodPrice = 168000,
                            FoodPriceLess = 134400f,
                            FoodTitle = "Combo 4 ly Combo 5",
                            RestaurantId = 5
                        },
                        new
                        {
                            FoodId = 75,
                            FoodDescription = "Trà sữa full topping size XL",
                            FoodImageUrl = "./ImageForSeedData/Food/Restaurant5/food75.jpeg",
                            FoodPrice = 42000,
                            FoodPriceLess = 33600f,
                            FoodTitle = "Combo 5",
                            RestaurantId = 5
                        },
                        new
                        {
                            FoodId = 76,
                            FoodDescription = "Trà sữa, thạch dẻo, thạch phô mai, bánh flan size L",
                            FoodImageUrl = "./ImageForSeedData/Food/Restaurant5/food76.jpeg",
                            FoodPrice = 37000,
                            FoodPriceLess = 29600f,
                            FoodTitle = "Combo 4",
                            RestaurantId = 5
                        },
                        new
                        {
                            FoodId = 77,
                            FoodDescription = "Trà sữa, thạch dẻo, thạch phô mai size L",
                            FoodImageUrl = "./ImageForSeedData/Food/Restaurant5/food77.jpeg",
                            FoodPrice = 32000,
                            FoodPriceLess = 25600f,
                            FoodTitle = "Combo 2",
                            RestaurantId = 5
                        },
                        new
                        {
                            FoodId = 78,
                            FoodDescription = "",
                            FoodImageUrl = "./ImageForSeedData/Food/Restaurant5/food78.jpeg",
                            FoodPrice = 35000,
                            FoodPriceLess = 28000f,
                            FoodTitle = "Trà đào cam sả",
                            RestaurantId = 5
                        },
                        new
                        {
                            FoodId = 79,
                            FoodDescription = "",
                            FoodImageUrl = "./ImageForSeedData/Food/Restaurant5/food79.jpeg",
                            FoodPrice = 22000,
                            FoodPriceLess = 17600f,
                            FoodTitle = "Trà đào dầm",
                            RestaurantId = 5
                        },
                        new
                        {
                            FoodId = 80,
                            FoodDescription = "",
                            FoodImageUrl = "./ImageForSeedData/Food/Restaurant5/food80.jpeg",
                            FoodPrice = 21000,
                            FoodPriceLess = 16800f,
                            FoodTitle = "Lục trà bạc hà",
                            RestaurantId = 5
                        },
                        new
                        {
                            FoodId = 81,
                            FoodDescription = "",
                            FoodImageUrl = "./ImageForSeedData/Food/Restaurant5/food81.jpeg",
                            FoodPrice = 34000,
                            FoodPriceLess = 27200f,
                            FoodTitle = "Trà Cam Nhài",
                            RestaurantId = 5
                        },
                        new
                        {
                            FoodId = 82,
                            FoodDescription = "",
                            FoodImageUrl = "./ImageForSeedData/Food/Restaurant5/food82.jpeg",
                            FoodPrice = 25000,
                            FoodPriceLess = 20000f,
                            FoodTitle = "Sữa tươi trân châu đường đen",
                            RestaurantId = 5
                        },
                        new
                        {
                            FoodId = 83,
                            FoodDescription = "",
                            FoodImageUrl = "./ImageForSeedData/Food/Restaurant5/food83.jpeg",
                            FoodPrice = 30000,
                            FoodPriceLess = 24000f,
                            FoodTitle = "Sữa tươi matcha trân châu đường đen",
                            RestaurantId = 5
                        },
                        new
                        {
                            FoodId = 84,
                            FoodDescription = "",
                            FoodImageUrl = "./ImageForSeedData/Food/Restaurant5/food84.jpeg",
                            FoodPrice = 25000,
                            FoodPriceLess = 20000f,
                            FoodTitle = "Sữa tươi đường đen sương sáo",
                            RestaurantId = 5
                        },
                        new
                        {
                            FoodId = 85,
                            FoodDescription = "",
                            FoodImageUrl = "./ImageForSeedData/Food/Restaurant5/food85.jpeg",
                            FoodPrice = 21000,
                            FoodPriceLess = 16800f,
                            FoodTitle = "Trà sữa",
                            RestaurantId = 5
                        },
                        new
                        {
                            FoodId = 86,
                            FoodDescription = "",
                            FoodImageUrl = "./ImageForSeedData/Food/Restaurant5/food86.jpeg",
                            FoodPrice = 27000,
                            FoodPriceLess = 21600f,
                            FoodTitle = "Trà sữa socola",
                            RestaurantId = 5
                        },
                        new
                        {
                            FoodId = 87,
                            FoodDescription = "",
                            FoodImageUrl = "./ImageForSeedData/Food/Restaurant5/food87.jpeg",
                            FoodPrice = 22000,
                            FoodPriceLess = 17600f,
                            FoodTitle = "Trà sữa hoa đậu biếc",
                            RestaurantId = 5
                        },
                        new
                        {
                            FoodId = 88,
                            FoodDescription = "",
                            FoodImageUrl = "./ImageForSeedData/Food/Restaurant5/food88.jpeg",
                            FoodPrice = 32000,
                            FoodPriceLess = 25600f,
                            FoodTitle = "Thơm ép",
                            RestaurantId = 5
                        },
                        new
                        {
                            FoodId = 89,
                            FoodDescription = "",
                            FoodImageUrl = "./ImageForSeedData/Food/Restaurant5/food89.jpeg",
                            FoodPrice = 32000,
                            FoodPriceLess = 25600f,
                            FoodTitle = "Ổi ép",
                            RestaurantId = 5
                        },
                        new
                        {
                            FoodId = 90,
                            FoodDescription = "",
                            FoodImageUrl = "./ImageForSeedData/Food/Restaurant5/food90.jpeg",
                            FoodPrice = 48000,
                            FoodPriceLess = 38400f,
                            FoodTitle = "Trà sữa + Trà sữa socola",
                            RestaurantId = 5
                        });
                });

            modelBuilder.Entity("ShopeeApi.Models.RelationCategoryFood", b =>
                {
                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<int>("FoodId")
                        .HasColumnType("int");

                    b.HasKey("CategoryId", "FoodId");

                    b.HasIndex("FoodId");

                    b.ToTable("RelationCategoryFoods");
                });

            modelBuilder.Entity("ShopeeApi.Models.Restaurant", b =>
                {
                    b.Property<int>("RsId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RsId"), 1L, 1);

                    b.Property<string>("RsAddress")
                        .IsRequired()
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("RsImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(600)");

                    b.Property<string>("RsOpenTime")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("RsPrinceRange")
                        .IsRequired()
                        .HasColumnType("nvarchar(800)");

                    b.Property<int>("RsPromotion")
                        .HasColumnType("int");

                    b.Property<string>("RsProvince")
                        .IsRequired()
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("RsRefeLike")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<int>("RsReviews")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<float>("RsStar")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("real")
                        .HasDefaultValue(1f);

                    b.Property<string>("RsTitle")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("RsType")
                        .IsRequired()
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("RsId");

                    b.HasIndex("RsTitle")
                        .IsUnique();

                    b.ToTable("Restaurants");

                    b.HasData(
                        new
                        {
                            RsId = 1,
                            RsAddress = "606/52 Đường 3 Tháng 2, P. 14, Quận 10, TP. HCM",
                            RsImageUrl = "./ImageForSeedData/Restaurant/restaurant1.jpg",
                            RsOpenTime = "6:00 - 22:00",
                            RsPrinceRange = "44,000 - 85,000",
                            RsPromotion = 0,
                            RsProvince = "TP.HCM",
                            RsRefeLike = false,
                            RsReviews = 1,
                            RsStar = 5f,
                            RsTitle = "Bếp Bà Muối - Ăn Vặt Online",
                            RsType = "QUANAN"
                        },
                        new
                        {
                            RsId = 2,
                            RsAddress = "35 Sơn Kỳ, P. Sơn Kỳ, Tân Phú, TP. HCM",
                            RsImageUrl = "./ImageForSeedData/Restaurant/restaurant2.jpg",
                            RsOpenTime = "8:15 - 22:20",
                            RsPrinceRange = "45,000 - 60,000",
                            RsPromotion = 50,
                            RsProvince = "TP.HCM",
                            RsRefeLike = false,
                            RsReviews = 500,
                            RsStar = 4.5f,
                            RsTitle = "Royaltea Vietnam By Hongkong - Sơn Kỳ",
                            RsType = "CAFE/DESSERT"
                        },
                        new
                        {
                            RsId = 3,
                            RsAddress = "115B Tôn Đản, P. 14, Quận 4, TP. HCM",
                            RsImageUrl = "./ImageForSeedData/Restaurant/restaurant3.jpg",
                            RsOpenTime = "6:00 - 20:11",
                            RsPrinceRange = "15,000 - 30,000",
                            RsPromotion = 0,
                            RsProvince = "TP.HCM",
                            RsRefeLike = false,
                            RsReviews = 999,
                            RsStar = 4.5f,
                            RsTitle = "Anh Thư - Bánh Mì & Bún Thịt Nướng",
                            RsType = "ANVAT/VIAHE"
                        },
                        new
                        {
                            RsId = 4,
                            RsAddress = "322 Phạm Hùng, P. 4, Quận 8, TP. HCM",
                            RsImageUrl = "./ImageForSeedData/Restaurant/restaurant4.jpeg",
                            RsOpenTime = "7:00 - 21:30",
                            RsPrinceRange = "30,000 - 50,000",
                            RsPromotion = 5,
                            RsProvince = "TP.HCM",
                            RsRefeLike = true,
                            RsReviews = 100,
                            RsStar = 4.5f,
                            RsTitle = "Mì Quảng 3 Anh Em - Phạm Hùng",
                            RsType = "QUANAN"
                        },
                        new
                        {
                            RsId = 5,
                            RsAddress = "38 Đường Số 13, P. Bình Thọ, Thủ Đức, TP. HCM",
                            RsImageUrl = "./ImageForSeedData/Restaurant/restaurant5.jpg",
                            RsOpenTime = "9:00 - 21:00",
                            RsPrinceRange = "14,000 - 30,000",
                            RsPromotion = 10,
                            RsProvince = "TP.HCM",
                            RsRefeLike = false,
                            RsReviews = 999,
                            RsStar = 4.5f,
                            RsTitle = "Kim Milk Tea - Trà Sữa, Nước Ép & Ăn Vặt",
                            RsType = "CAFE/DESSERT"
                        },
                        new
                        {
                            RsId = 6,
                            RsAddress = "122 Nguyễn Khoái, P. 2, Quận 4, TP. HCM",
                            RsImageUrl = "./ImageForSeedData/Restaurant/restaurant6.jpg",
                            RsOpenTime = "7:20 - 21:45",
                            RsPrinceRange = "15,000 - 69,000",
                            RsPromotion = 10,
                            RsProvince = "TP.HCM",
                            RsRefeLike = false,
                            RsReviews = 999,
                            RsStar = 4.5f,
                            RsTitle = "Min Kee - Mì Khô & Trà Hong Kong",
                            RsType = "QUANAN"
                        },
                        new
                        {
                            RsId = 7,
                            RsAddress = "18A/29 Nguyễn Thị Minh Khai, P. Đa Kao, Quận 1, TP. HCM",
                            RsImageUrl = "./ImageForSeedData/Restaurant/restaurant7.jpg",
                            RsOpenTime = "8:30 - 20:25",
                            RsPrinceRange = "95,000 - 150,000",
                            RsPromotion = 5,
                            RsProvince = "TP.HCM",
                            RsRefeLike = true,
                            RsReviews = 999,
                            RsStar = 4.5f,
                            RsTitle = "Bánh Bò Thốt Nốt COCOCake - Lò Bánh Minh Khai",
                            RsType = "QUANAN"
                        },
                        new
                        {
                            RsId = 8,
                            RsAddress = "26 Huỳnh Lan Khanh, P. 2, Tân Bình, TP. HCM",
                            RsImageUrl = "./ImageForSeedData/Restaurant/restaurant8.jpg",
                            RsOpenTime = "7:00 - 20:45",
                            RsPrinceRange = "20,000 - 100,000",
                            RsPromotion = 5,
                            RsProvince = "TP.HCM",
                            RsRefeLike = false,
                            RsReviews = 999,
                            RsStar = 4.5f,
                            RsTitle = "Việt - Cơm Chay",
                            RsType = "ANCHAY"
                        },
                        new
                        {
                            RsId = 9,
                            RsAddress = "420/11 Huỳnh Văn Bánh, P. 14, Phú Nhuận, TP. HCM",
                            RsImageUrl = "./ImageForSeedData/Restaurant/restaurant9.jpeg",
                            RsOpenTime = "9:00 - 19:00",
                            RsPrinceRange = "105,000 - 150,000",
                            RsPromotion = 0,
                            RsProvince = "TP.HCM",
                            RsRefeLike = false,
                            RsReviews = 50,
                            RsStar = 4.5f,
                            RsTitle = "Bánh Quế Hà Lan - Huỳnh Văn Bánh",
                            RsType = "TIEMBANH"
                        });
                });

            modelBuilder.Entity("ShopeeApi.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<byte[]>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<byte[]>("PasswordSalt")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("UserName")
                        .IsUnique();

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            PasswordHash = new byte[] { 97, 244, 89, 241, 167, 49, 22, 112, 45, 140, 144, 70, 224, 119, 115, 117, 228, 6, 103, 65, 22, 16, 89, 139, 16, 29, 15, 73, 165, 6, 183, 204, 11, 246, 18, 215, 8, 99, 220, 79, 203, 33, 124, 231, 64, 203, 89, 83, 129, 189, 96, 83, 186, 239, 12, 83, 138, 78, 198, 85, 63, 185, 52, 25 },
                            PasswordSalt = new byte[] { 100, 118, 196, 1, 229, 239, 108, 140, 136, 46, 101, 135, 208, 31, 197, 186, 91, 241, 255, 144, 234, 182, 243, 131, 128, 214, 161, 116, 194, 104, 20, 232, 162, 205, 133, 206, 185, 32, 235, 215, 25, 120, 100, 68, 168, 248, 199, 105, 52, 41, 179, 72, 86, 85, 217, 43, 239, 209, 130, 174, 16, 91, 236, 100, 209, 190, 126, 246, 93, 238, 158, 142, 255, 134, 92, 124, 178, 194, 221, 20, 73, 245, 84, 50, 182, 218, 30, 60, 36, 18, 98, 89, 99, 55, 19, 58, 50, 44, 66, 146, 177, 254, 144, 177, 77, 102, 231, 161, 248, 37, 231, 250, 169, 123, 56, 168, 213, 69, 153, 204, 177, 145, 139, 25, 23, 103, 56, 239 },
                            Role = 928399,
                            UserName = "nhoxhieuro5@gmail.com"
                        },
                        new
                        {
                            Id = 2,
                            PasswordHash = new byte[] { 88, 90, 241, 87, 42, 238, 127, 22, 81, 237, 234, 29, 36, 7, 86, 157, 147, 198, 147, 101, 2, 218, 175, 231, 60, 4, 156, 27, 224, 99, 136, 138, 96, 202, 61, 19, 30, 36, 83, 216, 157, 228, 125, 68, 114, 106, 189, 17, 146, 32, 33, 202, 116, 223, 79, 30, 72, 24, 59, 38, 25, 172, 227, 217 },
                            PasswordSalt = new byte[] { 44, 31, 86, 28, 169, 178, 250, 60, 195, 110, 47, 237, 190, 246, 14, 227, 159, 190, 216, 229, 180, 31, 161, 31, 16, 60, 197, 111, 120, 77, 149, 61, 229, 111, 92, 178, 166, 63, 37, 127, 94, 154, 134, 205, 149, 152, 182, 233, 154, 63, 218, 85, 100, 147, 6, 121, 184, 58, 215, 207, 3, 168, 165, 50, 94, 202, 54, 212, 121, 111, 75, 131, 229, 208, 227, 48, 65, 184, 250, 80, 164, 26, 188, 203, 102, 98, 211, 228, 161, 255, 170, 32, 215, 113, 90, 6, 238, 141, 134, 203, 106, 38, 200, 217, 79, 193, 143, 76, 57, 167, 110, 52, 72, 207, 14, 139, 155, 252, 100, 232, 147, 245, 128, 196, 114, 215, 214, 168 },
                            Role = 468255,
                            UserName = "chaymetwa"
                        },
                        new
                        {
                            Id = 3,
                            PasswordHash = new byte[] { 150, 97, 228, 219, 236, 235, 35, 206, 172, 66, 38, 203, 140, 36, 16, 139, 235, 214, 85, 89, 184, 235, 246, 186, 42, 72, 106, 224, 188, 178, 120, 238, 120, 107, 123, 49, 176, 223, 138, 70, 121, 141, 178, 164, 44, 50, 108, 242, 234, 174, 176, 128, 119, 155, 83, 158, 184, 104, 200, 248, 195, 187, 66, 56 },
                            PasswordSalt = new byte[] { 213, 202, 38, 236, 129, 170, 134, 134, 100, 166, 148, 152, 32, 11, 79, 48, 16, 201, 253, 232, 85, 187, 167, 185, 153, 204, 18, 120, 178, 231, 246, 180, 38, 217, 141, 1, 147, 52, 215, 85, 255, 199, 171, 171, 137, 207, 117, 252, 143, 163, 58, 80, 147, 200, 235, 104, 108, 186, 75, 36, 129, 19, 194, 146, 223, 69, 172, 43, 77, 93, 141, 209, 68, 138, 252, 182, 162, 17, 25, 239, 76, 90, 187, 9, 211, 155, 121, 201, 206, 102, 99, 193, 14, 5, 103, 61, 31, 45, 210, 20, 78, 220, 243, 242, 252, 206, 98, 116, 127, 53, 104, 52, 239, 210, 128, 92, 16, 185, 246, 236, 14, 45, 179, 206, 194, 219, 124, 205 },
                            Role = 468255,
                            UserName = "metmoichua"
                        },
                        new
                        {
                            Id = 4,
                            PasswordHash = new byte[] { 98, 27, 205, 236, 49, 110, 82, 148, 83, 86, 251, 86, 45, 232, 182, 44, 169, 185, 168, 237, 85, 179, 118, 79, 177, 81, 176, 33, 173, 209, 116, 183, 97, 76, 18, 142, 47, 188, 79, 47, 78, 76, 205, 14, 0, 110, 29, 81, 70, 145, 38, 87, 238, 118, 127, 214, 27, 154, 81, 44, 14, 249, 64, 219 },
                            PasswordSalt = new byte[] { 107, 163, 89, 33, 206, 203, 57, 245, 190, 221, 74, 174, 80, 180, 80, 233, 22, 15, 172, 164, 29, 239, 214, 149, 234, 118, 152, 56, 248, 135, 172, 248, 98, 3, 96, 7, 171, 174, 41, 129, 47, 145, 92, 185, 80, 250, 139, 133, 83, 118, 211, 145, 190, 132, 197, 123, 129, 221, 38, 81, 12, 22, 33, 102, 45, 16, 84, 137, 186, 243, 99, 216, 106, 50, 48, 133, 168, 165, 104, 120, 206, 133, 241, 49, 118, 102, 65, 158, 97, 218, 238, 55, 113, 233, 231, 97, 27, 32, 41, 177, 90, 196, 186, 53, 101, 56, 71, 101, 15, 41, 162, 49, 140, 34, 224, 103, 244, 143, 177, 254, 18, 15, 39, 38, 202, 221, 150, 100 },
                            Role = 468255,
                            UserName = "hoiaita"
                        });
                });

            modelBuilder.Entity("ShopeeApi.Models.Category", b =>
                {
                    b.HasOne("ShopeeApi.Models.Restaurant", "Restaurant")
                        .WithMany("Categories")
                        .HasForeignKey("RestaurantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Restaurant");
                });

            modelBuilder.Entity("ShopeeApi.Models.Food", b =>
                {
                    b.HasOne("ShopeeApi.Models.Restaurant", "Restaurant")
                        .WithMany("Foods")
                        .HasForeignKey("RestaurantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Restaurant");
                });

            modelBuilder.Entity("ShopeeApi.Models.RelationCategoryFood", b =>
                {
                    b.HasOne("ShopeeApi.Models.Category", "Category")
                        .WithMany("RelationCategoryFoods")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ShopeeApi.Models.Food", "Food")
                        .WithMany("RelationCategoryFoods")
                        .HasForeignKey("FoodId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("Food");
                });

            modelBuilder.Entity("ShopeeApi.Models.Category", b =>
                {
                    b.Navigation("RelationCategoryFoods");
                });

            modelBuilder.Entity("ShopeeApi.Models.Food", b =>
                {
                    b.Navigation("RelationCategoryFoods");
                });

            modelBuilder.Entity("ShopeeApi.Models.Restaurant", b =>
                {
                    b.Navigation("Categories");

                    b.Navigation("Foods");
                });
#pragma warning restore 612, 618
        }
    }
}
