version: '3.4'

services:

  frontend:
    image: 518h0090/shopeefoodhieuintern:frontend
    build:
      context: "./Frontend"
      dockerfile: Dockerfile
    restart: always
    ports:
      - "8000:80"
    depends_on:
      - shopeeapi

  shopeeapi:
    image: 518h0090/shopeefoodhieuintern:backend
    build:
      context: "./ShopeeApi"
      dockerfile: ShopeeApi/Dockerfile
    ports:
      - "49071:80"
    depends_on:
      - db

  db:
    image: "mcr.microsoft.com/mssql/server:2022-latest"
    ports:
      - "1433:1433"

    environment:
      SA_PASSWORD: "Hieuro5122"
      ACCEPT_EULA: "Y"
