// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ShopeeApi.Datas;

#nullable disable

namespace ShopeeApi.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20221011090237_AddSeedFood34")]
    partial class AddSeedFood34
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("ShopeeApi.Models.Category", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CategoryId"), 1L, 1);

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("CategoryTag")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("RestaurantId")
                        .HasColumnType("int");

                    b.HasKey("CategoryId");

                    b.HasIndex("RestaurantId");

                    b.HasIndex("CategoryTag", "RestaurantId")
                        .IsUnique();

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            CategoryId = 1,
                            CategoryName = "MENU",
                            CategoryTag = "menu",
                            RestaurantId = 1
                        },
                        new
                        {
                            CategoryId = 2,
                            CategoryName = "FREESHIP XTRA SIÊU ƯU ĐÃI - GIẢM 50%",
                            CategoryTag = "freeship50%",
                            RestaurantId = 2
                        },
                        new
                        {
                            CategoryId = 3,
                            CategoryName = "NOWFOOD DAY",
                            CategoryTag = "nowfoodday",
                            RestaurantId = 2
                        },
                        new
                        {
                            CategoryId = 4,
                            CategoryName = "NEW",
                            CategoryTag = "new",
                            RestaurantId = 2
                        },
                        new
                        {
                            CategoryId = 5,
                            CategoryName = "ROYAL BLACK TIGER",
                            CategoryTag = "royalblacktiger",
                            RestaurantId = 2
                        },
                        new
                        {
                            CategoryId = 6,
                            CategoryName = "ROYAL CHEESE TEA",
                            CategoryTag = "royalcheesetea",
                            RestaurantId = 2
                        },
                        new
                        {
                            CategoryId = 7,
                            CategoryName = "MILK TEA",
                            CategoryTag = "milktea",
                            RestaurantId = 2
                        },
                        new
                        {
                            CategoryId = 8,
                            CategoryName = "FRESH FRUIT TEA",
                            CategoryTag = "freshfruittea",
                            RestaurantId = 2
                        },
                        new
                        {
                            CategoryId = 9,
                            CategoryName = "MATCHA & CHOCOLATE",
                            CategoryTag = "matchachocolate",
                            RestaurantId = 2
                        },
                        new
                        {
                            CategoryId = 10,
                            CategoryName = "SMOOTHIE CHEESE",
                            CategoryTag = "smoothiecheese",
                            RestaurantId = 2
                        },
                        new
                        {
                            CategoryId = 11,
                            CategoryName = "BÁNH MÌ",
                            CategoryTag = "banhmi",
                            RestaurantId = 3
                        },
                        new
                        {
                            CategoryId = 12,
                            CategoryName = "BÚN",
                            CategoryTag = "bun",
                            RestaurantId = 3
                        },
                        new
                        {
                            CategoryId = 13,
                            CategoryName = "MÓN THÊM",
                            CategoryTag = "monthem",
                            RestaurantId = 3
                        },
                        new
                        {
                            CategoryId = 14,
                            CategoryName = "THỨC UỐNG",
                            CategoryTag = "thucuong",
                            RestaurantId = 3
                        },
                        new
                        {
                            CategoryId = 15,
                            CategoryName = "KHUYẾN MÃI HOT",
                            CategoryTag = "khuyenmaihot",
                            RestaurantId = 4
                        },
                        new
                        {
                            CategoryId = 16,
                            CategoryName = "COMBO HOT NƯỚC NGỌT",
                            CategoryTag = "combohotnuocngot",
                            RestaurantId = 4
                        },
                        new
                        {
                            CategoryId = 17,
                            CategoryName = "MÌ QUẢNG",
                            CategoryTag = "miquang",
                            RestaurantId = 4
                        },
                        new
                        {
                            CategoryId = 18,
                            CategoryName = "COMBO SIÊU TIẾT KIỆM 1 NGƯỜI",
                            CategoryTag = "combosieutietkiem1nguoi",
                            RestaurantId = 4
                        },
                        new
                        {
                            CategoryId = 19,
                            CategoryName = "COMBO 3 TÔ",
                            CategoryTag = "combo3to",
                            RestaurantId = 4
                        },
                        new
                        {
                            CategoryId = 20,
                            CategoryName = "MÓN THÊM",
                            CategoryTag = "monthem",
                            RestaurantId = 4
                        },
                        new
                        {
                            CategoryId = 21,
                            CategoryName = "NƯỚC UỐNG",
                            CategoryTag = "nuocuong",
                            RestaurantId = 4
                        },
                        new
                        {
                            CategoryId = 22,
                            CategoryName = "ĐẶC SẢN MIỀN TRUNG",
                            CategoryTag = "dacsanmientrung",
                            RestaurantId = 4
                        },
                        new
                        {
                            CategoryId = 23,
                            CategoryName = "NOWFOOD DAY",
                            CategoryTag = "nowfoodday",
                            RestaurantId = 5
                        },
                        new
                        {
                            CategoryId = 24,
                            CategoryName = "COMBO TRÀ SỮA",
                            CategoryTag = "combotrasua",
                            RestaurantId = 5
                        },
                        new
                        {
                            CategoryId = 25,
                            CategoryName = "TRÀ TRÁI CÂY NHIỆT ĐỚI",
                            CategoryTag = "tratraicaynhietdoi",
                            RestaurantId = 5
                        },
                        new
                        {
                            CategoryId = 26,
                            CategoryName = "SỮA TƯƠI ĐƯỜNG ĐEN",
                            CategoryTag = "suatuoiduongden",
                            RestaurantId = 5
                        },
                        new
                        {
                            CategoryId = 27,
                            CategoryName = "TRÀ SỮA",
                            CategoryTag = "trasua",
                            RestaurantId = 5
                        },
                        new
                        {
                            CategoryId = 28,
                            CategoryName = "LỤC TRÀ",
                            CategoryTag = "luctra",
                            RestaurantId = 5
                        },
                        new
                        {
                            CategoryId = 29,
                            CategoryName = "NƯỚC ÉP TRÁI CÂY TƯƠI",
                            CategoryTag = "nuoceptraicaytuoi",
                            RestaurantId = 5
                        },
                        new
                        {
                            CategoryId = 30,
                            CategoryName = "COMBO COUPLE",
                            CategoryTag = "combocouple",
                            RestaurantId = 5
                        },
                        new
                        {
                            CategoryId = 31,
                            CategoryName = "MÌ CỰC PHẨM",
                            CategoryTag = "micucpham",
                            RestaurantId = 6
                        },
                        new
                        {
                            CategoryId = 32,
                            CategoryName = "SỦI CẢO / HOÀNH THÁNH",
                            CategoryTag = "suicaohoanhthanh",
                            RestaurantId = 6
                        },
                        new
                        {
                            CategoryId = 33,
                            CategoryName = "MÌ KHÔ",
                            CategoryTag = "mikho",
                            RestaurantId = 6
                        },
                        new
                        {
                            CategoryId = 34,
                            CategoryName = "MÌ NƯỚC",
                            CategoryTag = "minuoc",
                            RestaurantId = 6
                        },
                        new
                        {
                            CategoryId = 35,
                            CategoryName = "HỦ TIẾU KHÔ",
                            CategoryTag = "hutieukho",
                            RestaurantId = 6
                        },
                        new
                        {
                            CategoryId = 36,
                            CategoryName = "MÓN ĂN THÊM",
                            CategoryTag = "monanthem",
                            RestaurantId = 6
                        },
                        new
                        {
                            CategoryId = 37,
                            CategoryName = "TRÀ THANH NHIỆT",
                            CategoryTag = "trathanhnhiet",
                            RestaurantId = 6
                        },
                        new
                        {
                            CategoryId = 38,
                            CategoryName = "SIÊU SALE MÙA LỄ HỘI",
                            CategoryTag = "sieusalemualehoi",
                            RestaurantId = 7
                        },
                        new
                        {
                            CategoryId = 39,
                            CategoryName = "BÁNH BÒ",
                            CategoryTag = "banhbo",
                            RestaurantId = 7
                        },
                        new
                        {
                            CategoryId = 40,
                            CategoryName = "BÁNH DA LỢN",
                            CategoryTag = "banhdalon",
                            RestaurantId = 7
                        },
                        new
                        {
                            CategoryId = 41,
                            CategoryName = "RAU CÂU FLAN CHEESE",
                            CategoryTag = "raucauflancheese",
                            RestaurantId = 7
                        },
                        new
                        {
                            CategoryId = 42,
                            CategoryName = "RAU CÂU SƠN THỦY",
                            CategoryTag = "raucausonthuy",
                            RestaurantId = 7
                        },
                        new
                        {
                            CategoryId = 43,
                            CategoryName = "RAU CÂU DỪA",
                            CategoryTag = "raucaudua",
                            RestaurantId = 7
                        },
                        new
                        {
                            CategoryId = 44,
                            CategoryName = "KEM",
                            CategoryTag = "kem",
                            RestaurantId = 7
                        },
                        new
                        {
                            CategoryId = 45,
                            CategoryName = "COMBO",
                            CategoryTag = "combo",
                            RestaurantId = 7
                        },
                        new
                        {
                            CategoryId = 46,
                            CategoryName = "YOGHURT",
                            CategoryTag = "yoghurt",
                            RestaurantId = 7
                        },
                        new
                        {
                            CategoryId = 47,
                            CategoryName = "BÁNH FLAN",
                            CategoryTag = "banhflan",
                            RestaurantId = 7
                        },
                        new
                        {
                            CategoryId = 48,
                            CategoryName = "CHÈ",
                            CategoryTag = "che",
                            RestaurantId = 7
                        },
                        new
                        {
                            CategoryId = 49,
                            CategoryName = "CỐT DỪA",
                            CategoryTag = "cotdua",
                            RestaurantId = 7
                        },
                        new
                        {
                            CategoryId = 50,
                            CategoryName = "COMBO",
                            CategoryTag = "combo",
                            RestaurantId = 8
                        },
                        new
                        {
                            CategoryId = 51,
                            CategoryName = "MÓN CƠM",
                            CategoryTag = "moncom",
                            RestaurantId = 8
                        },
                        new
                        {
                            CategoryId = 52,
                            CategoryName = "MÓN SỢI",
                            CategoryTag = "monsoi",
                            RestaurantId = 8
                        },
                        new
                        {
                            CategoryId = 53,
                            CategoryName = "MÓN LẨU",
                            CategoryTag = "monlau",
                            RestaurantId = 8
                        },
                        new
                        {
                            CategoryId = 54,
                            CategoryName = "BANH1 BISCOTTI",
                            CategoryTag = "banhbiscotti",
                            RestaurantId = 9
                        });
                });

            modelBuilder.Entity("ShopeeApi.Models.Food", b =>
                {
                    b.Property<int>("FoodId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FoodId"), 1L, 1);

                    b.Property<string>("FoodDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FoodImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("FoodPrice")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<float>("FoodPriceLess")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("real")
                        .HasDefaultValue(0f);

                    b.Property<string>("FoodTitle")
                        .IsRequired()
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("RestaurantId")
                        .HasColumnType("int");

                    b.HasKey("FoodId");

                    b.HasIndex("RestaurantId");

                    b.HasIndex("FoodTitle", "RestaurantId")
                        .IsUnique();

                    b.ToTable("Foods");

                    b.HasData(
                        new
                        {
                            FoodId = 1,
                            FoodDescription = "Hộp đã được nâng cấp lên từ 300->400 gram vẫn nguyên giá cux",
                            FoodImageUrl = "./ImageForSeedData/Food/Restaurant1/food1.jpeg",
                            FoodPrice = 85000,
                            FoodPriceLess = 0f,
                            FoodTitle = "Pate bơ béo (400gram)",
                            RestaurantId = 1
                        },
                        new
                        {
                            FoodId = 2,
                            FoodDescription = "Hộp đã được nâng cấp từ 300->400 gram với giá giữ nguyên",
                            FoodImageUrl = "./ImageForSeedData/Food/Restaurant1/food2.jpeg",
                            FoodPrice = 85000,
                            FoodPriceLess = 0f,
                            FoodTitle = "Pate sate (400gram)",
                            RestaurantId = 1
                        },
                        new
                        {
                            FoodId = 3,
                            FoodDescription = "1 hủ/ 150gr",
                            FoodImageUrl = "./ImageForSeedData/Food/Restaurant1/food3.jpeg",
                            FoodPrice = 44000,
                            FoodPriceLess = 0f,
                            FoodTitle = "Muối nguyễn thần thánh",
                            RestaurantId = 1
                        },
                        new
                        {
                            FoodId = 4,
                            FoodDescription = "",
                            FoodImageUrl = "./ImageForSeedData/Food/Restaurant2/food4.jpeg",
                            FoodPrice = 50000,
                            FoodPriceLess = 30000f,
                            FoodTitle = "Trà sữa trân châu hoàng kim",
                            RestaurantId = 2
                        },
                        new
                        {
                            FoodId = 5,
                            FoodDescription = "",
                            FoodImageUrl = "./ImageForSeedData/Food/Restaurant2/food5.jpeg",
                            FoodPrice = 45000,
                            FoodPriceLess = 27000f,
                            FoodTitle = "Trà sữa Hongkong Royal",
                            RestaurantId = 2
                        },
                        new
                        {
                            FoodId = 6,
                            FoodDescription = "",
                            FoodImageUrl = "./ImageForSeedData/Food/Restaurant2/food6.jpeg",
                            FoodPrice = 45000,
                            FoodPriceLess = 27000f,
                            FoodTitle = "Trà sữa lúa mạch",
                            RestaurantId = 2
                        },
                        new
                        {
                            FoodId = 7,
                            FoodDescription = "",
                            FoodImageUrl = "./ImageForSeedData/Food/Restaurant2/food7.jpeg",
                            FoodPrice = 45000,
                            FoodPriceLess = 27000f,
                            FoodTitle = "Hồng trà sữa",
                            RestaurantId = 2
                        },
                        new
                        {
                            FoodId = 8,
                            FoodDescription = "",
                            FoodImageUrl = "./ImageForSeedData/Food/Restaurant2/food7.jpeg",
                            FoodPrice = 45000,
                            FoodPriceLess = 27000f,
                            FoodTitle = "Trà sữa hoa nhài",
                            RestaurantId = 2
                        },
                        new
                        {
                            FoodId = 9,
                            FoodDescription = "",
                            FoodImageUrl = "./ImageForSeedData/Food/Restaurant2/food7.jpeg",
                            FoodPrice = 45000,
                            FoodPriceLess = 27000f,
                            FoodTitle = "Trà sữa olong kim phượng",
                            RestaurantId = 2
                        },
                        new
                        {
                            FoodId = 10,
                            FoodDescription = "",
                            FoodImageUrl = "./ImageForSeedData/Food/Restaurant2/food7.jpeg",
                            FoodPrice = 45000,
                            FoodPriceLess = 27000f,
                            FoodTitle = "Trà sữa olong bạch đào",
                            RestaurantId = 2
                        },
                        new
                        {
                            FoodId = 11,
                            FoodDescription = "không chọn được mức đá",
                            FoodImageUrl = "./ImageForSeedData/Food/Restaurant2/food11.png",
                            FoodPrice = 50000,
                            FoodPriceLess = 30000f,
                            FoodTitle = "Sữa tươi trân châu hoàng kim",
                            RestaurantId = 2
                        },
                        new
                        {
                            FoodId = 12,
                            FoodDescription = "",
                            FoodImageUrl = "./ImageForSeedData/Food/Restaurant2/food11.png",
                            FoodPrice = 50000,
                            FoodPriceLess = 30000f,
                            FoodTitle = "Đường Đen Sầu Riêng",
                            RestaurantId = 2
                        },
                        new
                        {
                            FoodId = 13,
                            FoodDescription = "không thể để đá riêng",
                            FoodImageUrl = "./ImageForSeedData/Food/Restaurant2/food13.jpeg",
                            FoodPrice = 50000,
                            FoodPriceLess = 30000f,
                            FoodTitle = "Sữa tươi trân châu đường đen",
                            RestaurantId = 2
                        },
                        new
                        {
                            FoodId = 14,
                            FoodDescription = "",
                            FoodImageUrl = "./ImageForSeedData/Food/Restaurant2/food14.jpeg",
                            FoodPrice = 50000,
                            FoodPriceLess = 30000f,
                            FoodTitle = "Trà sữa trân châu đường đen",
                            RestaurantId = 2
                        },
                        new
                        {
                            FoodId = 15,
                            FoodDescription = "Size M",
                            FoodImageUrl = "./ImageForSeedData/Food/Restaurant2/food15.jpeg",
                            FoodPrice = 57000,
                            FoodPriceLess = 34200f,
                            FoodTitle = "Matcha đường đen",
                            RestaurantId = 2
                        },
                        new
                        {
                            FoodId = 16,
                            FoodDescription = "Thơm ngon",
                            FoodImageUrl = "./ImageForSeedData/Food/Restaurant2/food16.jpeg",
                            FoodPrice = 65000,
                            FoodPriceLess = 39000f,
                            FoodTitle = "Trà táo xanh kiwi",
                            RestaurantId = 2
                        },
                        new
                        {
                            FoodId = 17,
                            FoodDescription = "SizeM",
                            FoodImageUrl = "./ImageForSeedData/Food/Restaurant2/food17.jpeg",
                            FoodPrice = 69000,
                            FoodPriceLess = 41400f,
                            FoodTitle = "Matcha đường đen kem cheese",
                            RestaurantId = 2
                        },
                        new
                        {
                            FoodId = 18,
                            FoodDescription = "",
                            FoodImageUrl = "./ImageForSeedData/Food/Restaurant2/food11.png",
                            FoodPrice = 55000,
                            FoodPriceLess = 33000f,
                            FoodTitle = "Trà sữa khoai môn đường đen",
                            RestaurantId = 2
                        },
                        new
                        {
                            FoodId = 19,
                            FoodDescription = "",
                            FoodImageUrl = "./ImageForSeedData/Food/Restaurant2/food19.jpeg",
                            FoodPrice = 54000,
                            FoodPriceLess = 32400f,
                            FoodTitle = "Trà lúa mạch kem cheese",
                            RestaurantId = 2
                        },
                        new
                        {
                            FoodId = 20,
                            FoodDescription = "",
                            FoodImageUrl = "./ImageForSeedData/Food/Restaurant2/food20.jpeg",
                            FoodPrice = 54000,
                            FoodPriceLess = 32400f,
                            FoodTitle = "Hồng trà Royal kem cheese",
                            RestaurantId = 2
                        },
                        new
                        {
                            FoodId = 21,
                            FoodDescription = "",
                            FoodImageUrl = "./ImageForSeedData/Food/Restaurant2/food21.jpeg",
                            FoodPrice = 57000,
                            FoodPriceLess = 34200f,
                            FoodTitle = "Trà sương mù London kem cheese",
                            RestaurantId = 2
                        },
                        new
                        {
                            FoodId = 22,
                            FoodDescription = "",
                            FoodImageUrl = "./ImageForSeedData/Food/Restaurant2/food22.jpeg",
                            FoodPrice = 54000,
                            FoodPriceLess = 34200f,
                            FoodTitle = "Trà xanh Golden kem cheese",
                            RestaurantId = 2
                        },
                        new
                        {
                            FoodId = 23,
                            FoodDescription = "",
                            FoodImageUrl = "./ImageForSeedData/Food/Restaurant2/food23.jpeg",
                            FoodPrice = 54000,
                            FoodPriceLess = 32400f,
                            FoodTitle = "Trà ô long bạch đào kem cheese",
                            RestaurantId = 2
                        },
                        new
                        {
                            FoodId = 24,
                            FoodDescription = "",
                            FoodImageUrl = "./ImageForSeedData/Food/Restaurant2/food24.jpeg",
                            FoodPrice = 54000,
                            FoodPriceLess = 32400f,
                            FoodTitle = "Trà bách hoa kem cheese",
                            RestaurantId = 2
                        },
                        new
                        {
                            FoodId = 25,
                            FoodDescription = "",
                            FoodImageUrl = "./ImageForSeedData/Food/Restaurant2/food25.jpeg",
                            FoodPrice = 54000,
                            FoodPriceLess = 32400f,
                            FoodTitle = "Trà ô long mộc hoa kem cheese",
                            RestaurantId = 2
                        },
                        new
                        {
                            FoodId = 26,
                            FoodDescription = "",
                            FoodImageUrl = "./ImageForSeedData/Food/Restaurant2/food25.jpeg",
                            FoodPrice = 54000,
                            FoodPriceLess = 32400f,
                            FoodTitle = "Trà oolong Kim Phượng kem cheese",
                            RestaurantId = 2
                        },
                        new
                        {
                            FoodId = 27,
                            FoodDescription = "",
                            FoodImageUrl = "./ImageForSeedData/Food/Restaurant2/food27.jpeg",
                            FoodPrice = 59000,
                            FoodPriceLess = 35400f,
                            FoodTitle = "Trà sữa oreo cake cream",
                            RestaurantId = 2
                        },
                        new
                        {
                            FoodId = 28,
                            FoodDescription = "",
                            FoodImageUrl = "./ImageForSeedData/Food/Restaurant2/food28.jpeg",
                            FoodPrice = 55000,
                            FoodPriceLess = 33000f,
                            FoodTitle = "Trà sữa trân châu ngọc trai trắng",
                            RestaurantId = 2
                        },
                        new
                        {
                            FoodId = 29,
                            FoodDescription = "",
                            FoodImageUrl = "./ImageForSeedData/Food/Restaurant2/food29.jpeg",
                            FoodPrice = 55000,
                            FoodPriceLess = 33000f,
                            FoodTitle = "Trà sữa trân châu ngọc trai đen",
                            RestaurantId = 2
                        },
                        new
                        {
                            FoodId = 30,
                            FoodDescription = "",
                            FoodImageUrl = "./ImageForSeedData/Food/Restaurant2/food30.jpeg",
                            FoodPrice = 68000,
                            FoodPriceLess = 40800f,
                            FoodTitle = "Trà hoa quả Royaltea đặc biệt",
                            RestaurantId = 2
                        },
                        new
                        {
                            FoodId = 31,
                            FoodDescription = "",
                            FoodImageUrl = "./ImageForSeedData/Food/Restaurant2/food31.jpeg",
                            FoodPrice = 65000,
                            FoodPriceLess = 39000f,
                            FoodTitle = "Trà xanh cam bưởi dâu tây",
                            RestaurantId = 2
                        },
                        new
                        {
                            FoodId = 32,
                            FoodDescription = "",
                            FoodImageUrl = "./ImageForSeedData/Food/Restaurant2/food32.jpeg",
                            FoodPrice = 65000,
                            FoodPriceLess = 39000f,
                            FoodTitle = "Trà xanh cam bưởi nhiệt đới",
                            RestaurantId = 2
                        },
                        new
                        {
                            FoodId = 33,
                            FoodDescription = "",
                            FoodImageUrl = "./ImageForSeedData/Food/Restaurant2/food33.jpeg",
                            FoodPrice = 58000,
                            FoodPriceLess = 34800f,
                            FoodTitle = "Scola kem cheese",
                            RestaurantId = 2
                        },
                        new
                        {
                            FoodId = 34,
                            FoodDescription = "",
                            FoodImageUrl = "./ImageForSeedData/Food/Restaurant2/food34.jpeg",
                            FoodPrice = 55000,
                            FoodPriceLess = 33000f,
                            FoodTitle = "Scola cake cream",
                            RestaurantId = 2
                        },
                        new
                        {
                            FoodId = 35,
                            FoodDescription = "",
                            FoodImageUrl = "./ImageForSeedData/Food/Restaurant2/food35.jpeg",
                            FoodPrice = 67000,
                            FoodPriceLess = 40200f,
                            FoodTitle = "Smoothie xoài kem cheese",
                            RestaurantId = 2
                        },
                        new
                        {
                            FoodId = 36,
                            FoodDescription = "",
                            FoodImageUrl = "./ImageForSeedData/Food/Restaurant2/food36.jpeg",
                            FoodPrice = 67000,
                            FoodPriceLess = 40200f,
                            FoodTitle = "Smoothie dưa hấu kem cheese",
                            RestaurantId = 2
                        },
                        new
                        {
                            FoodId = 37,
                            FoodDescription = "",
                            FoodImageUrl = "./ImageForSeedData/Food/Restaurant2/food37.jpeg",
                            FoodPrice = 67000,
                            FoodPriceLess = 40200f,
                            FoodTitle = "Smoothie ruby",
                            RestaurantId = 2
                        },
                        new
                        {
                            FoodId = 38,
                            FoodDescription = "",
                            FoodImageUrl = "./ImageForSeedData/Food/Restaurant3/food38.jpeg",
                            FoodPrice = 26000,
                            FoodPriceLess = 0f,
                            FoodTitle = "Bánh mì thịt nướng",
                            RestaurantId = 3
                        },
                        new
                        {
                            FoodId = 39,
                            FoodDescription = "",
                            FoodImageUrl = "./ImageForSeedData/Food/Restaurant3/food39.jpeg",
                            FoodPrice = 32000,
                            FoodPriceLess = 0f,
                            FoodTitle = "Bánh mì thịt nướng đặc biệt",
                            RestaurantId = 3
                        },
                        new
                        {
                            FoodId = 40,
                            FoodDescription = "",
                            FoodImageUrl = "./ImageForSeedData/Food/Restaurant3/food40.jpeg",
                            FoodPrice = 47000,
                            FoodPriceLess = 0f,
                            FoodTitle = "Bún thịt nướng đặc biệt",
                            RestaurantId = 3
                        },
                        new
                        {
                            FoodId = 41,
                            FoodDescription = "",
                            FoodImageUrl = "./ImageForSeedData/Food/Restaurant3/food41.jpeg",
                            FoodPrice = 33000,
                            FoodPriceLess = 0f,
                            FoodTitle = "Bún thịt nướng",
                            RestaurantId = 3
                        },
                        new
                        {
                            FoodId = 42,
                            FoodDescription = "",
                            FoodImageUrl = "./ImageForSeedData/Food/Restaurant3/food42.jpeg",
                            FoodPrice = 33000,
                            FoodPriceLess = 0f,
                            FoodTitle = "Bún nem nướng",
                            RestaurantId = 3
                        },
                        new
                        {
                            FoodId = 43,
                            FoodDescription = "",
                            FoodImageUrl = "./ImageForSeedData/Food/Restaurant3/food43.jpeg",
                            FoodPrice = 30000,
                            FoodPriceLess = 0f,
                            FoodTitle = "Bún Chả giò",
                            RestaurantId = 3
                        },
                        new
                        {
                            FoodId = 44,
                            FoodDescription = "Cái",
                            FoodImageUrl = "./ImageForSeedData/Food/Restaurant3/food44.jpeg",
                            FoodPrice = 6000,
                            FoodPriceLess = 0f,
                            FoodTitle = "Chả giò",
                            RestaurantId = 3
                        },
                        new
                        {
                            FoodId = 45,
                            FoodDescription = "Xiên",
                            FoodImageUrl = "./ImageForSeedData/Food/Restaurant3/food45.jpeg",
                            FoodPrice = 18000,
                            FoodPriceLess = 0f,
                            FoodTitle = "Thịt xiên",
                            RestaurantId = 3
                        },
                        new
                        {
                            FoodId = 46,
                            FoodDescription = "Viên",
                            FoodImageUrl = "./ImageForSeedData/Food/Restaurant3/food46.jpeg",
                            FoodPrice = 6000,
                            FoodPriceLess = 0f,
                            FoodTitle = "Thịt viên",
                            RestaurantId = 3
                        },
                        new
                        {
                            FoodId = 47,
                            FoodDescription = "",
                            FoodImageUrl = "./ImageForSeedData/Food/Restaurant3/food47.jpeg",
                            FoodPrice = 12000,
                            FoodPriceLess = 0f,
                            FoodTitle = "Nem nướng",
                            RestaurantId = 3
                        },
                        new
                        {
                            FoodId = 48,
                            FoodDescription = "",
                            FoodImageUrl = "./ImageForSeedData/Food/Restaurant3/food48.jpeg",
                            FoodPrice = 3000,
                            FoodPriceLess = 0f,
                            FoodTitle = "Bún thêm",
                            RestaurantId = 3
                        },
                        new
                        {
                            FoodId = 49,
                            FoodDescription = "",
                            FoodImageUrl = "./ImageForSeedData/Food/Restaurant3/food49.jpeg",
                            FoodPrice = 3000,
                            FoodPriceLess = 0f,
                            FoodTitle = "Rau thêm",
                            RestaurantId = 3
                        },
                        new
                        {
                            FoodId = 50,
                            FoodDescription = "Thành phần: bí đao, hạt chia, thục địa, la hán quả, bông cóc ... Đường phèn",
                            FoodImageUrl = "./ImageForSeedData/Food/Restaurant3/food50.jpeg",
                            FoodPrice = 15000,
                            FoodPriceLess = 0f,
                            FoodTitle = "Sâm Bí Đao Hạt Chia",
                            RestaurantId = 3
                        },
                        new
                        {
                            FoodId = 51,
                            FoodDescription = "Thành phần: BÍ ĐAOM THỤC ĐỊA, LA HÁN QUẢ, BÔNG CÚC ... ĐƯỜNG PHÈN",
                            FoodImageUrl = "./ImageForSeedData/Food/Restaurant3/food51.jpeg",
                            FoodPrice = 12000,
                            FoodPriceLess = 0f,
                            FoodTitle = "Sâm Bí Đao Đường Phền",
                            RestaurantId = 3
                        },
                        new
                        {
                            FoodId = 52,
                            FoodDescription = "Gọi 0906743795 Hổ trợ nhanh nhất nhé cảm ơn ạ ^^",
                            FoodImageUrl = "./ImageForSeedData/Food/Restaurant4/food52.jpeg",
                            FoodPrice = 55000,
                            FoodPriceLess = 49500f,
                            FoodTitle = "Mì Quảng thịt, trứng cút",
                            RestaurantId = 4
                        },
                        new
                        {
                            FoodId = 53,
                            FoodDescription = "",
                            FoodImageUrl = "./ImageForSeedData/Food/Restaurant4/food53.jpeg",
                            FoodPrice = 50000,
                            FoodPriceLess = 45000f,
                            FoodTitle = "Mì Quảng Chả Nhỏ",
                            RestaurantId = 4
                        },
                        new
                        {
                            FoodId = 54,
                            FoodDescription = "Gọi 0906743795 Hỗ trợ nha",
                            FoodImageUrl = "./ImageForSeedData/Food/Restaurant4/food54.jpeg",
                            FoodPrice = 55000,
                            FoodPriceLess = 49500f,
                            FoodTitle = "Mì Quảng Chả cua",
                            RestaurantId = 4
                        },
                        new
                        {
                            FoodId = 55,
                            FoodDescription = "",
                            FoodImageUrl = "./ImageForSeedData/Food/Restaurant4/food55.jpeg",
                            FoodPrice = 60000,
                            FoodPriceLess = 54000f,
                            FoodTitle = "Mì Quảng bắp bò + chả",
                            RestaurantId = 4
                        },
                        new
                        {
                            FoodId = 56,
                            FoodDescription = "",
                            FoodImageUrl = "./ImageForSeedData/Food/Restaurant4/food56.jpeg",
                            FoodPrice = 60000,
                            FoodPriceLess = 54000f,
                            FoodTitle = "Mì Quảng sườn non + chả",
                            RestaurantId = 4
                        },
                        new
                        {
                            FoodId = 57,
                            FoodDescription = "",
                            FoodImageUrl = "./ImageForSeedData/Food/Restaurant4/food57.jpeg",
                            FoodPrice = 50000,
                            FoodPriceLess = 45000f,
                            FoodTitle = "Chén tôm thêm",
                            RestaurantId = 4
                        },
                        new
                        {
                            FoodId = 58,
                            FoodDescription = "0906743795 Hổ trợ nhanh nhất nhé cảm ơn ạ ^^",
                            FoodImageUrl = "./ImageForSeedData/Food/Restaurant4/food58.jpeg",
                            FoodPrice = 70000,
                            FoodPriceLess = 63000f,
                            FoodTitle = "Mì Quảng Đặt biệt",
                            RestaurantId = 4
                        },
                        new
                        {
                            FoodId = 59,
                            FoodDescription = "0906743795 Hổ trợ nhanh nhất nhé cảm ơn ạ ^^",
                            FoodImageUrl = "./ImageForSeedData/Food/Restaurant4/food59.jpeg",
                            FoodPrice = 60000,
                            FoodPriceLess = 54000f,
                            FoodTitle = "Mì Quảng gà chọi rút xương",
                            RestaurantId = 4
                        },
                        new
                        {
                            FoodId = 60,
                            FoodDescription = "0906743795 Hổ trợ nhanh nhất nhé cảm ơn ạ ^^",
                            FoodImageUrl = "./ImageForSeedData/Food/Restaurant4/food60.jpeg",
                            FoodPrice = 55000,
                            FoodPriceLess = 49500f,
                            FoodTitle = "Mì Quảng tôm thịt",
                            RestaurantId = 4
                        },
                        new
                        {
                            FoodId = 61,
                            FoodDescription = "TẶNG KÈM TƯƠNG ỚT HỘI AN SIÊU NGON",
                            FoodImageUrl = "./ImageForSeedData/Food/Restaurant4/food61.jpg",
                            FoodPrice = 65000,
                            FoodPriceLess = 58500f,
                            FoodTitle = "Combo 1 tô mì quảng chọn món + 1 pepsi/nước suối",
                            RestaurantId = 4
                        },
                        new
                        {
                            FoodId = 62,
                            FoodDescription = "0906743795 Hổ trợ nhanh nhất nhé cảm ơn ạ ^^",
                            FoodImageUrl = "./ImageForSeedData/Food/Restaurant4/food62.jpeg",
                            FoodPrice = 215000,
                            FoodPriceLess = 193500f,
                            FoodTitle = "Combo 3 tô mì quảng đặc biệt 3 anh em",
                            RestaurantId = 4
                        },
                        new
                        {
                            FoodId = 63,
                            FoodDescription = "Hổ trợ nhanh nhất nhé cảm ơn ạ ^^",
                            FoodImageUrl = "./ImageForSeedData/Food/Restaurant4/food63.jpeg",
                            FoodPrice = 180000,
                            FoodPriceLess = 162000f,
                            FoodTitle = "Combo 3 tô mì Quảng gà chọi rút xương",
                            RestaurantId = 4
                        },
                        new
                        {
                            FoodId = 64,
                            FoodDescription = "0906743795 Hổ trợ nhanh nhất nhé cảm ơn ạ ^^",
                            FoodImageUrl = "./ImageForSeedData/Food/Restaurant4/food64.jpeg",
                            FoodPrice = 165000,
                            FoodPriceLess = 148500f,
                            FoodTitle = "Combo 3 tô mì Quảng Thit trứng cút",
                            RestaurantId = 4
                        },
                        new
                        {
                            FoodId = 65,
                            FoodDescription = "",
                            FoodImageUrl = "./ImageForSeedData/Food/Restaurant4/food65.jpg",
                            FoodPrice = 10000,
                            FoodPriceLess = 9000f,
                            FoodTitle = "Bánh tráng thêm",
                            RestaurantId = 4
                        },
                        new
                        {
                            FoodId = 66,
                            FoodDescription = "",
                            FoodImageUrl = "./ImageForSeedData/Food/Restaurant4/food66.jpg",
                            FoodPrice = 10000,
                            FoodPriceLess = 9000f,
                            FoodTitle = "Rau thêm",
                            RestaurantId = 4
                        },
                        new
                        {
                            FoodId = 67,
                            FoodDescription = "",
                            FoodImageUrl = "./ImageForSeedData/Food/Restaurant4/food67.jpg",
                            FoodPrice = 20000,
                            FoodPriceLess = 18000f,
                            FoodTitle = "Pepsi",
                            RestaurantId = 4
                        },
                        new
                        {
                            FoodId = 68,
                            FoodDescription = "",
                            FoodImageUrl = "./ImageForSeedData/Food/Restaurant4/food68.jpg",
                            FoodPrice = 20000,
                            FoodPriceLess = 18000f,
                            FoodTitle = "7up",
                            RestaurantId = 4
                        },
                        new
                        {
                            FoodId = 69,
                            FoodDescription = "",
                            FoodImageUrl = "./ImageForSeedData/Food/Restaurant4/food69.jpeg",
                            FoodPrice = 55000,
                            FoodPriceLess = 49500f,
                            FoodTitle = "Bánh tráng gạo 300gram",
                            RestaurantId = 4
                        },
                        new
                        {
                            FoodId = 70,
                            FoodDescription = "1 hủ",
                            FoodImageUrl = "./ImageForSeedData/Food/Restaurant4/food70.jpeg",
                            FoodPrice = 90000,
                            FoodPriceLess = 81000f,
                            FoodTitle = "Tương ớt hội an",
                            RestaurantId = 4
                        });
                });

            modelBuilder.Entity("ShopeeApi.Models.RelationCategoryFood", b =>
                {
                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<int>("FoodId")
                        .HasColumnType("int");

                    b.HasKey("CategoryId", "FoodId");

                    b.HasIndex("FoodId");

                    b.ToTable("RelationCategoryFoods");
                });

            modelBuilder.Entity("ShopeeApi.Models.Restaurant", b =>
                {
                    b.Property<int>("RsId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RsId"), 1L, 1);

                    b.Property<string>("RsAddress")
                        .IsRequired()
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("RsImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(600)");

                    b.Property<string>("RsOpenTime")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("RsPrinceRange")
                        .IsRequired()
                        .HasColumnType("nvarchar(800)");

                    b.Property<int>("RsPromotion")
                        .HasColumnType("int");

                    b.Property<string>("RsProvince")
                        .IsRequired()
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("RsRefeLike")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<int>("RsReviews")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<float>("RsStar")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("real")
                        .HasDefaultValue(1f);

                    b.Property<string>("RsTitle")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("RsType")
                        .IsRequired()
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("RsId");

                    b.HasIndex("RsTitle")
                        .IsUnique();

                    b.ToTable("Restaurants");

                    b.HasData(
                        new
                        {
                            RsId = 1,
                            RsAddress = "606/52 Đường 3 Tháng 2, P. 14, Quận 10, TP. HCM",
                            RsImageUrl = "./ImageForSeedData/Restaurant/restaurant1.jpg",
                            RsOpenTime = "6:00 - 22:00",
                            RsPrinceRange = "44,000 - 85,000",
                            RsPromotion = 0,
                            RsProvince = "TP.HCM",
                            RsRefeLike = false,
                            RsReviews = 1,
                            RsStar = 5f,
                            RsTitle = "Bếp Bà Muối - Ăn Vặt Online",
                            RsType = "QUANAN"
                        },
                        new
                        {
                            RsId = 2,
                            RsAddress = "35 Sơn Kỳ, P. Sơn Kỳ, Tân Phú, TP. HCM",
                            RsImageUrl = "./ImageForSeedData/Restaurant/restaurant2.jpg",
                            RsOpenTime = "8:15 - 22:20",
                            RsPrinceRange = "45,000 - 60,000",
                            RsPromotion = 50,
                            RsProvince = "TP.HCM",
                            RsRefeLike = false,
                            RsReviews = 500,
                            RsStar = 4.5f,
                            RsTitle = "Royaltea Vietnam By Hongkong - Sơn Kỳ",
                            RsType = "CAFE/DESSERT"
                        },
                        new
                        {
                            RsId = 3,
                            RsAddress = "115B Tôn Đản, P. 14, Quận 4, TP. HCM",
                            RsImageUrl = "./ImageForSeedData/Restaurant/restaurant3.jpg",
                            RsOpenTime = "6:00 - 20:11",
                            RsPrinceRange = "15,000 - 30,000",
                            RsPromotion = 0,
                            RsProvince = "TP.HCM",
                            RsRefeLike = false,
                            RsReviews = 999,
                            RsStar = 4.5f,
                            RsTitle = "Anh Thư - Bánh Mì & Bún Thịt Nướng",
                            RsType = "ANVAT/VIAHE"
                        },
                        new
                        {
                            RsId = 4,
                            RsAddress = "322 Phạm Hùng, P. 4, Quận 8, TP. HCM",
                            RsImageUrl = "./ImageForSeedData/Restaurant/restaurant4.jpeg",
                            RsOpenTime = "7:00 - 21:30",
                            RsPrinceRange = "30,000 - 50,000",
                            RsPromotion = 5,
                            RsProvince = "TP.HCM",
                            RsRefeLike = true,
                            RsReviews = 100,
                            RsStar = 4.5f,
                            RsTitle = "Mì Quảng 3 Anh Em - Phạm Hùng",
                            RsType = "QUANAN"
                        },
                        new
                        {
                            RsId = 5,
                            RsAddress = "38 Đường Số 13, P. Bình Thọ, Thủ Đức, TP. HCM",
                            RsImageUrl = "./ImageForSeedData/Restaurant/restaurant5.jpg",
                            RsOpenTime = "9:00 - 21:00",
                            RsPrinceRange = "14,000 - 30,000",
                            RsPromotion = 10,
                            RsProvince = "TP.HCM",
                            RsRefeLike = false,
                            RsReviews = 999,
                            RsStar = 4.5f,
                            RsTitle = "Kim Milk Tea - Trà Sữa, Nước Ép & Ăn Vặt",
                            RsType = "CAFE/DESSERT"
                        },
                        new
                        {
                            RsId = 6,
                            RsAddress = "122 Nguyễn Khoái, P. 2, Quận 4, TP. HCM",
                            RsImageUrl = "./ImageForSeedData/Restaurant/restaurant6.jpg",
                            RsOpenTime = "7:20 - 21:45",
                            RsPrinceRange = "15,000 - 69,000",
                            RsPromotion = 10,
                            RsProvince = "TP.HCM",
                            RsRefeLike = false,
                            RsReviews = 999,
                            RsStar = 4.5f,
                            RsTitle = "Min Kee - Mì Khô & Trà Hong Kong",
                            RsType = "QUANAN"
                        },
                        new
                        {
                            RsId = 7,
                            RsAddress = "18A/29 Nguyễn Thị Minh Khai, P. Đa Kao, Quận 1, TP. HCM",
                            RsImageUrl = "./ImageForSeedData/Restaurant/restaurant7.jpg",
                            RsOpenTime = "8:30 - 20:25",
                            RsPrinceRange = "95,000 - 150,000",
                            RsPromotion = 5,
                            RsProvince = "TP.HCM",
                            RsRefeLike = true,
                            RsReviews = 999,
                            RsStar = 4.5f,
                            RsTitle = "Bánh Bò Thốt Nốt COCOCake - Lò Bánh Minh Khai",
                            RsType = "QUANAN"
                        },
                        new
                        {
                            RsId = 8,
                            RsAddress = "26 Huỳnh Lan Khanh, P. 2, Tân Bình, TP. HCM",
                            RsImageUrl = "./ImageForSeedData/Restaurant/restaurant8.jpg",
                            RsOpenTime = "7:00 - 20:45",
                            RsPrinceRange = "20,000 - 100,000",
                            RsPromotion = 5,
                            RsProvince = "TP.HCM",
                            RsRefeLike = false,
                            RsReviews = 999,
                            RsStar = 4.5f,
                            RsTitle = "Việt - Cơm Chay",
                            RsType = "ANCHAY"
                        },
                        new
                        {
                            RsId = 9,
                            RsAddress = "420/11 Huỳnh Văn Bánh, P. 14, Phú Nhuận, TP. HCM",
                            RsImageUrl = "./ImageForSeedData/Restaurant/restaurant9.jpeg",
                            RsOpenTime = "9:00 - 19:00",
                            RsPrinceRange = "105,000 - 150,000",
                            RsPromotion = 0,
                            RsProvince = "TP.HCM",
                            RsRefeLike = false,
                            RsReviews = 50,
                            RsStar = 4.5f,
                            RsTitle = "Bánh Quế Hà Lan - Huỳnh Văn Bánh",
                            RsType = "TIEMBANH"
                        });
                });

            modelBuilder.Entity("ShopeeApi.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<byte[]>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<byte[]>("PasswordSalt")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("UserName")
                        .IsUnique();

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            PasswordHash = new byte[] { 3, 150, 211, 217, 204, 215, 5, 126, 27, 226, 237, 164, 180, 146, 232, 75, 36, 82, 205, 205, 114, 40, 226, 63, 80, 96, 127, 73, 148, 19, 32, 82, 86, 99, 23, 167, 15, 220, 134, 121, 231, 246, 242, 187, 202, 29, 13, 14, 29, 39, 156, 153, 164, 4, 216, 198, 40, 196, 239, 116, 76, 176, 212, 75 },
                            PasswordSalt = new byte[] { 76, 177, 179, 204, 76, 78, 75, 200, 168, 61, 98, 98, 9, 209, 203, 186, 127, 135, 16, 13, 220, 220, 32, 14, 143, 232, 248, 139, 38, 67, 239, 39, 148, 98, 156, 169, 104, 148, 229, 211, 116, 53, 92, 154, 38, 166, 7, 97, 116, 216, 46, 178, 80, 110, 130, 95, 223, 50, 146, 100, 207, 51, 87, 101, 51, 78, 225, 74, 167, 119, 43, 97, 194, 44, 190, 227, 208, 153, 27, 241, 100, 235, 221, 11, 161, 153, 179, 47, 78, 77, 238, 189, 186, 234, 34, 83, 138, 46, 146, 236, 84, 90, 90, 187, 3, 228, 199, 203, 154, 208, 56, 68, 11, 91, 99, 101, 173, 23, 38, 152, 65, 180, 173, 147, 126, 138, 14, 244 },
                            Role = 928399,
                            UserName = "nhoxhieuro5@gmail.com"
                        },
                        new
                        {
                            Id = 2,
                            PasswordHash = new byte[] { 221, 169, 186, 67, 85, 90, 224, 85, 249, 125, 162, 60, 230, 166, 59, 132, 111, 89, 45, 28, 157, 205, 89, 22, 199, 30, 148, 129, 134, 105, 198, 15, 111, 49, 206, 187, 179, 67, 85, 194, 4, 126, 54, 223, 113, 201, 55, 186, 254, 254, 125, 41, 228, 252, 135, 125, 90, 149, 199, 221, 98, 131, 242, 137 },
                            PasswordSalt = new byte[] { 44, 184, 88, 218, 39, 121, 224, 204, 168, 29, 24, 112, 172, 100, 5, 174, 12, 251, 103, 151, 143, 150, 70, 52, 195, 239, 176, 127, 226, 237, 83, 204, 143, 32, 97, 142, 209, 244, 36, 97, 199, 189, 143, 145, 11, 66, 160, 30, 35, 195, 208, 167, 206, 216, 66, 245, 113, 239, 234, 17, 42, 69, 198, 206, 144, 122, 247, 126, 134, 206, 28, 198, 29, 45, 155, 123, 141, 112, 209, 20, 189, 165, 160, 37, 9, 21, 237, 96, 60, 101, 242, 251, 193, 144, 65, 198, 33, 101, 244, 136, 76, 89, 140, 142, 43, 27, 44, 252, 50, 229, 134, 154, 10, 16, 208, 250, 29, 209, 97, 70, 47, 181, 168, 61, 98, 64, 194, 71 },
                            Role = 468255,
                            UserName = "chaymetwa"
                        },
                        new
                        {
                            Id = 3,
                            PasswordHash = new byte[] { 191, 39, 35, 110, 204, 172, 184, 206, 233, 37, 28, 253, 47, 201, 188, 197, 187, 31, 240, 38, 145, 10, 253, 38, 214, 169, 62, 149, 220, 6, 81, 83, 210, 219, 104, 201, 6, 156, 91, 69, 251, 102, 149, 171, 144, 235, 204, 81, 67, 75, 126, 44, 97, 207, 100, 210, 241, 102, 158, 253, 223, 10, 62, 28 },
                            PasswordSalt = new byte[] { 127, 11, 56, 187, 25, 5, 130, 210, 152, 222, 144, 54, 26, 15, 231, 231, 172, 27, 38, 35, 49, 101, 90, 240, 70, 19, 194, 223, 185, 49, 45, 73, 20, 3, 86, 126, 195, 96, 192, 104, 247, 155, 7, 62, 28, 211, 238, 2, 37, 94, 250, 173, 232, 46, 231, 118, 135, 235, 240, 148, 149, 218, 100, 136, 58, 170, 173, 52, 153, 210, 221, 129, 214, 189, 153, 142, 2, 229, 96, 183, 193, 217, 120, 134, 190, 198, 234, 170, 59, 117, 243, 109, 102, 14, 112, 218, 221, 188, 206, 193, 46, 90, 98, 113, 213, 99, 250, 40, 147, 45, 216, 150, 245, 136, 229, 80, 252, 66, 214, 51, 176, 244, 60, 48, 173, 77, 201, 238 },
                            Role = 468255,
                            UserName = "metmoichua"
                        },
                        new
                        {
                            Id = 4,
                            PasswordHash = new byte[] { 147, 249, 154, 224, 4, 71, 166, 150, 46, 129, 85, 177, 118, 117, 58, 14, 153, 100, 113, 198, 52, 96, 248, 101, 6, 34, 2, 253, 4, 143, 175, 41, 216, 177, 116, 154, 159, 214, 214, 23, 122, 32, 100, 37, 126, 48, 138, 11, 34, 111, 231, 25, 85, 99, 213, 222, 169, 155, 30, 151, 202, 137, 51, 102 },
                            PasswordSalt = new byte[] { 214, 61, 151, 247, 67, 71, 210, 100, 45, 212, 149, 207, 252, 8, 214, 95, 191, 11, 118, 22, 188, 162, 111, 246, 152, 154, 133, 83, 90, 92, 235, 221, 202, 240, 250, 193, 0, 69, 30, 112, 36, 31, 112, 57, 70, 39, 148, 146, 230, 107, 168, 230, 100, 204, 99, 43, 102, 61, 15, 37, 110, 120, 56, 1, 163, 65, 197, 162, 110, 179, 101, 181, 160, 101, 255, 4, 23, 37, 250, 225, 183, 182, 113, 231, 50, 116, 191, 158, 252, 247, 204, 230, 253, 58, 52, 10, 5, 220, 58, 123, 252, 76, 95, 49, 160, 170, 171, 198, 151, 25, 138, 151, 114, 225, 232, 44, 40, 60, 172, 172, 35, 108, 124, 230, 175, 47, 190, 22 },
                            Role = 468255,
                            UserName = "hoiaita"
                        });
                });

            modelBuilder.Entity("ShopeeApi.Models.Category", b =>
                {
                    b.HasOne("ShopeeApi.Models.Restaurant", "Restaurant")
                        .WithMany("Categories")
                        .HasForeignKey("RestaurantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Restaurant");
                });

            modelBuilder.Entity("ShopeeApi.Models.Food", b =>
                {
                    b.HasOne("ShopeeApi.Models.Restaurant", "Restaurant")
                        .WithMany("Foods")
                        .HasForeignKey("RestaurantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Restaurant");
                });

            modelBuilder.Entity("ShopeeApi.Models.RelationCategoryFood", b =>
                {
                    b.HasOne("ShopeeApi.Models.Category", "Category")
                        .WithMany("RelationCategoryFoods")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ShopeeApi.Models.Food", "Food")
                        .WithMany("RelationCategoryFoods")
                        .HasForeignKey("FoodId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("Food");
                });

            modelBuilder.Entity("ShopeeApi.Models.Category", b =>
                {
                    b.Navigation("RelationCategoryFoods");
                });

            modelBuilder.Entity("ShopeeApi.Models.Food", b =>
                {
                    b.Navigation("RelationCategoryFoods");
                });

            modelBuilder.Entity("ShopeeApi.Models.Restaurant", b =>
                {
                    b.Navigation("Categories");

                    b.Navigation("Foods");
                });
#pragma warning restore 612, 618
        }
    }
}
