// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ShopeeApi.Datas;

#nullable disable

namespace ShopeeApi.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20221011070434_seedDataForCategory")]
    partial class seedDataForCategory
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("ShopeeApi.Models.Category", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CategoryId"), 1L, 1);

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("CategoryTag")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("RestaurantId")
                        .HasColumnType("int");

                    b.HasKey("CategoryId");

                    b.HasIndex("RestaurantId");

                    b.HasIndex("CategoryTag", "RestaurantId")
                        .IsUnique();

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            CategoryId = 1,
                            CategoryName = "MENU",
                            CategoryTag = "menu",
                            RestaurantId = 1
                        },
                        new
                        {
                            CategoryId = 2,
                            CategoryName = "FREESHIP XTRA SIÊU ƯU ĐÃI - GIẢM 50%",
                            CategoryTag = "freeship50%",
                            RestaurantId = 2
                        },
                        new
                        {
                            CategoryId = 3,
                            CategoryName = "NOWFOOD DAY",
                            CategoryTag = "nowfoodday",
                            RestaurantId = 2
                        },
                        new
                        {
                            CategoryId = 4,
                            CategoryName = "NEW",
                            CategoryTag = "new",
                            RestaurantId = 2
                        },
                        new
                        {
                            CategoryId = 5,
                            CategoryName = "ROYAL BLACK TIGER",
                            CategoryTag = "royalblacktiger",
                            RestaurantId = 2
                        },
                        new
                        {
                            CategoryId = 6,
                            CategoryName = "ROYAL CHEESE TEA",
                            CategoryTag = "royalcheesetea",
                            RestaurantId = 2
                        },
                        new
                        {
                            CategoryId = 7,
                            CategoryName = "MILK TEA",
                            CategoryTag = "milktea",
                            RestaurantId = 2
                        },
                        new
                        {
                            CategoryId = 8,
                            CategoryName = "FRESH FRUIT TEA",
                            CategoryTag = "freshfruittea",
                            RestaurantId = 2
                        },
                        new
                        {
                            CategoryId = 9,
                            CategoryName = "MATCHA & CHOCOLATE",
                            CategoryTag = "matchachocolate",
                            RestaurantId = 2
                        },
                        new
                        {
                            CategoryId = 10,
                            CategoryName = "SMOOTHIE CHEESE",
                            CategoryTag = "smoothiecheese",
                            RestaurantId = 2
                        },
                        new
                        {
                            CategoryId = 11,
                            CategoryName = "BÁNH MÌ",
                            CategoryTag = "banhmi",
                            RestaurantId = 3
                        },
                        new
                        {
                            CategoryId = 12,
                            CategoryName = "BÚN",
                            CategoryTag = "bun",
                            RestaurantId = 3
                        },
                        new
                        {
                            CategoryId = 13,
                            CategoryName = "MÓN THÊM",
                            CategoryTag = "monthem",
                            RestaurantId = 3
                        },
                        new
                        {
                            CategoryId = 14,
                            CategoryName = "THỨC UỐNG",
                            CategoryTag = "thucuong",
                            RestaurantId = 3
                        },
                        new
                        {
                            CategoryId = 15,
                            CategoryName = "KHUYẾN MÃI HOT",
                            CategoryTag = "khuyenmaihot",
                            RestaurantId = 4
                        },
                        new
                        {
                            CategoryId = 16,
                            CategoryName = "COMBO HOT NƯỚC NGỌT",
                            CategoryTag = "combohotnuocngot",
                            RestaurantId = 4
                        },
                        new
                        {
                            CategoryId = 17,
                            CategoryName = "MÌ QUẢNG",
                            CategoryTag = "miquang",
                            RestaurantId = 4
                        },
                        new
                        {
                            CategoryId = 18,
                            CategoryName = "COMBO SIÊU TIẾT KIỆM 1 NGƯỜI",
                            CategoryTag = "combosieutietkiem1nguoi",
                            RestaurantId = 4
                        },
                        new
                        {
                            CategoryId = 19,
                            CategoryName = "COMBO 3 TÔ",
                            CategoryTag = "combo3to",
                            RestaurantId = 4
                        },
                        new
                        {
                            CategoryId = 20,
                            CategoryName = "MÓN THÊM",
                            CategoryTag = "monthem",
                            RestaurantId = 4
                        },
                        new
                        {
                            CategoryId = 21,
                            CategoryName = "NƯỚC UỐNG",
                            CategoryTag = "nuocuong",
                            RestaurantId = 4
                        },
                        new
                        {
                            CategoryId = 22,
                            CategoryName = "ĐẶC SẢN MIỀN TRUNG",
                            CategoryTag = "dacsanmientrung",
                            RestaurantId = 4
                        },
                        new
                        {
                            CategoryId = 23,
                            CategoryName = "NOWFOOD DAY",
                            CategoryTag = "nowfoodday",
                            RestaurantId = 5
                        },
                        new
                        {
                            CategoryId = 24,
                            CategoryName = "COMBO TRÀ SỮA",
                            CategoryTag = "combotrasua",
                            RestaurantId = 5
                        },
                        new
                        {
                            CategoryId = 25,
                            CategoryName = "TRÀ TRÁI CÂY NHIỆT ĐỚI",
                            CategoryTag = "tratraicaynhietdoi",
                            RestaurantId = 5
                        },
                        new
                        {
                            CategoryId = 26,
                            CategoryName = "SỮA TƯƠI ĐƯỜNG ĐEN",
                            CategoryTag = "suatuoiduongden",
                            RestaurantId = 5
                        },
                        new
                        {
                            CategoryId = 27,
                            CategoryName = "TRÀ SỮA",
                            CategoryTag = "trasua",
                            RestaurantId = 5
                        },
                        new
                        {
                            CategoryId = 28,
                            CategoryName = "LỤC TRÀ",
                            CategoryTag = "luctra",
                            RestaurantId = 5
                        },
                        new
                        {
                            CategoryId = 29,
                            CategoryName = "NƯỚC ÉP TRÁI CÂY TƯƠI",
                            CategoryTag = "nuoceptraicaytuoi",
                            RestaurantId = 5
                        },
                        new
                        {
                            CategoryId = 30,
                            CategoryName = "COMBO COUPLE",
                            CategoryTag = "combocouple",
                            RestaurantId = 5
                        },
                        new
                        {
                            CategoryId = 31,
                            CategoryName = "MÌ CỰC PHẨM",
                            CategoryTag = "micucpham",
                            RestaurantId = 6
                        },
                        new
                        {
                            CategoryId = 32,
                            CategoryName = "SỦI CẢO / HOÀNH THÁNH",
                            CategoryTag = "suicaohoanhthanh",
                            RestaurantId = 6
                        },
                        new
                        {
                            CategoryId = 33,
                            CategoryName = "MÌ KHÔ",
                            CategoryTag = "mikho",
                            RestaurantId = 6
                        },
                        new
                        {
                            CategoryId = 34,
                            CategoryName = "MÌ NƯỚC",
                            CategoryTag = "minuoc",
                            RestaurantId = 6
                        },
                        new
                        {
                            CategoryId = 35,
                            CategoryName = "HỦ TIẾU KHÔ",
                            CategoryTag = "hutieukho",
                            RestaurantId = 6
                        },
                        new
                        {
                            CategoryId = 36,
                            CategoryName = "MÓN ĂN THÊM",
                            CategoryTag = "monanthem",
                            RestaurantId = 6
                        },
                        new
                        {
                            CategoryId = 37,
                            CategoryName = "TRÀ THANH NHIỆT",
                            CategoryTag = "trathanhnhiet",
                            RestaurantId = 6
                        },
                        new
                        {
                            CategoryId = 38,
                            CategoryName = "SIÊU SALE MÙA LỄ HỘI",
                            CategoryTag = "sieusalemualehoi",
                            RestaurantId = 7
                        },
                        new
                        {
                            CategoryId = 39,
                            CategoryName = "BÁNH BÒ",
                            CategoryTag = "banhbo",
                            RestaurantId = 7
                        },
                        new
                        {
                            CategoryId = 40,
                            CategoryName = "BÁNH DA LỢN",
                            CategoryTag = "banhdalon",
                            RestaurantId = 7
                        },
                        new
                        {
                            CategoryId = 41,
                            CategoryName = "RAU CÂU FLAN CHEESE",
                            CategoryTag = "raucauflancheese",
                            RestaurantId = 7
                        },
                        new
                        {
                            CategoryId = 42,
                            CategoryName = "RAU CÂU SƠN THỦY",
                            CategoryTag = "raucausonthuy",
                            RestaurantId = 7
                        },
                        new
                        {
                            CategoryId = 43,
                            CategoryName = "RAU CÂU DỪA",
                            CategoryTag = "raucaudua",
                            RestaurantId = 7
                        },
                        new
                        {
                            CategoryId = 44,
                            CategoryName = "KEM",
                            CategoryTag = "kem",
                            RestaurantId = 7
                        },
                        new
                        {
                            CategoryId = 45,
                            CategoryName = "COMBO",
                            CategoryTag = "combo",
                            RestaurantId = 7
                        },
                        new
                        {
                            CategoryId = 46,
                            CategoryName = "YOGHURT",
                            CategoryTag = "yoghurt",
                            RestaurantId = 7
                        },
                        new
                        {
                            CategoryId = 47,
                            CategoryName = "BÁNH FLAN",
                            CategoryTag = "banhflan",
                            RestaurantId = 7
                        },
                        new
                        {
                            CategoryId = 48,
                            CategoryName = "CHÈ",
                            CategoryTag = "che",
                            RestaurantId = 7
                        },
                        new
                        {
                            CategoryId = 49,
                            CategoryName = "CỐT DỪA",
                            CategoryTag = "cotdua",
                            RestaurantId = 7
                        },
                        new
                        {
                            CategoryId = 50,
                            CategoryName = "COMBO",
                            CategoryTag = "combo",
                            RestaurantId = 8
                        },
                        new
                        {
                            CategoryId = 51,
                            CategoryName = "MÓN CƠM",
                            CategoryTag = "moncom",
                            RestaurantId = 8
                        },
                        new
                        {
                            CategoryId = 52,
                            CategoryName = "MÓN SỢI",
                            CategoryTag = "monsoi",
                            RestaurantId = 8
                        },
                        new
                        {
                            CategoryId = 53,
                            CategoryName = "MÓN LẨU",
                            CategoryTag = "monlau",
                            RestaurantId = 8
                        },
                        new
                        {
                            CategoryId = 54,
                            CategoryName = "BANH1 BISCOTTI",
                            CategoryTag = "banhbiscotti",
                            RestaurantId = 9
                        });
                });

            modelBuilder.Entity("ShopeeApi.Models.Food", b =>
                {
                    b.Property<int>("FoodId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FoodId"), 1L, 1);

                    b.Property<string>("FoodDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FoodImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("FoodPrice")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<float>("FoodPriceLess")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("real")
                        .HasDefaultValue(0f);

                    b.Property<string>("FoodTitle")
                        .IsRequired()
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("RestaurantId")
                        .HasColumnType("int");

                    b.HasKey("FoodId");

                    b.HasIndex("RestaurantId");

                    b.HasIndex("FoodTitle", "RestaurantId")
                        .IsUnique();

                    b.ToTable("Foods");
                });

            modelBuilder.Entity("ShopeeApi.Models.RelationCategoryFood", b =>
                {
                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<int>("FoodId")
                        .HasColumnType("int");

                    b.HasKey("CategoryId", "FoodId");

                    b.HasIndex("FoodId");

                    b.ToTable("RelationCategoryFoods");
                });

            modelBuilder.Entity("ShopeeApi.Models.Restaurant", b =>
                {
                    b.Property<int>("RsId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RsId"), 1L, 1);

                    b.Property<string>("RsAddress")
                        .IsRequired()
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("RsImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(600)");

                    b.Property<string>("RsOpenTime")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("RsPrinceRange")
                        .IsRequired()
                        .HasColumnType("nvarchar(800)");

                    b.Property<int>("RsPromotion")
                        .HasColumnType("int");

                    b.Property<string>("RsProvince")
                        .IsRequired()
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("RsRefeLike")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<int>("RsReviews")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<float>("RsStar")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("real")
                        .HasDefaultValue(1f);

                    b.Property<string>("RsTitle")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("RsType")
                        .IsRequired()
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("RsId");

                    b.HasIndex("RsTitle")
                        .IsUnique();

                    b.ToTable("Restaurants");

                    b.HasData(
                        new
                        {
                            RsId = 1,
                            RsAddress = "606/52 Đường 3 Tháng 2, P. 14, Quận 10, TP. HCM",
                            RsImageUrl = "./ImageForSeedData/Restaurant/restaurant1.jpg",
                            RsOpenTime = "6:00 - 22:00",
                            RsPrinceRange = "44,000 - 85,000",
                            RsPromotion = 0,
                            RsProvince = "TP.HCM",
                            RsRefeLike = false,
                            RsReviews = 1,
                            RsStar = 5f,
                            RsTitle = "Bếp Bà Muối - Ăn Vặt Online",
                            RsType = "QUANAN"
                        },
                        new
                        {
                            RsId = 2,
                            RsAddress = "35 Sơn Kỳ, P. Sơn Kỳ, Tân Phú, TP. HCM",
                            RsImageUrl = "./ImageForSeedData/Restaurant/restaurant2.jpg",
                            RsOpenTime = "8:15 - 22:20",
                            RsPrinceRange = "45,000 - 60,000",
                            RsPromotion = 50,
                            RsProvince = "TP.HCM",
                            RsRefeLike = false,
                            RsReviews = 500,
                            RsStar = 4.5f,
                            RsTitle = "Royaltea Vietnam By Hongkong - Sơn Kỳ",
                            RsType = "CAFE/DESSERT"
                        },
                        new
                        {
                            RsId = 3,
                            RsAddress = "115B Tôn Đản, P. 14, Quận 4, TP. HCM",
                            RsImageUrl = "./ImageForSeedData/Restaurant/restaurant3.jpg",
                            RsOpenTime = "6:00 - 20:11",
                            RsPrinceRange = "15,000 - 30,000",
                            RsPromotion = 0,
                            RsProvince = "TP.HCM",
                            RsRefeLike = false,
                            RsReviews = 999,
                            RsStar = 4.5f,
                            RsTitle = "Anh Thư - Bánh Mì & Bún Thịt Nướng",
                            RsType = "ANVAT/VIAHE"
                        },
                        new
                        {
                            RsId = 4,
                            RsAddress = "322 Phạm Hùng, P. 4, Quận 8, TP. HCM",
                            RsImageUrl = "./ImageForSeedData/Restaurant/restaurant4.jpeg",
                            RsOpenTime = "7:00 - 21:30",
                            RsPrinceRange = "30,000 - 50,000",
                            RsPromotion = 5,
                            RsProvince = "TP.HCM",
                            RsRefeLike = true,
                            RsReviews = 100,
                            RsStar = 4.5f,
                            RsTitle = "Mì Quảng 3 Anh Em - Phạm Hùng",
                            RsType = "QUANAN"
                        },
                        new
                        {
                            RsId = 5,
                            RsAddress = "38 Đường Số 13, P. Bình Thọ, Thủ Đức, TP. HCM",
                            RsImageUrl = "./ImageForSeedData/Restaurant/restaurant5.jpg",
                            RsOpenTime = "9:00 - 21:00",
                            RsPrinceRange = "14,000 - 30,000",
                            RsPromotion = 10,
                            RsProvince = "TP.HCM",
                            RsRefeLike = false,
                            RsReviews = 999,
                            RsStar = 4.5f,
                            RsTitle = "Kim Milk Tea - Trà Sữa, Nước Ép & Ăn Vặt",
                            RsType = "CAFE/DESSERT"
                        },
                        new
                        {
                            RsId = 6,
                            RsAddress = "122 Nguyễn Khoái, P. 2, Quận 4, TP. HCM",
                            RsImageUrl = "./ImageForSeedData/Restaurant/restaurant6.jpg",
                            RsOpenTime = "7:20 - 21:45",
                            RsPrinceRange = "15,000 - 69,000",
                            RsPromotion = 10,
                            RsProvince = "TP.HCM",
                            RsRefeLike = false,
                            RsReviews = 999,
                            RsStar = 4.5f,
                            RsTitle = "Min Kee - Mì Khô & Trà Hong Kong",
                            RsType = "QUANAN"
                        },
                        new
                        {
                            RsId = 7,
                            RsAddress = "18A/29 Nguyễn Thị Minh Khai, P. Đa Kao, Quận 1, TP. HCM",
                            RsImageUrl = "./ImageForSeedData/Restaurant/restaurant7.jpg",
                            RsOpenTime = "8:30 - 20:25",
                            RsPrinceRange = "95,000 - 150,000",
                            RsPromotion = 5,
                            RsProvince = "TP.HCM",
                            RsRefeLike = true,
                            RsReviews = 999,
                            RsStar = 4.5f,
                            RsTitle = "Bánh Bò Thốt Nốt COCOCake - Lò Bánh Minh Khai",
                            RsType = "QUANAN"
                        },
                        new
                        {
                            RsId = 8,
                            RsAddress = "26 Huỳnh Lan Khanh, P. 2, Tân Bình, TP. HCM",
                            RsImageUrl = "./ImageForSeedData/Restaurant/restaurant8.jpg",
                            RsOpenTime = "7:00 - 20:45",
                            RsPrinceRange = "20,000 - 100,000",
                            RsPromotion = 5,
                            RsProvince = "TP.HCM",
                            RsRefeLike = false,
                            RsReviews = 999,
                            RsStar = 4.5f,
                            RsTitle = "Việt - Cơm Chay",
                            RsType = "ANCHAY"
                        },
                        new
                        {
                            RsId = 9,
                            RsAddress = "420/11 Huỳnh Văn Bánh, P. 14, Phú Nhuận, TP. HCM",
                            RsImageUrl = "./ImageForSeedData/Restaurant/restaurant9.jpeg",
                            RsOpenTime = "9:00 - 19:00",
                            RsPrinceRange = "105,000 - 150,000",
                            RsPromotion = 0,
                            RsProvince = "TP.HCM",
                            RsRefeLike = false,
                            RsReviews = 50,
                            RsStar = 4.5f,
                            RsTitle = "Bánh Quế Hà Lan - Huỳnh Văn Bánh",
                            RsType = "TIEMBANH"
                        });
                });

            modelBuilder.Entity("ShopeeApi.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<byte[]>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<byte[]>("PasswordSalt")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("UserName")
                        .IsUnique();

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            PasswordHash = new byte[] { 197, 113, 160, 2, 222, 64, 106, 87, 23, 132, 236, 143, 180, 22, 164, 165, 156, 211, 135, 164, 57, 15, 171, 34, 161, 72, 174, 91, 37, 84, 52, 186, 224, 174, 181, 62, 14, 9, 110, 171, 246, 193, 25, 100, 188, 37, 45, 141, 126, 62, 101, 107, 40, 145, 6, 146, 9, 130, 69, 10, 73, 31, 20, 226 },
                            PasswordSalt = new byte[] { 223, 125, 191, 19, 230, 240, 12, 163, 246, 218, 83, 142, 227, 116, 203, 91, 138, 147, 225, 8, 252, 90, 192, 65, 237, 156, 70, 180, 245, 221, 118, 10, 26, 0, 129, 243, 217, 143, 116, 174, 223, 42, 177, 90, 250, 132, 0, 240, 72, 202, 194, 72, 19, 171, 152, 161, 126, 254, 13, 85, 148, 54, 18, 154, 54, 104, 204, 211, 117, 243, 81, 214, 85, 159, 145, 110, 110, 95, 83, 52, 189, 228, 201, 176, 246, 194, 222, 15, 92, 48, 26, 255, 183, 250, 142, 103, 51, 89, 77, 174, 250, 224, 182, 69, 192, 150, 243, 35, 117, 140, 240, 113, 70, 84, 223, 39, 27, 146, 51, 83, 63, 91, 247, 9, 76, 249, 90, 112 },
                            Role = 928399,
                            UserName = "nhoxhieuro5@gmail.com"
                        },
                        new
                        {
                            Id = 2,
                            PasswordHash = new byte[] { 164, 16, 119, 67, 81, 207, 11, 171, 221, 9, 241, 160, 57, 152, 51, 192, 60, 112, 148, 18, 199, 175, 69, 116, 66, 25, 252, 99, 13, 238, 114, 5, 74, 43, 106, 63, 138, 101, 111, 43, 8, 105, 78, 83, 170, 217, 166, 118, 235, 11, 48, 170, 3, 21, 28, 169, 28, 15, 120, 137, 224, 162, 19, 241 },
                            PasswordSalt = new byte[] { 85, 98, 213, 123, 191, 245, 214, 84, 190, 155, 206, 2, 172, 75, 147, 43, 82, 201, 228, 227, 108, 18, 106, 96, 215, 47, 203, 226, 117, 128, 210, 125, 121, 13, 237, 109, 17, 119, 133, 73, 51, 127, 46, 212, 250, 237, 25, 175, 30, 53, 206, 143, 231, 18, 235, 179, 177, 144, 50, 134, 154, 244, 161, 39, 49, 14, 190, 227, 6, 201, 216, 253, 175, 76, 104, 195, 131, 23, 154, 106, 255, 180, 239, 128, 193, 223, 244, 32, 172, 150, 98, 76, 164, 132, 120, 221, 75, 211, 241, 112, 53, 16, 84, 78, 153, 191, 48, 3, 16, 89, 176, 186, 99, 244, 61, 33, 1, 199, 67, 51, 191, 85, 140, 62, 2, 237, 244, 176 },
                            Role = 468255,
                            UserName = "chaymetwa"
                        },
                        new
                        {
                            Id = 3,
                            PasswordHash = new byte[] { 101, 168, 148, 1, 217, 169, 159, 2, 226, 143, 41, 248, 164, 58, 12, 81, 17, 227, 180, 85, 40, 217, 201, 202, 201, 205, 245, 228, 156, 193, 45, 164, 45, 248, 247, 241, 43, 220, 98, 236, 120, 94, 21, 25, 36, 14, 233, 171, 125, 173, 69, 31, 151, 151, 147, 239, 202, 206, 132, 131, 187, 208, 70, 208 },
                            PasswordSalt = new byte[] { 43, 218, 55, 234, 81, 18, 136, 15, 33, 4, 1, 75, 142, 64, 95, 79, 119, 167, 161, 156, 93, 195, 88, 73, 56, 180, 140, 42, 239, 196, 230, 248, 238, 147, 40, 73, 1, 111, 88, 229, 138, 129, 59, 99, 217, 121, 14, 237, 217, 99, 131, 24, 44, 138, 39, 192, 232, 129, 177, 37, 213, 99, 243, 24, 33, 141, 166, 13, 57, 246, 54, 106, 40, 41, 42, 135, 155, 59, 166, 182, 85, 164, 233, 125, 9, 112, 155, 156, 61, 123, 94, 242, 124, 192, 192, 84, 231, 174, 120, 233, 49, 76, 30, 43, 24, 129, 213, 71, 74, 5, 16, 233, 188, 93, 205, 159, 47, 142, 8, 111, 113, 12, 145, 7, 226, 143, 174, 152 },
                            Role = 468255,
                            UserName = "metmoichua"
                        },
                        new
                        {
                            Id = 4,
                            PasswordHash = new byte[] { 204, 134, 166, 46, 40, 6, 215, 248, 20, 69, 185, 180, 60, 8, 26, 186, 197, 149, 103, 136, 137, 157, 159, 74, 158, 99, 174, 226, 172, 131, 140, 135, 246, 46, 51, 170, 124, 81, 228, 92, 151, 45, 82, 5, 153, 234, 188, 211, 19, 49, 176, 21, 127, 125, 221, 237, 174, 225, 93, 60, 202, 135, 233, 53 },
                            PasswordSalt = new byte[] { 11, 3, 5, 65, 102, 67, 243, 54, 76, 197, 94, 15, 51, 196, 50, 211, 254, 85, 68, 61, 210, 52, 234, 235, 182, 172, 148, 4, 219, 212, 3, 91, 16, 108, 224, 60, 20, 215, 166, 208, 158, 63, 49, 228, 156, 103, 98, 79, 142, 99, 224, 112, 47, 175, 57, 248, 203, 77, 177, 238, 22, 49, 151, 154, 134, 237, 71, 19, 95, 252, 88, 231, 205, 77, 229, 28, 119, 14, 203, 119, 116, 133, 31, 188, 111, 131, 17, 180, 104, 146, 74, 24, 138, 239, 62, 28, 135, 79, 6, 29, 72, 208, 227, 234, 250, 6, 127, 225, 18, 164, 150, 255, 144, 124, 15, 152, 154, 158, 199, 100, 10, 84, 167, 31, 133, 144, 187, 231 },
                            Role = 468255,
                            UserName = "hoiaita"
                        });
                });

            modelBuilder.Entity("ShopeeApi.Models.Category", b =>
                {
                    b.HasOne("ShopeeApi.Models.Restaurant", "Restaurant")
                        .WithMany("Categories")
                        .HasForeignKey("RestaurantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Restaurant");
                });

            modelBuilder.Entity("ShopeeApi.Models.Food", b =>
                {
                    b.HasOne("ShopeeApi.Models.Restaurant", "Restaurant")
                        .WithMany("Foods")
                        .HasForeignKey("RestaurantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Restaurant");
                });

            modelBuilder.Entity("ShopeeApi.Models.RelationCategoryFood", b =>
                {
                    b.HasOne("ShopeeApi.Models.Category", "Category")
                        .WithMany("RelationCategoryFoods")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ShopeeApi.Models.Food", "Food")
                        .WithMany("RelationCategoryFoods")
                        .HasForeignKey("FoodId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("Food");
                });

            modelBuilder.Entity("ShopeeApi.Models.Category", b =>
                {
                    b.Navigation("RelationCategoryFoods");
                });

            modelBuilder.Entity("ShopeeApi.Models.Food", b =>
                {
                    b.Navigation("RelationCategoryFoods");
                });

            modelBuilder.Entity("ShopeeApi.Models.Restaurant", b =>
                {
                    b.Navigation("Categories");

                    b.Navigation("Foods");
                });
#pragma warning restore 612, 618
        }
    }
}
