// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ShopeeApi.Datas;

#nullable disable

namespace ShopeeApi.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20221012032001_seedfoodres7")]
    partial class seedfoodres7
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("ShopeeApi.Models.Category", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CategoryId"), 1L, 1);

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("CategoryTag")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("RestaurantId")
                        .HasColumnType("int");

                    b.HasKey("CategoryId");

                    b.HasIndex("RestaurantId");

                    b.HasIndex("CategoryTag", "RestaurantId")
                        .IsUnique();

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            CategoryId = 1,
                            CategoryName = "MENU",
                            CategoryTag = "menu",
                            RestaurantId = 1
                        },
                        new
                        {
                            CategoryId = 2,
                            CategoryName = "FREESHIP XTRA SIÊU ƯU ĐÃI - GIẢM 50%",
                            CategoryTag = "freeship50%",
                            RestaurantId = 2
                        },
                        new
                        {
                            CategoryId = 3,
                            CategoryName = "NOWFOOD DAY",
                            CategoryTag = "nowfoodday",
                            RestaurantId = 2
                        },
                        new
                        {
                            CategoryId = 4,
                            CategoryName = "NEW",
                            CategoryTag = "new",
                            RestaurantId = 2
                        },
                        new
                        {
                            CategoryId = 5,
                            CategoryName = "ROYAL BLACK TIGER",
                            CategoryTag = "royalblacktiger",
                            RestaurantId = 2
                        },
                        new
                        {
                            CategoryId = 6,
                            CategoryName = "ROYAL CHEESE TEA",
                            CategoryTag = "royalcheesetea",
                            RestaurantId = 2
                        },
                        new
                        {
                            CategoryId = 7,
                            CategoryName = "MILK TEA",
                            CategoryTag = "milktea",
                            RestaurantId = 2
                        },
                        new
                        {
                            CategoryId = 8,
                            CategoryName = "FRESH FRUIT TEA",
                            CategoryTag = "freshfruittea",
                            RestaurantId = 2
                        },
                        new
                        {
                            CategoryId = 9,
                            CategoryName = "MATCHA & CHOCOLATE",
                            CategoryTag = "matchachocolate",
                            RestaurantId = 2
                        },
                        new
                        {
                            CategoryId = 10,
                            CategoryName = "SMOOTHIE CHEESE",
                            CategoryTag = "smoothiecheese",
                            RestaurantId = 2
                        },
                        new
                        {
                            CategoryId = 11,
                            CategoryName = "BÁNH MÌ",
                            CategoryTag = "banhmi",
                            RestaurantId = 3
                        },
                        new
                        {
                            CategoryId = 12,
                            CategoryName = "BÚN",
                            CategoryTag = "bun",
                            RestaurantId = 3
                        },
                        new
                        {
                            CategoryId = 13,
                            CategoryName = "MÓN THÊM",
                            CategoryTag = "monthem",
                            RestaurantId = 3
                        },
                        new
                        {
                            CategoryId = 14,
                            CategoryName = "THỨC UỐNG",
                            CategoryTag = "thucuong",
                            RestaurantId = 3
                        },
                        new
                        {
                            CategoryId = 15,
                            CategoryName = "KHUYẾN MÃI HOT",
                            CategoryTag = "khuyenmaihot",
                            RestaurantId = 4
                        },
                        new
                        {
                            CategoryId = 16,
                            CategoryName = "COMBO HOT NƯỚC NGỌT",
                            CategoryTag = "combohotnuocngot",
                            RestaurantId = 4
                        },
                        new
                        {
                            CategoryId = 17,
                            CategoryName = "MÌ QUẢNG",
                            CategoryTag = "miquang",
                            RestaurantId = 4
                        },
                        new
                        {
                            CategoryId = 18,
                            CategoryName = "COMBO SIÊU TIẾT KIỆM 1 NGƯỜI",
                            CategoryTag = "combosieutietkiem1nguoi",
                            RestaurantId = 4
                        },
                        new
                        {
                            CategoryId = 19,
                            CategoryName = "COMBO 3 TÔ",
                            CategoryTag = "combo3to",
                            RestaurantId = 4
                        },
                        new
                        {
                            CategoryId = 20,
                            CategoryName = "MÓN THÊM",
                            CategoryTag = "monthem",
                            RestaurantId = 4
                        },
                        new
                        {
                            CategoryId = 21,
                            CategoryName = "NƯỚC UỐNG",
                            CategoryTag = "nuocuong",
                            RestaurantId = 4
                        },
                        new
                        {
                            CategoryId = 22,
                            CategoryName = "ĐẶC SẢN MIỀN TRUNG",
                            CategoryTag = "dacsanmientrung",
                            RestaurantId = 4
                        },
                        new
                        {
                            CategoryId = 23,
                            CategoryName = "NOWFOOD DAY",
                            CategoryTag = "nowfoodday",
                            RestaurantId = 5
                        },
                        new
                        {
                            CategoryId = 24,
                            CategoryName = "COMBO TRÀ SỮA",
                            CategoryTag = "combotrasua",
                            RestaurantId = 5
                        },
                        new
                        {
                            CategoryId = 25,
                            CategoryName = "TRÀ TRÁI CÂY NHIỆT ĐỚI",
                            CategoryTag = "tratraicaynhietdoi",
                            RestaurantId = 5
                        },
                        new
                        {
                            CategoryId = 26,
                            CategoryName = "SỮA TƯƠI ĐƯỜNG ĐEN",
                            CategoryTag = "suatuoiduongden",
                            RestaurantId = 5
                        },
                        new
                        {
                            CategoryId = 27,
                            CategoryName = "TRÀ SỮA",
                            CategoryTag = "trasua",
                            RestaurantId = 5
                        },
                        new
                        {
                            CategoryId = 28,
                            CategoryName = "LỤC TRÀ",
                            CategoryTag = "luctra",
                            RestaurantId = 5
                        },
                        new
                        {
                            CategoryId = 29,
                            CategoryName = "NƯỚC ÉP TRÁI CÂY TƯƠI",
                            CategoryTag = "nuoceptraicaytuoi",
                            RestaurantId = 5
                        },
                        new
                        {
                            CategoryId = 30,
                            CategoryName = "COMBO COUPLE",
                            CategoryTag = "combocouple",
                            RestaurantId = 5
                        },
                        new
                        {
                            CategoryId = 31,
                            CategoryName = "MÌ CỰC PHẨM",
                            CategoryTag = "micucpham",
                            RestaurantId = 6
                        },
                        new
                        {
                            CategoryId = 32,
                            CategoryName = "SỦI CẢO / HOÀNH THÁNH",
                            CategoryTag = "suicaohoanhthanh",
                            RestaurantId = 6
                        },
                        new
                        {
                            CategoryId = 33,
                            CategoryName = "MÌ KHÔ",
                            CategoryTag = "mikho",
                            RestaurantId = 6
                        },
                        new
                        {
                            CategoryId = 34,
                            CategoryName = "MÌ NƯỚC",
                            CategoryTag = "minuoc",
                            RestaurantId = 6
                        },
                        new
                        {
                            CategoryId = 35,
                            CategoryName = "HỦ TIẾU KHÔ",
                            CategoryTag = "hutieukho",
                            RestaurantId = 6
                        },
                        new
                        {
                            CategoryId = 36,
                            CategoryName = "MÓN ĂN THÊM",
                            CategoryTag = "monanthem",
                            RestaurantId = 6
                        },
                        new
                        {
                            CategoryId = 37,
                            CategoryName = "TRÀ THANH NHIỆT",
                            CategoryTag = "trathanhnhiet",
                            RestaurantId = 6
                        },
                        new
                        {
                            CategoryId = 38,
                            CategoryName = "SIÊU SALE MÙA LỄ HỘI",
                            CategoryTag = "sieusalemualehoi",
                            RestaurantId = 7
                        },
                        new
                        {
                            CategoryId = 39,
                            CategoryName = "BÁNH BÒ",
                            CategoryTag = "banhbo",
                            RestaurantId = 7
                        },
                        new
                        {
                            CategoryId = 40,
                            CategoryName = "BÁNH DA LỢN",
                            CategoryTag = "banhdalon",
                            RestaurantId = 7
                        },
                        new
                        {
                            CategoryId = 41,
                            CategoryName = "RAU CÂU FLAN CHEESE",
                            CategoryTag = "raucauflancheese",
                            RestaurantId = 7
                        },
                        new
                        {
                            CategoryId = 42,
                            CategoryName = "RAU CÂU SƠN THỦY",
                            CategoryTag = "raucausonthuy",
                            RestaurantId = 7
                        },
                        new
                        {
                            CategoryId = 43,
                            CategoryName = "RAU CÂU DỪA",
                            CategoryTag = "raucaudua",
                            RestaurantId = 7
                        },
                        new
                        {
                            CategoryId = 44,
                            CategoryName = "KEM",
                            CategoryTag = "kem",
                            RestaurantId = 7
                        },
                        new
                        {
                            CategoryId = 45,
                            CategoryName = "COMBO",
                            CategoryTag = "combo",
                            RestaurantId = 7
                        },
                        new
                        {
                            CategoryId = 46,
                            CategoryName = "YOGHURT",
                            CategoryTag = "yoghurt",
                            RestaurantId = 7
                        },
                        new
                        {
                            CategoryId = 47,
                            CategoryName = "BÁNH FLAN",
                            CategoryTag = "banhflan",
                            RestaurantId = 7
                        },
                        new
                        {
                            CategoryId = 48,
                            CategoryName = "CHÈ",
                            CategoryTag = "che",
                            RestaurantId = 7
                        },
                        new
                        {
                            CategoryId = 49,
                            CategoryName = "CỐT DỪA",
                            CategoryTag = "cotdua",
                            RestaurantId = 7
                        },
                        new
                        {
                            CategoryId = 50,
                            CategoryName = "COMBO",
                            CategoryTag = "combo",
                            RestaurantId = 8
                        },
                        new
                        {
                            CategoryId = 51,
                            CategoryName = "MÓN CƠM",
                            CategoryTag = "moncom",
                            RestaurantId = 8
                        },
                        new
                        {
                            CategoryId = 52,
                            CategoryName = "MÓN SỢI",
                            CategoryTag = "monsoi",
                            RestaurantId = 8
                        },
                        new
                        {
                            CategoryId = 53,
                            CategoryName = "MÓN LẨU",
                            CategoryTag = "monlau",
                            RestaurantId = 8
                        },
                        new
                        {
                            CategoryId = 54,
                            CategoryName = "BANH1 BISCOTTI",
                            CategoryTag = "banhbiscotti",
                            RestaurantId = 9
                        });
                });

            modelBuilder.Entity("ShopeeApi.Models.Food", b =>
                {
                    b.Property<int>("FoodId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FoodId"), 1L, 1);

                    b.Property<string>("FoodDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FoodImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("FoodPrice")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<float>("FoodPriceLess")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("real")
                        .HasDefaultValue(0f);

                    b.Property<string>("FoodTitle")
                        .IsRequired()
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("RestaurantId")
                        .HasColumnType("int");

                    b.HasKey("FoodId");

                    b.HasIndex("RestaurantId");

                    b.HasIndex("FoodTitle", "RestaurantId")
                        .IsUnique();

                    b.ToTable("Foods");

                    b.HasData(
                        new
                        {
                            FoodId = 1,
                            FoodDescription = "Hộp đã được nâng cấp lên từ 300->400 gram vẫn nguyên giá cux",
                            FoodImageUrl = "./ImageForSeedData/Food/Restaurant1/food1.jpeg",
                            FoodPrice = 85000,
                            FoodPriceLess = 0f,
                            FoodTitle = "Pate bơ béo (400gram)",
                            RestaurantId = 1
                        },
                        new
                        {
                            FoodId = 2,
                            FoodDescription = "Hộp đã được nâng cấp từ 300->400 gram với giá giữ nguyên",
                            FoodImageUrl = "./ImageForSeedData/Food/Restaurant1/food2.jpeg",
                            FoodPrice = 85000,
                            FoodPriceLess = 0f,
                            FoodTitle = "Pate sate (400gram)",
                            RestaurantId = 1
                        },
                        new
                        {
                            FoodId = 3,
                            FoodDescription = "1 hủ/ 150gr",
                            FoodImageUrl = "./ImageForSeedData/Food/Restaurant1/food3.jpeg",
                            FoodPrice = 44000,
                            FoodPriceLess = 0f,
                            FoodTitle = "Muối nguyễn thần thánh",
                            RestaurantId = 1
                        },
                        new
                        {
                            FoodId = 4,
                            FoodDescription = "",
                            FoodImageUrl = "./ImageForSeedData/Food/Restaurant2/food4.jpeg",
                            FoodPrice = 50000,
                            FoodPriceLess = 30000f,
                            FoodTitle = "Trà sữa trân châu hoàng kim",
                            RestaurantId = 2
                        },
                        new
                        {
                            FoodId = 5,
                            FoodDescription = "",
                            FoodImageUrl = "./ImageForSeedData/Food/Restaurant2/food5.jpeg",
                            FoodPrice = 45000,
                            FoodPriceLess = 27000f,
                            FoodTitle = "Trà sữa Hongkong Royal",
                            RestaurantId = 2
                        },
                        new
                        {
                            FoodId = 6,
                            FoodDescription = "",
                            FoodImageUrl = "./ImageForSeedData/Food/Restaurant2/food6.jpeg",
                            FoodPrice = 45000,
                            FoodPriceLess = 27000f,
                            FoodTitle = "Trà sữa lúa mạch",
                            RestaurantId = 2
                        },
                        new
                        {
                            FoodId = 7,
                            FoodDescription = "",
                            FoodImageUrl = "./ImageForSeedData/Food/Restaurant2/food7.jpeg",
                            FoodPrice = 45000,
                            FoodPriceLess = 27000f,
                            FoodTitle = "Hồng trà sữa",
                            RestaurantId = 2
                        },
                        new
                        {
                            FoodId = 8,
                            FoodDescription = "",
                            FoodImageUrl = "./ImageForSeedData/Food/Restaurant2/food7.jpeg",
                            FoodPrice = 45000,
                            FoodPriceLess = 27000f,
                            FoodTitle = "Trà sữa hoa nhài",
                            RestaurantId = 2
                        },
                        new
                        {
                            FoodId = 9,
                            FoodDescription = "",
                            FoodImageUrl = "./ImageForSeedData/Food/Restaurant2/food7.jpeg",
                            FoodPrice = 45000,
                            FoodPriceLess = 27000f,
                            FoodTitle = "Trà sữa olong kim phượng",
                            RestaurantId = 2
                        },
                        new
                        {
                            FoodId = 10,
                            FoodDescription = "",
                            FoodImageUrl = "./ImageForSeedData/Food/Restaurant2/food7.jpeg",
                            FoodPrice = 45000,
                            FoodPriceLess = 27000f,
                            FoodTitle = "Trà sữa olong bạch đào",
                            RestaurantId = 2
                        },
                        new
                        {
                            FoodId = 11,
                            FoodDescription = "không chọn được mức đá",
                            FoodImageUrl = "./ImageForSeedData/Food/Restaurant2/food11.png",
                            FoodPrice = 50000,
                            FoodPriceLess = 30000f,
                            FoodTitle = "Sữa tươi trân châu hoàng kim",
                            RestaurantId = 2
                        },
                        new
                        {
                            FoodId = 12,
                            FoodDescription = "",
                            FoodImageUrl = "./ImageForSeedData/Food/Restaurant2/food11.png",
                            FoodPrice = 50000,
                            FoodPriceLess = 30000f,
                            FoodTitle = "Đường Đen Sầu Riêng",
                            RestaurantId = 2
                        },
                        new
                        {
                            FoodId = 13,
                            FoodDescription = "không thể để đá riêng",
                            FoodImageUrl = "./ImageForSeedData/Food/Restaurant2/food13.jpeg",
                            FoodPrice = 50000,
                            FoodPriceLess = 30000f,
                            FoodTitle = "Sữa tươi trân châu đường đen",
                            RestaurantId = 2
                        },
                        new
                        {
                            FoodId = 14,
                            FoodDescription = "",
                            FoodImageUrl = "./ImageForSeedData/Food/Restaurant2/food14.jpeg",
                            FoodPrice = 50000,
                            FoodPriceLess = 30000f,
                            FoodTitle = "Trà sữa trân châu đường đen",
                            RestaurantId = 2
                        },
                        new
                        {
                            FoodId = 15,
                            FoodDescription = "Size M",
                            FoodImageUrl = "./ImageForSeedData/Food/Restaurant2/food15.jpeg",
                            FoodPrice = 57000,
                            FoodPriceLess = 34200f,
                            FoodTitle = "Matcha đường đen",
                            RestaurantId = 2
                        },
                        new
                        {
                            FoodId = 16,
                            FoodDescription = "Thơm ngon",
                            FoodImageUrl = "./ImageForSeedData/Food/Restaurant2/food16.jpeg",
                            FoodPrice = 65000,
                            FoodPriceLess = 39000f,
                            FoodTitle = "Trà táo xanh kiwi",
                            RestaurantId = 2
                        },
                        new
                        {
                            FoodId = 17,
                            FoodDescription = "SizeM",
                            FoodImageUrl = "./ImageForSeedData/Food/Restaurant2/food17.jpeg",
                            FoodPrice = 69000,
                            FoodPriceLess = 41400f,
                            FoodTitle = "Matcha đường đen kem cheese",
                            RestaurantId = 2
                        },
                        new
                        {
                            FoodId = 18,
                            FoodDescription = "",
                            FoodImageUrl = "./ImageForSeedData/Food/Restaurant2/food11.png",
                            FoodPrice = 55000,
                            FoodPriceLess = 33000f,
                            FoodTitle = "Trà sữa khoai môn đường đen",
                            RestaurantId = 2
                        },
                        new
                        {
                            FoodId = 19,
                            FoodDescription = "",
                            FoodImageUrl = "./ImageForSeedData/Food/Restaurant2/food19.jpeg",
                            FoodPrice = 54000,
                            FoodPriceLess = 32400f,
                            FoodTitle = "Trà lúa mạch kem cheese",
                            RestaurantId = 2
                        },
                        new
                        {
                            FoodId = 20,
                            FoodDescription = "",
                            FoodImageUrl = "./ImageForSeedData/Food/Restaurant2/food20.jpeg",
                            FoodPrice = 54000,
                            FoodPriceLess = 32400f,
                            FoodTitle = "Hồng trà Royal kem cheese",
                            RestaurantId = 2
                        },
                        new
                        {
                            FoodId = 21,
                            FoodDescription = "",
                            FoodImageUrl = "./ImageForSeedData/Food/Restaurant2/food21.jpeg",
                            FoodPrice = 57000,
                            FoodPriceLess = 34200f,
                            FoodTitle = "Trà sương mù London kem cheese",
                            RestaurantId = 2
                        },
                        new
                        {
                            FoodId = 22,
                            FoodDescription = "",
                            FoodImageUrl = "./ImageForSeedData/Food/Restaurant2/food22.jpeg",
                            FoodPrice = 54000,
                            FoodPriceLess = 34200f,
                            FoodTitle = "Trà xanh Golden kem cheese",
                            RestaurantId = 2
                        },
                        new
                        {
                            FoodId = 23,
                            FoodDescription = "",
                            FoodImageUrl = "./ImageForSeedData/Food/Restaurant2/food23.jpeg",
                            FoodPrice = 54000,
                            FoodPriceLess = 32400f,
                            FoodTitle = "Trà ô long bạch đào kem cheese",
                            RestaurantId = 2
                        },
                        new
                        {
                            FoodId = 24,
                            FoodDescription = "",
                            FoodImageUrl = "./ImageForSeedData/Food/Restaurant2/food24.jpeg",
                            FoodPrice = 54000,
                            FoodPriceLess = 32400f,
                            FoodTitle = "Trà bách hoa kem cheese",
                            RestaurantId = 2
                        },
                        new
                        {
                            FoodId = 25,
                            FoodDescription = "",
                            FoodImageUrl = "./ImageForSeedData/Food/Restaurant2/food25.jpeg",
                            FoodPrice = 54000,
                            FoodPriceLess = 32400f,
                            FoodTitle = "Trà ô long mộc hoa kem cheese",
                            RestaurantId = 2
                        },
                        new
                        {
                            FoodId = 26,
                            FoodDescription = "",
                            FoodImageUrl = "./ImageForSeedData/Food/Restaurant2/food25.jpeg",
                            FoodPrice = 54000,
                            FoodPriceLess = 32400f,
                            FoodTitle = "Trà oolong Kim Phượng kem cheese",
                            RestaurantId = 2
                        },
                        new
                        {
                            FoodId = 27,
                            FoodDescription = "",
                            FoodImageUrl = "./ImageForSeedData/Food/Restaurant2/food27.jpeg",
                            FoodPrice = 59000,
                            FoodPriceLess = 35400f,
                            FoodTitle = "Trà sữa oreo cake cream",
                            RestaurantId = 2
                        },
                        new
                        {
                            FoodId = 28,
                            FoodDescription = "",
                            FoodImageUrl = "./ImageForSeedData/Food/Restaurant2/food28.jpeg",
                            FoodPrice = 55000,
                            FoodPriceLess = 33000f,
                            FoodTitle = "Trà sữa trân châu ngọc trai trắng",
                            RestaurantId = 2
                        },
                        new
                        {
                            FoodId = 29,
                            FoodDescription = "",
                            FoodImageUrl = "./ImageForSeedData/Food/Restaurant2/food29.jpeg",
                            FoodPrice = 55000,
                            FoodPriceLess = 33000f,
                            FoodTitle = "Trà sữa trân châu ngọc trai đen",
                            RestaurantId = 2
                        },
                        new
                        {
                            FoodId = 30,
                            FoodDescription = "",
                            FoodImageUrl = "./ImageForSeedData/Food/Restaurant2/food30.jpeg",
                            FoodPrice = 68000,
                            FoodPriceLess = 40800f,
                            FoodTitle = "Trà hoa quả Royaltea đặc biệt",
                            RestaurantId = 2
                        },
                        new
                        {
                            FoodId = 31,
                            FoodDescription = "",
                            FoodImageUrl = "./ImageForSeedData/Food/Restaurant2/food31.jpeg",
                            FoodPrice = 65000,
                            FoodPriceLess = 39000f,
                            FoodTitle = "Trà xanh cam bưởi dâu tây",
                            RestaurantId = 2
                        },
                        new
                        {
                            FoodId = 32,
                            FoodDescription = "",
                            FoodImageUrl = "./ImageForSeedData/Food/Restaurant2/food32.jpeg",
                            FoodPrice = 65000,
                            FoodPriceLess = 39000f,
                            FoodTitle = "Trà xanh cam bưởi nhiệt đới",
                            RestaurantId = 2
                        },
                        new
                        {
                            FoodId = 33,
                            FoodDescription = "",
                            FoodImageUrl = "./ImageForSeedData/Food/Restaurant2/food33.jpeg",
                            FoodPrice = 58000,
                            FoodPriceLess = 34800f,
                            FoodTitle = "Scola kem cheese",
                            RestaurantId = 2
                        },
                        new
                        {
                            FoodId = 34,
                            FoodDescription = "",
                            FoodImageUrl = "./ImageForSeedData/Food/Restaurant2/food34.jpeg",
                            FoodPrice = 55000,
                            FoodPriceLess = 33000f,
                            FoodTitle = "Scola cake cream",
                            RestaurantId = 2
                        },
                        new
                        {
                            FoodId = 35,
                            FoodDescription = "",
                            FoodImageUrl = "./ImageForSeedData/Food/Restaurant2/food35.jpeg",
                            FoodPrice = 67000,
                            FoodPriceLess = 40200f,
                            FoodTitle = "Smoothie xoài kem cheese",
                            RestaurantId = 2
                        },
                        new
                        {
                            FoodId = 36,
                            FoodDescription = "",
                            FoodImageUrl = "./ImageForSeedData/Food/Restaurant2/food36.jpeg",
                            FoodPrice = 67000,
                            FoodPriceLess = 40200f,
                            FoodTitle = "Smoothie dưa hấu kem cheese",
                            RestaurantId = 2
                        },
                        new
                        {
                            FoodId = 37,
                            FoodDescription = "",
                            FoodImageUrl = "./ImageForSeedData/Food/Restaurant2/food37.jpeg",
                            FoodPrice = 67000,
                            FoodPriceLess = 40200f,
                            FoodTitle = "Smoothie ruby",
                            RestaurantId = 2
                        },
                        new
                        {
                            FoodId = 38,
                            FoodDescription = "",
                            FoodImageUrl = "./ImageForSeedData/Food/Restaurant3/food38.jpeg",
                            FoodPrice = 26000,
                            FoodPriceLess = 0f,
                            FoodTitle = "Bánh mì thịt nướng",
                            RestaurantId = 3
                        },
                        new
                        {
                            FoodId = 39,
                            FoodDescription = "",
                            FoodImageUrl = "./ImageForSeedData/Food/Restaurant3/food39.jpeg",
                            FoodPrice = 32000,
                            FoodPriceLess = 0f,
                            FoodTitle = "Bánh mì thịt nướng đặc biệt",
                            RestaurantId = 3
                        },
                        new
                        {
                            FoodId = 40,
                            FoodDescription = "",
                            FoodImageUrl = "./ImageForSeedData/Food/Restaurant3/food40.jpeg",
                            FoodPrice = 47000,
                            FoodPriceLess = 0f,
                            FoodTitle = "Bún thịt nướng đặc biệt",
                            RestaurantId = 3
                        },
                        new
                        {
                            FoodId = 41,
                            FoodDescription = "",
                            FoodImageUrl = "./ImageForSeedData/Food/Restaurant3/food41.jpeg",
                            FoodPrice = 33000,
                            FoodPriceLess = 0f,
                            FoodTitle = "Bún thịt nướng",
                            RestaurantId = 3
                        },
                        new
                        {
                            FoodId = 42,
                            FoodDescription = "",
                            FoodImageUrl = "./ImageForSeedData/Food/Restaurant3/food42.jpeg",
                            FoodPrice = 33000,
                            FoodPriceLess = 0f,
                            FoodTitle = "Bún nem nướng",
                            RestaurantId = 3
                        },
                        new
                        {
                            FoodId = 43,
                            FoodDescription = "",
                            FoodImageUrl = "./ImageForSeedData/Food/Restaurant3/food43.jpeg",
                            FoodPrice = 30000,
                            FoodPriceLess = 0f,
                            FoodTitle = "Bún Chả giò",
                            RestaurantId = 3
                        },
                        new
                        {
                            FoodId = 44,
                            FoodDescription = "Cái",
                            FoodImageUrl = "./ImageForSeedData/Food/Restaurant3/food44.jpeg",
                            FoodPrice = 6000,
                            FoodPriceLess = 0f,
                            FoodTitle = "Chả giò",
                            RestaurantId = 3
                        },
                        new
                        {
                            FoodId = 45,
                            FoodDescription = "Xiên",
                            FoodImageUrl = "./ImageForSeedData/Food/Restaurant3/food45.jpeg",
                            FoodPrice = 18000,
                            FoodPriceLess = 0f,
                            FoodTitle = "Thịt xiên",
                            RestaurantId = 3
                        },
                        new
                        {
                            FoodId = 46,
                            FoodDescription = "Viên",
                            FoodImageUrl = "./ImageForSeedData/Food/Restaurant3/food46.jpeg",
                            FoodPrice = 6000,
                            FoodPriceLess = 0f,
                            FoodTitle = "Thịt viên",
                            RestaurantId = 3
                        },
                        new
                        {
                            FoodId = 47,
                            FoodDescription = "",
                            FoodImageUrl = "./ImageForSeedData/Food/Restaurant3/food47.jpeg",
                            FoodPrice = 12000,
                            FoodPriceLess = 0f,
                            FoodTitle = "Nem nướng",
                            RestaurantId = 3
                        },
                        new
                        {
                            FoodId = 48,
                            FoodDescription = "",
                            FoodImageUrl = "./ImageForSeedData/Food/Restaurant3/food48.jpeg",
                            FoodPrice = 3000,
                            FoodPriceLess = 0f,
                            FoodTitle = "Bún thêm",
                            RestaurantId = 3
                        },
                        new
                        {
                            FoodId = 49,
                            FoodDescription = "",
                            FoodImageUrl = "./ImageForSeedData/Food/Restaurant3/food49.jpeg",
                            FoodPrice = 3000,
                            FoodPriceLess = 0f,
                            FoodTitle = "Rau thêm",
                            RestaurantId = 3
                        },
                        new
                        {
                            FoodId = 50,
                            FoodDescription = "Thành phần: bí đao, hạt chia, thục địa, la hán quả, bông cóc ... Đường phèn",
                            FoodImageUrl = "./ImageForSeedData/Food/Restaurant3/food50.jpeg",
                            FoodPrice = 15000,
                            FoodPriceLess = 0f,
                            FoodTitle = "Sâm Bí Đao Hạt Chia",
                            RestaurantId = 3
                        },
                        new
                        {
                            FoodId = 51,
                            FoodDescription = "Thành phần: BÍ ĐAOM THỤC ĐỊA, LA HÁN QUẢ, BÔNG CÚC ... ĐƯỜNG PHÈN",
                            FoodImageUrl = "./ImageForSeedData/Food/Restaurant3/food51.jpeg",
                            FoodPrice = 12000,
                            FoodPriceLess = 0f,
                            FoodTitle = "Sâm Bí Đao Đường Phền",
                            RestaurantId = 3
                        },
                        new
                        {
                            FoodId = 52,
                            FoodDescription = "Gọi 0906743795 Hổ trợ nhanh nhất nhé cảm ơn ạ ^^",
                            FoodImageUrl = "./ImageForSeedData/Food/Restaurant4/food52.jpeg",
                            FoodPrice = 55000,
                            FoodPriceLess = 49500f,
                            FoodTitle = "Mì Quảng thịt, trứng cút",
                            RestaurantId = 4
                        },
                        new
                        {
                            FoodId = 53,
                            FoodDescription = "",
                            FoodImageUrl = "./ImageForSeedData/Food/Restaurant4/food53.jpeg",
                            FoodPrice = 50000,
                            FoodPriceLess = 45000f,
                            FoodTitle = "Mì Quảng Chả Nhỏ",
                            RestaurantId = 4
                        },
                        new
                        {
                            FoodId = 54,
                            FoodDescription = "Gọi 0906743795 Hỗ trợ nha",
                            FoodImageUrl = "./ImageForSeedData/Food/Restaurant4/food54.jpeg",
                            FoodPrice = 55000,
                            FoodPriceLess = 49500f,
                            FoodTitle = "Mì Quảng Chả cua",
                            RestaurantId = 4
                        },
                        new
                        {
                            FoodId = 55,
                            FoodDescription = "",
                            FoodImageUrl = "./ImageForSeedData/Food/Restaurant4/food55.jpeg",
                            FoodPrice = 60000,
                            FoodPriceLess = 54000f,
                            FoodTitle = "Mì Quảng bắp bò + chả",
                            RestaurantId = 4
                        },
                        new
                        {
                            FoodId = 56,
                            FoodDescription = "",
                            FoodImageUrl = "./ImageForSeedData/Food/Restaurant4/food56.jpeg",
                            FoodPrice = 60000,
                            FoodPriceLess = 54000f,
                            FoodTitle = "Mì Quảng sườn non + chả",
                            RestaurantId = 4
                        },
                        new
                        {
                            FoodId = 57,
                            FoodDescription = "",
                            FoodImageUrl = "./ImageForSeedData/Food/Restaurant4/food57.jpeg",
                            FoodPrice = 50000,
                            FoodPriceLess = 45000f,
                            FoodTitle = "Chén tôm thêm",
                            RestaurantId = 4
                        },
                        new
                        {
                            FoodId = 58,
                            FoodDescription = "0906743795 Hổ trợ nhanh nhất nhé cảm ơn ạ ^^",
                            FoodImageUrl = "./ImageForSeedData/Food/Restaurant4/food58.jpeg",
                            FoodPrice = 70000,
                            FoodPriceLess = 63000f,
                            FoodTitle = "Mì Quảng Đặt biệt",
                            RestaurantId = 4
                        },
                        new
                        {
                            FoodId = 59,
                            FoodDescription = "0906743795 Hổ trợ nhanh nhất nhé cảm ơn ạ ^^",
                            FoodImageUrl = "./ImageForSeedData/Food/Restaurant4/food59.jpeg",
                            FoodPrice = 60000,
                            FoodPriceLess = 54000f,
                            FoodTitle = "Mì Quảng gà chọi rút xương",
                            RestaurantId = 4
                        },
                        new
                        {
                            FoodId = 60,
                            FoodDescription = "0906743795 Hổ trợ nhanh nhất nhé cảm ơn ạ ^^",
                            FoodImageUrl = "./ImageForSeedData/Food/Restaurant4/food60.jpeg",
                            FoodPrice = 55000,
                            FoodPriceLess = 49500f,
                            FoodTitle = "Mì Quảng tôm thịt",
                            RestaurantId = 4
                        },
                        new
                        {
                            FoodId = 61,
                            FoodDescription = "TẶNG KÈM TƯƠNG ỚT HỘI AN SIÊU NGON",
                            FoodImageUrl = "./ImageForSeedData/Food/Restaurant4/food61.jpg",
                            FoodPrice = 65000,
                            FoodPriceLess = 58500f,
                            FoodTitle = "Combo 1 tô mì quảng chọn món + 1 pepsi/nước suối",
                            RestaurantId = 4
                        },
                        new
                        {
                            FoodId = 62,
                            FoodDescription = "0906743795 Hổ trợ nhanh nhất nhé cảm ơn ạ ^^",
                            FoodImageUrl = "./ImageForSeedData/Food/Restaurant4/food62.jpeg",
                            FoodPrice = 215000,
                            FoodPriceLess = 193500f,
                            FoodTitle = "Combo 3 tô mì quảng đặc biệt 3 anh em",
                            RestaurantId = 4
                        },
                        new
                        {
                            FoodId = 63,
                            FoodDescription = "Hổ trợ nhanh nhất nhé cảm ơn ạ ^^",
                            FoodImageUrl = "./ImageForSeedData/Food/Restaurant4/food63.jpeg",
                            FoodPrice = 180000,
                            FoodPriceLess = 162000f,
                            FoodTitle = "Combo 3 tô mì Quảng gà chọi rút xương",
                            RestaurantId = 4
                        },
                        new
                        {
                            FoodId = 64,
                            FoodDescription = "0906743795 Hổ trợ nhanh nhất nhé cảm ơn ạ ^^",
                            FoodImageUrl = "./ImageForSeedData/Food/Restaurant4/food64.jpeg",
                            FoodPrice = 165000,
                            FoodPriceLess = 148500f,
                            FoodTitle = "Combo 3 tô mì Quảng Thit trứng cút",
                            RestaurantId = 4
                        },
                        new
                        {
                            FoodId = 65,
                            FoodDescription = "",
                            FoodImageUrl = "./ImageForSeedData/Food/Restaurant4/food65.jpg",
                            FoodPrice = 10000,
                            FoodPriceLess = 9000f,
                            FoodTitle = "Bánh tráng thêm",
                            RestaurantId = 4
                        },
                        new
                        {
                            FoodId = 66,
                            FoodDescription = "",
                            FoodImageUrl = "./ImageForSeedData/Food/Restaurant4/food66.jpg",
                            FoodPrice = 10000,
                            FoodPriceLess = 9000f,
                            FoodTitle = "Rau thêm",
                            RestaurantId = 4
                        },
                        new
                        {
                            FoodId = 67,
                            FoodDescription = "",
                            FoodImageUrl = "./ImageForSeedData/Food/Restaurant4/food67.jpg",
                            FoodPrice = 20000,
                            FoodPriceLess = 18000f,
                            FoodTitle = "Pepsi",
                            RestaurantId = 4
                        },
                        new
                        {
                            FoodId = 68,
                            FoodDescription = "",
                            FoodImageUrl = "./ImageForSeedData/Food/Restaurant4/food68.jpg",
                            FoodPrice = 20000,
                            FoodPriceLess = 18000f,
                            FoodTitle = "7up",
                            RestaurantId = 4
                        },
                        new
                        {
                            FoodId = 69,
                            FoodDescription = "",
                            FoodImageUrl = "./ImageForSeedData/Food/Restaurant4/food69.jpeg",
                            FoodPrice = 55000,
                            FoodPriceLess = 49500f,
                            FoodTitle = "Bánh tráng gạo 300gram",
                            RestaurantId = 4
                        },
                        new
                        {
                            FoodId = 70,
                            FoodDescription = "1 hủ",
                            FoodImageUrl = "./ImageForSeedData/Food/Restaurant4/food70.jpeg",
                            FoodPrice = 90000,
                            FoodPriceLess = 81000f,
                            FoodTitle = "Tương ớt hội an",
                            RestaurantId = 4
                        },
                        new
                        {
                            FoodId = 71,
                            FoodDescription = "Trà sữa, trân châu, bánh flan size L",
                            FoodImageUrl = "./ImageForSeedData/Food/Restaurant5/food71.jpeg",
                            FoodPrice = 32000,
                            FoodPriceLess = 25600f,
                            FoodTitle = "Combo 3",
                            RestaurantId = 5
                        },
                        new
                        {
                            FoodId = 72,
                            FoodDescription = "Trà sữa + 1 topping (trân châu/sương sáo/thạch dẻo) size L",
                            FoodImageUrl = "./ImageForSeedData/Food/Restaurant5/food72.jpeg",
                            FoodPrice = 24000,
                            FoodPriceLess = 19200f,
                            FoodTitle = "Trà sữa + 1 topping (trân châu/sương sáo/thạch dẻo) size L",
                            RestaurantId = 5
                        },
                        new
                        {
                            FoodId = 73,
                            FoodDescription = "",
                            FoodImageUrl = "./ImageForSeedData/Food/Restaurant5/food73.jpeg",
                            FoodPrice = 34000,
                            FoodPriceLess = 27200f,
                            FoodTitle = "Dưa hấu ép",
                            RestaurantId = 5
                        },
                        new
                        {
                            FoodId = 74,
                            FoodDescription = "4 ly Trà sữa full topping size XL",
                            FoodImageUrl = "./ImageForSeedData/Food/Restaurant5/food74.jpeg",
                            FoodPrice = 168000,
                            FoodPriceLess = 134400f,
                            FoodTitle = "Combo 4 ly Combo 5",
                            RestaurantId = 5
                        },
                        new
                        {
                            FoodId = 75,
                            FoodDescription = "Trà sữa full topping size XL",
                            FoodImageUrl = "./ImageForSeedData/Food/Restaurant5/food75.jpeg",
                            FoodPrice = 42000,
                            FoodPriceLess = 33600f,
                            FoodTitle = "Combo 5",
                            RestaurantId = 5
                        },
                        new
                        {
                            FoodId = 76,
                            FoodDescription = "Trà sữa, thạch dẻo, thạch phô mai, bánh flan size L",
                            FoodImageUrl = "./ImageForSeedData/Food/Restaurant5/food76.jpeg",
                            FoodPrice = 37000,
                            FoodPriceLess = 29600f,
                            FoodTitle = "Combo 4",
                            RestaurantId = 5
                        },
                        new
                        {
                            FoodId = 77,
                            FoodDescription = "Trà sữa, thạch dẻo, thạch phô mai size L",
                            FoodImageUrl = "./ImageForSeedData/Food/Restaurant5/food77.jpeg",
                            FoodPrice = 32000,
                            FoodPriceLess = 25600f,
                            FoodTitle = "Combo 2",
                            RestaurantId = 5
                        },
                        new
                        {
                            FoodId = 78,
                            FoodDescription = "",
                            FoodImageUrl = "./ImageForSeedData/Food/Restaurant5/food78.jpeg",
                            FoodPrice = 35000,
                            FoodPriceLess = 28000f,
                            FoodTitle = "Trà đào cam sả",
                            RestaurantId = 5
                        },
                        new
                        {
                            FoodId = 79,
                            FoodDescription = "",
                            FoodImageUrl = "./ImageForSeedData/Food/Restaurant5/food79.jpeg",
                            FoodPrice = 22000,
                            FoodPriceLess = 17600f,
                            FoodTitle = "Trà đào dầm",
                            RestaurantId = 5
                        },
                        new
                        {
                            FoodId = 80,
                            FoodDescription = "",
                            FoodImageUrl = "./ImageForSeedData/Food/Restaurant5/food80.jpeg",
                            FoodPrice = 21000,
                            FoodPriceLess = 16800f,
                            FoodTitle = "Lục trà bạc hà",
                            RestaurantId = 5
                        },
                        new
                        {
                            FoodId = 81,
                            FoodDescription = "",
                            FoodImageUrl = "./ImageForSeedData/Food/Restaurant5/food81.jpeg",
                            FoodPrice = 34000,
                            FoodPriceLess = 27200f,
                            FoodTitle = "Trà Cam Nhài",
                            RestaurantId = 5
                        },
                        new
                        {
                            FoodId = 82,
                            FoodDescription = "",
                            FoodImageUrl = "./ImageForSeedData/Food/Restaurant5/food82.jpeg",
                            FoodPrice = 25000,
                            FoodPriceLess = 20000f,
                            FoodTitle = "Sữa tươi trân châu đường đen",
                            RestaurantId = 5
                        },
                        new
                        {
                            FoodId = 83,
                            FoodDescription = "",
                            FoodImageUrl = "./ImageForSeedData/Food/Restaurant5/food83.jpeg",
                            FoodPrice = 30000,
                            FoodPriceLess = 24000f,
                            FoodTitle = "Sữa tươi matcha trân châu đường đen",
                            RestaurantId = 5
                        },
                        new
                        {
                            FoodId = 84,
                            FoodDescription = "",
                            FoodImageUrl = "./ImageForSeedData/Food/Restaurant5/food84.jpeg",
                            FoodPrice = 25000,
                            FoodPriceLess = 20000f,
                            FoodTitle = "Sữa tươi đường đen sương sáo",
                            RestaurantId = 5
                        },
                        new
                        {
                            FoodId = 85,
                            FoodDescription = "",
                            FoodImageUrl = "./ImageForSeedData/Food/Restaurant5/food85.jpeg",
                            FoodPrice = 21000,
                            FoodPriceLess = 16800f,
                            FoodTitle = "Trà sữa",
                            RestaurantId = 5
                        },
                        new
                        {
                            FoodId = 86,
                            FoodDescription = "",
                            FoodImageUrl = "./ImageForSeedData/Food/Restaurant5/food86.jpeg",
                            FoodPrice = 27000,
                            FoodPriceLess = 21600f,
                            FoodTitle = "Trà sữa socola",
                            RestaurantId = 5
                        },
                        new
                        {
                            FoodId = 87,
                            FoodDescription = "",
                            FoodImageUrl = "./ImageForSeedData/Food/Restaurant5/food87.jpeg",
                            FoodPrice = 22000,
                            FoodPriceLess = 17600f,
                            FoodTitle = "Trà sữa hoa đậu biếc",
                            RestaurantId = 5
                        },
                        new
                        {
                            FoodId = 88,
                            FoodDescription = "",
                            FoodImageUrl = "./ImageForSeedData/Food/Restaurant5/food88.jpeg",
                            FoodPrice = 32000,
                            FoodPriceLess = 25600f,
                            FoodTitle = "Thơm ép",
                            RestaurantId = 5
                        },
                        new
                        {
                            FoodId = 89,
                            FoodDescription = "",
                            FoodImageUrl = "./ImageForSeedData/Food/Restaurant5/food89.jpeg",
                            FoodPrice = 32000,
                            FoodPriceLess = 25600f,
                            FoodTitle = "Ổi ép",
                            RestaurantId = 5
                        },
                        new
                        {
                            FoodId = 90,
                            FoodDescription = "",
                            FoodImageUrl = "./ImageForSeedData/Food/Restaurant5/food90.jpeg",
                            FoodPrice = 48000,
                            FoodPriceLess = 38400f,
                            FoodTitle = "Trà sữa + Trà sữa socola",
                            RestaurantId = 5
                        },
                        new
                        {
                            FoodId = 91,
                            FoodDescription = "2 vắt mì + đùi gà góc tư mắm tỏi + cải Tặng kèm 1 ly Trà La Hán Quả",
                            FoodImageUrl = "./ImageForSeedData/Food/Restaurant6/food91.jpeg",
                            FoodPrice = 87000,
                            FoodPriceLess = 78300f,
                            FoodTitle = "Mì khô gà chiên giòn mắm tỏi",
                            RestaurantId = 6
                        },
                        new
                        {
                            FoodId = 92,
                            FoodDescription = "2 vắt mì + tôm + xá xíu + gà xé + 2 cá viên hấp + trứng bắc thảo + sate tôm X.O Tặng kèm 1 ly Trà La Hán Quar",
                            FoodImageUrl = "./ImageForSeedData/Food/Restaurant6/food92.jpeg",
                            FoodPrice = 97000,
                            FoodPriceLess = 87300f,
                            FoodTitle = "Mì khô thập cẩm Hong Kong",
                            RestaurantId = 6
                        },
                        new
                        {
                            FoodId = 93,
                            FoodDescription = "2 vắt mì + 4 hoành thánh chiên + 1 đùi gà góc tư mắm tỏi + cải Tặng kèm 1 ly Trà La Hán Quả",
                            FoodImageUrl = "./ImageForSeedData/Food/Restaurant6/food93.jpeg",
                            FoodPrice = 97000,
                            FoodPriceLess = 87300f,
                            FoodTitle = "Mì hoành thánh khô gà góc tư mắm giòn",
                            RestaurantId = 6
                        },
                        new
                        {
                            FoodId = 94,
                            FoodDescription = "8 viên hoành thánh luộc + Sốt giấm đen + Sate tôm X.O + cải",
                            FoodImageUrl = "./ImageForSeedData/Food/Restaurant6/food94.jpg",
                            FoodPrice = 69000,
                            FoodPriceLess = 62100f,
                            FoodTitle = "Hoành thánh giấm đen",
                            RestaurantId = 6
                        },
                        new
                        {
                            FoodId = 95,
                            FoodDescription = "6 viên sủi cảo + sốt tương sate tôm X.O + cải Tặng kèm 1 ly Trà La Hán Quả",
                            FoodImageUrl = "./ImageForSeedData/Food/Restaurant6/food95.jpeg",
                            FoodPrice = 69000,
                            FoodPriceLess = 62100f,
                            FoodTitle = "Sủi cảo khô sốt X.O",
                            RestaurantId = 6
                        },
                        new
                        {
                            FoodId = 96,
                            FoodDescription = "3 Sủi cảo + 5 Hoành thánh + Sốt tương sate X.O + cải Tặng kèm 1 ly Trà La Hán Quar",
                            FoodImageUrl = "./ImageForSeedData/Food/Restaurant6/food96.jpeg",
                            FoodPrice = 69000,
                            FoodPriceLess = 62100f,
                            FoodTitle = "Hoành sủi khô",
                            RestaurantId = 6
                        },
                        new
                        {
                            FoodId = 97,
                            FoodDescription = "6 hoành thánh chiên + 6 cá viên mắm tỏi + bắc thảo + trứng gà Tặng kèm 1 ly Trà La Hán Quả",
                            FoodImageUrl = "./ImageForSeedData/Food/Restaurant6/food97.jpeg",
                            FoodPrice = 69000,
                            FoodPriceLess = 62100f,
                            FoodTitle = "Combo thập cẩm chiên lớn",
                            RestaurantId = 6
                        },
                        new
                        {
                            FoodId = 98,
                            FoodDescription = "8 viên hoành thánh nước + xá xíu + cải",
                            FoodImageUrl = "./ImageForSeedData/Food/Restaurant6/food98.jpeg",
                            FoodPrice = 59000,
                            FoodPriceLess = 53100f,
                            FoodTitle = "Hoành thánh nước xá xíu",
                            RestaurantId = 6
                        },
                        new
                        {
                            FoodId = 99,
                            FoodDescription = "2 vắt mì + xá xíu + cải Tặng kèm 1 ly Trà La Hán Quả",
                            FoodImageUrl = "./ImageForSeedData/Food/Restaurant6/food99.jpeg",
                            FoodPrice = 59000,
                            FoodPriceLess = 53100f,
                            FoodTitle = "Mì khô xá xíu",
                            RestaurantId = 6
                        },
                        new
                        {
                            FoodId = 100,
                            FoodDescription = "2 vắt mì + 2 hoành thánh chiên + 6 viên cá chiên mắm + cải Tặng kèm 1 Ly Trà La Hán Quả",
                            FoodImageUrl = "./ImageForSeedData/Food/Restaurant6/food100.jpeg",
                            FoodPrice = 59000,
                            FoodPriceLess = 53100f,
                            FoodTitle = "Mì khô cá hoành chiên mắm",
                            RestaurantId = 6
                        },
                        new
                        {
                            FoodId = 101,
                            FoodDescription = "2 vắt mì trộn khô + 4 viên hoành thánh chiên + Cải Tặng kèm 1 ly Trà La Hán Quả",
                            FoodImageUrl = "./ImageForSeedData/Food/Restaurant6/food101.jpeg",
                            FoodPrice = 59000,
                            FoodPriceLess = 53100f,
                            FoodTitle = "Mì khô hoành thánh chiên (Ko kèm chén súp)",
                            RestaurantId = 6
                        },
                        new
                        {
                            FoodId = 102,
                            FoodDescription = "2 vắt mì + gà luộc xé + cải Tặng kèm 1 Ly Trà La Hán Quả",
                            FoodImageUrl = "./ImageForSeedData/Food/Restaurant6/food102.jpeg",
                            FoodPrice = 59000,
                            FoodPriceLess = 53100f,
                            FoodTitle = "Mì khô gà xé",
                            RestaurantId = 6
                        },
                        new
                        {
                            FoodId = 103,
                            FoodDescription = "2 vắt mì + 5 hoành thánh luộc + cải + Súp",
                            FoodImageUrl = "./ImageForSeedData/Food/Restaurant6/food103.jpeg",
                            FoodPrice = 59000,
                            FoodPriceLess = 53100f,
                            FoodTitle = "Mì hoành thánh nước",
                            RestaurantId = 6
                        },
                        new
                        {
                            FoodId = 104,
                            FoodDescription = "Hủ tíu khô + xá xíu + cải Tặng kèm 1 ly Trà La Hán Quả",
                            FoodImageUrl = "./ImageForSeedData/Food/Restaurant6/food104.jpeg",
                            FoodPrice = 59000,
                            FoodPriceLess = 53100f,
                            FoodTitle = "Hủ tiếu khô xá xíu",
                            RestaurantId = 6
                        },
                        new
                        {
                            FoodId = 105,
                            FoodDescription = "Đùi gà góc tư chiên giòn sốt mắm tỏi",
                            FoodImageUrl = "./ImageForSeedData/Food/Restaurant6/food105.jpeg",
                            FoodPrice = 59000,
                            FoodPriceLess = 53100f,
                            FoodTitle = "Đùi gà góc tư chiên mắm",
                            RestaurantId = 6
                        },
                        new
                        {
                            FoodId = 106,
                            FoodDescription = "4 viên",
                            FoodImageUrl = "./ImageForSeedData/Food/Restaurant6/food105.jpeg",
                            FoodPrice = 39000,
                            FoodPriceLess = 35100f,
                            FoodTitle = "Hoàn thánh chiên",
                            RestaurantId = 6
                        },
                        new
                        {
                            FoodId = 107,
                            FoodDescription = "",
                            FoodImageUrl = "./ImageForSeedData/Food/Restaurant6/food107.jpg",
                            FoodPrice = 39000,
                            FoodPriceLess = 35100f,
                            FoodTitle = "Hồng trà long nhãn",
                            RestaurantId = 6
                        },
                        new
                        {
                            FoodId = 108,
                            FoodDescription = "",
                            FoodImageUrl = "./ImageForSeedData/Food/Restaurant6/food105.jpeg",
                            FoodPrice = 29000,
                            FoodPriceLess = 26100f,
                            FoodTitle = "Hồng trà chanh",
                            RestaurantId = 6
                        },
                        new
                        {
                            FoodId = 109,
                            FoodDescription = "Bánh bò nướng đường thốt nốt",
                            FoodImageUrl = "./ImageForSeedData/Food/Restaurant7/food109.jpeg",
                            FoodPrice = 22000,
                            FoodPriceLess = 11000f,
                            FoodTitle = "Bánh bò nướng (hộp 1 lát lớn)",
                            RestaurantId = 6
                        },
                        new
                        {
                            FoodId = 110,
                            FoodDescription = "Rau câu sơn thủy, bao gồm nhiều vị trong cùng một miếng rau câu: cốt dừa, cà phê, rau câu, lá dứa",
                            FoodImageUrl = "./ImageForSeedData/Food/Restaurant7/food110.jpeg",
                            FoodPrice = 45000,
                            FoodPriceLess = 40500f,
                            FoodTitle = "Rau câu sơn thủy hộp nhỏ (350g)",
                            RestaurantId = 6
                        },
                        new
                        {
                            FoodId = 111,
                            FoodDescription = "Gồm: nước cốt dừa tươi, đường thốt nốt, trứng gà tươi, bột",
                            FoodImageUrl = "./ImageForSeedData/Food/Restaurant7/food111.jpeg",
                            FoodPrice = 35000,
                            FoodPriceLess = 31500f,
                            FoodTitle = "Hộp 2 lát bánh bò nhỏ",
                            RestaurantId = 6
                        },
                        new
                        {
                            FoodId = 112,
                            FoodDescription = "Bánh bò nướng đường thốt nốt",
                            FoodImageUrl = "./ImageForSeedData/Food/Restaurant7/food112.jpeg",
                            FoodPrice = 110000,
                            FoodPriceLess = 99000f,
                            FoodTitle = "Bánh bò nhỏ (550g)",
                            RestaurantId = 6
                        },
                        new
                        {
                            FoodId = 113,
                            FoodDescription = "Bánh bò nướng đường thốt nốt",
                            FoodImageUrl = "./ImageForSeedData/Food/Restaurant7/food113.jpeg",
                            FoodPrice = 170000,
                            FoodPriceLess = 153000f,
                            FoodTitle = "Bánh bò lớn (900g)",
                            RestaurantId = 6
                        },
                        new
                        {
                            FoodId = 114,
                            FoodDescription = "Bánh bò nướng đường thốt nốt",
                            FoodImageUrl = "./ImageForSeedData/Food/Restaurant7/food114.jpeg",
                            FoodPrice = 60000,
                            FoodPriceLess = 54000f,
                            FoodTitle = "Hộp 4 lát bánh bò nhỏ",
                            RestaurantId = 6
                        },
                        new
                        {
                            FoodId = 115,
                            FoodDescription = "Bánh da lợn có thành phần chính từ lá cẩm khoai môn",
                            FoodImageUrl = "./ImageForSeedData/Food/Restaurant7/food115.jpeg",
                            FoodPrice = 60000,
                            FoodPriceLess = 54000f,
                            FoodTitle = "Da lợn cuộn 2 vị hộp 6 khoanh",
                            RestaurantId = 6
                        },
                        new
                        {
                            FoodId = 116,
                            FoodDescription = "Bánh da lợn có thành phần chính từ lá cẩm khoai môn",
                            FoodImageUrl = "./ImageForSeedData/Food/Restaurant7/food116.jpeg",
                            FoodPrice = 75000,
                            FoodPriceLess = 67500f,
                            FoodTitle = "Da lợn cuộn 2 vị hộp 8 khoanh",
                            RestaurantId = 6
                        },
                        new
                        {
                            FoodId = 117,
                            FoodDescription = "Bánh da lợn có thành phần chính từ lá dứa, đậu xanh",
                            FoodImageUrl = "./ImageForSeedData/Food/Restaurant7/food117.jpeg",
                            FoodPrice = 60000,
                            FoodPriceLess = 54000f,
                            FoodTitle = "Da lợn cuộn Đậu xanh lá dứa hộp 6 khoanh",
                            RestaurantId = 6
                        },
                        new
                        {
                            FoodId = 118,
                            FoodDescription = "Rau câu dẻo, lớp rau câu cà phê và flan phô mai xen kẽ nhau tạo thành từng lớp",
                            FoodImageUrl = "./ImageForSeedData/Food/Restaurant7/food118.jpeg",
                            FoodPrice = 95000,
                            FoodPriceLess = 85500f,
                            FoodTitle = "Flan cheese Cà phê hộp nhỏ (600g)",
                            RestaurantId = 6
                        },
                        new
                        {
                            FoodId = 119,
                            FoodDescription = "Rau câu dẻo, lớp rau câu cà phê và flan phô mai xen kẽ nhau tạo thành từng lớp",
                            FoodImageUrl = "./ImageForSeedData/Food/Restaurant7/food119.jpeg",
                            FoodPrice = 140000,
                            FoodPriceLess = 126000f,
                            FoodTitle = "Flan cheese Cà phê hộp lớn (900g)",
                            RestaurantId = 6
                        },
                        new
                        {
                            FoodId = 120,
                            FoodDescription = "Rau câu sơn thủy, bao gồm nhiều vị trong cùng một miếng rau câu: cốt dừa, cà phê, rau câu, lá dứa",
                            FoodImageUrl = "./ImageForSeedData/Food/Restaurant7/food120.jpeg",
                            FoodPrice = 75000,
                            FoodPriceLess = 67500f,
                            FoodTitle = "Rau câu sơn thủy hộp lớn (600g)",
                            RestaurantId = 6
                        },
                        new
                        {
                            FoodId = 121,
                            FoodDescription = "Rau câu dẻo được làm từ nước cốt và nước dừa tươi",
                            FoodImageUrl = "./ImageForSeedData/Food/Restaurant7/food121.jpeg",
                            FoodPrice = 85000,
                            FoodPriceLess = 76500f,
                            FoodTitle = "Rau câu dừa hộp nhỏ (600g)",
                            RestaurantId = 6
                        },
                        new
                        {
                            FoodId = 122,
                            FoodDescription = "",
                            FoodImageUrl = "./ImageForSeedData/Food/Restaurant7/food122.jpeg",
                            FoodPrice = 95000,
                            FoodPriceLess = 85500f,
                            FoodTitle = "Hộp kem Nhãn nhỏ 250g",
                            RestaurantId = 6
                        },
                        new
                        {
                            FoodId = 123,
                            FoodDescription = "Hình ảnh mang tính chất minh họa",
                            FoodImageUrl = "./ImageForSeedData/Food/Restaurant7/food123.jpeg",
                            FoodPrice = 195000,
                            FoodPriceLess = 175500f,
                            FoodTitle = "Combo B: 1 Bánh bò nhỏ (550g) + Hộp kem dừa 250gr",
                            RestaurantId = 6
                        },
                        new
                        {
                            FoodId = 124,
                            FoodDescription = "",
                            FoodImageUrl = "./ImageForSeedData/Food/Restaurant7/food124.jpeg",
                            FoodPrice = 22000,
                            FoodPriceLess = 19800f,
                            FoodTitle = "Yoghurt",
                            RestaurantId = 6
                        },
                        new
                        {
                            FoodId = 125,
                            FoodDescription = "",
                            FoodImageUrl = "./ImageForSeedData/Food/Restaurant7/food125.jpeg",
                            FoodPrice = 22000,
                            FoodPriceLess = 19800f,
                            FoodTitle = "Bánh Flan Vị Truyền Thống",
                            RestaurantId = 6
                        },
                        new
                        {
                            FoodId = 126,
                            FoodDescription = "Chè bưởi kèm cốt dừa chan",
                            FoodImageUrl = "./ImageForSeedData/Food/Restaurant7/food126.jpeg",
                            FoodPrice = 35000,
                            FoodPriceLess = 31500f,
                            FoodTitle = "Chè Bưởi (Đường Thốt Nốt) 200g☘",
                            RestaurantId = 6
                        },
                        new
                        {
                            FoodId = 127,
                            FoodDescription = "50ml cốt dừa (lạnh)",
                            FoodImageUrl = "./ImageForSeedData/Food/Restaurant7/food127.jpeg",
                            FoodPrice = 6000,
                            FoodPriceLess = 5400f,
                            FoodTitle = "Cốt dừa chén nhỏ 50ml (lạnh)",
                            RestaurantId = 6
                        });
                });

            modelBuilder.Entity("ShopeeApi.Models.RelationCategoryFood", b =>
                {
                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<int>("FoodId")
                        .HasColumnType("int");

                    b.HasKey("CategoryId", "FoodId");

                    b.HasIndex("FoodId");

                    b.ToTable("RelationCategoryFoods");
                });

            modelBuilder.Entity("ShopeeApi.Models.Restaurant", b =>
                {
                    b.Property<int>("RsId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RsId"), 1L, 1);

                    b.Property<string>("RsAddress")
                        .IsRequired()
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("RsImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(600)");

                    b.Property<string>("RsOpenTime")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("RsPrinceRange")
                        .IsRequired()
                        .HasColumnType("nvarchar(800)");

                    b.Property<int>("RsPromotion")
                        .HasColumnType("int");

                    b.Property<string>("RsProvince")
                        .IsRequired()
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("RsRefeLike")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<int>("RsReviews")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<float>("RsStar")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("real")
                        .HasDefaultValue(1f);

                    b.Property<string>("RsTitle")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("RsType")
                        .IsRequired()
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("RsId");

                    b.HasIndex("RsTitle")
                        .IsUnique();

                    b.ToTable("Restaurants");

                    b.HasData(
                        new
                        {
                            RsId = 1,
                            RsAddress = "606/52 Đường 3 Tháng 2, P. 14, Quận 10, TP. HCM",
                            RsImageUrl = "./ImageForSeedData/Restaurant/restaurant1.jpg",
                            RsOpenTime = "6:00 - 22:00",
                            RsPrinceRange = "44,000 - 85,000",
                            RsPromotion = 0,
                            RsProvince = "TP.HCM",
                            RsRefeLike = false,
                            RsReviews = 1,
                            RsStar = 5f,
                            RsTitle = "Bếp Bà Muối - Ăn Vặt Online",
                            RsType = "QUANAN"
                        },
                        new
                        {
                            RsId = 2,
                            RsAddress = "35 Sơn Kỳ, P. Sơn Kỳ, Tân Phú, TP. HCM",
                            RsImageUrl = "./ImageForSeedData/Restaurant/restaurant2.jpg",
                            RsOpenTime = "8:15 - 22:20",
                            RsPrinceRange = "45,000 - 60,000",
                            RsPromotion = 50,
                            RsProvince = "TP.HCM",
                            RsRefeLike = false,
                            RsReviews = 500,
                            RsStar = 4.5f,
                            RsTitle = "Royaltea Vietnam By Hongkong - Sơn Kỳ",
                            RsType = "CAFE/DESSERT"
                        },
                        new
                        {
                            RsId = 3,
                            RsAddress = "115B Tôn Đản, P. 14, Quận 4, TP. HCM",
                            RsImageUrl = "./ImageForSeedData/Restaurant/restaurant3.jpg",
                            RsOpenTime = "6:00 - 20:11",
                            RsPrinceRange = "15,000 - 30,000",
                            RsPromotion = 0,
                            RsProvince = "TP.HCM",
                            RsRefeLike = false,
                            RsReviews = 999,
                            RsStar = 4.5f,
                            RsTitle = "Anh Thư - Bánh Mì & Bún Thịt Nướng",
                            RsType = "ANVAT/VIAHE"
                        },
                        new
                        {
                            RsId = 4,
                            RsAddress = "322 Phạm Hùng, P. 4, Quận 8, TP. HCM",
                            RsImageUrl = "./ImageForSeedData/Restaurant/restaurant4.jpeg",
                            RsOpenTime = "7:00 - 21:30",
                            RsPrinceRange = "30,000 - 50,000",
                            RsPromotion = 5,
                            RsProvince = "TP.HCM",
                            RsRefeLike = true,
                            RsReviews = 100,
                            RsStar = 4.5f,
                            RsTitle = "Mì Quảng 3 Anh Em - Phạm Hùng",
                            RsType = "QUANAN"
                        },
                        new
                        {
                            RsId = 5,
                            RsAddress = "38 Đường Số 13, P. Bình Thọ, Thủ Đức, TP. HCM",
                            RsImageUrl = "./ImageForSeedData/Restaurant/restaurant5.jpg",
                            RsOpenTime = "9:00 - 21:00",
                            RsPrinceRange = "14,000 - 30,000",
                            RsPromotion = 10,
                            RsProvince = "TP.HCM",
                            RsRefeLike = false,
                            RsReviews = 999,
                            RsStar = 4.5f,
                            RsTitle = "Kim Milk Tea - Trà Sữa, Nước Ép & Ăn Vặt",
                            RsType = "CAFE/DESSERT"
                        },
                        new
                        {
                            RsId = 6,
                            RsAddress = "122 Nguyễn Khoái, P. 2, Quận 4, TP. HCM",
                            RsImageUrl = "./ImageForSeedData/Restaurant/restaurant6.jpg",
                            RsOpenTime = "7:20 - 21:45",
                            RsPrinceRange = "15,000 - 69,000",
                            RsPromotion = 10,
                            RsProvince = "TP.HCM",
                            RsRefeLike = false,
                            RsReviews = 999,
                            RsStar = 4.5f,
                            RsTitle = "Min Kee - Mì Khô & Trà Hong Kong",
                            RsType = "QUANAN"
                        },
                        new
                        {
                            RsId = 7,
                            RsAddress = "18A/29 Nguyễn Thị Minh Khai, P. Đa Kao, Quận 1, TP. HCM",
                            RsImageUrl = "./ImageForSeedData/Restaurant/restaurant7.jpg",
                            RsOpenTime = "8:30 - 20:25",
                            RsPrinceRange = "95,000 - 150,000",
                            RsPromotion = 5,
                            RsProvince = "TP.HCM",
                            RsRefeLike = true,
                            RsReviews = 999,
                            RsStar = 4.5f,
                            RsTitle = "Bánh Bò Thốt Nốt COCOCake - Lò Bánh Minh Khai",
                            RsType = "QUANAN"
                        },
                        new
                        {
                            RsId = 8,
                            RsAddress = "26 Huỳnh Lan Khanh, P. 2, Tân Bình, TP. HCM",
                            RsImageUrl = "./ImageForSeedData/Restaurant/restaurant8.jpg",
                            RsOpenTime = "7:00 - 20:45",
                            RsPrinceRange = "20,000 - 100,000",
                            RsPromotion = 5,
                            RsProvince = "TP.HCM",
                            RsRefeLike = false,
                            RsReviews = 999,
                            RsStar = 4.5f,
                            RsTitle = "Việt - Cơm Chay",
                            RsType = "ANCHAY"
                        },
                        new
                        {
                            RsId = 9,
                            RsAddress = "420/11 Huỳnh Văn Bánh, P. 14, Phú Nhuận, TP. HCM",
                            RsImageUrl = "./ImageForSeedData/Restaurant/restaurant9.jpeg",
                            RsOpenTime = "9:00 - 19:00",
                            RsPrinceRange = "105,000 - 150,000",
                            RsPromotion = 0,
                            RsProvince = "TP.HCM",
                            RsRefeLike = false,
                            RsReviews = 50,
                            RsStar = 4.5f,
                            RsTitle = "Bánh Quế Hà Lan - Huỳnh Văn Bánh",
                            RsType = "TIEMBANH"
                        });
                });

            modelBuilder.Entity("ShopeeApi.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<byte[]>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<byte[]>("PasswordSalt")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("UserName")
                        .IsUnique();

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            PasswordHash = new byte[] { 223, 24, 186, 213, 132, 104, 130, 122, 85, 107, 84, 241, 18, 41, 236, 240, 15, 71, 8, 45, 129, 191, 6, 32, 66, 53, 141, 231, 126, 119, 210, 119, 191, 63, 13, 195, 240, 182, 151, 201, 107, 161, 149, 81, 101, 206, 156, 206, 23, 122, 93, 172, 246, 194, 176, 188, 246, 51, 255, 197, 181, 209, 214, 97 },
                            PasswordSalt = new byte[] { 145, 16, 121, 93, 242, 42, 191, 207, 225, 65, 214, 92, 29, 166, 149, 6, 164, 243, 120, 175, 40, 13, 123, 175, 159, 103, 12, 45, 47, 55, 209, 239, 246, 171, 165, 246, 33, 157, 133, 177, 191, 157, 95, 240, 185, 104, 246, 167, 167, 210, 20, 143, 134, 144, 218, 128, 60, 154, 183, 28, 5, 244, 91, 94, 94, 153, 90, 85, 122, 3, 204, 48, 213, 178, 147, 21, 117, 247, 149, 23, 221, 51, 120, 161, 230, 245, 219, 36, 29, 226, 47, 36, 85, 42, 182, 13, 216, 14, 134, 120, 14, 152, 243, 131, 89, 199, 132, 75, 179, 237, 59, 213, 119, 127, 46, 106, 11, 246, 95, 219, 41, 221, 196, 29, 18, 84, 6, 184 },
                            Role = 928399,
                            UserName = "nhoxhieuro5@gmail.com"
                        },
                        new
                        {
                            Id = 2,
                            PasswordHash = new byte[] { 66, 211, 101, 143, 207, 242, 212, 248, 49, 6, 148, 134, 75, 249, 117, 162, 96, 3, 96, 81, 235, 108, 97, 35, 93, 81, 12, 94, 202, 121, 0, 242, 246, 144, 14, 189, 11, 26, 42, 203, 227, 89, 90, 195, 55, 38, 226, 25, 112, 174, 231, 120, 190, 215, 106, 164, 242, 115, 156, 166, 62, 255, 183, 29 },
                            PasswordSalt = new byte[] { 147, 172, 58, 109, 136, 176, 55, 31, 236, 234, 62, 147, 238, 17, 111, 57, 161, 118, 154, 108, 14, 91, 43, 71, 241, 1, 192, 121, 237, 107, 128, 133, 100, 41, 93, 152, 145, 107, 125, 141, 219, 20, 170, 5, 105, 105, 207, 200, 171, 49, 168, 93, 3, 119, 39, 250, 45, 122, 174, 231, 246, 60, 182, 228, 195, 136, 218, 171, 0, 68, 3, 216, 164, 161, 9, 183, 189, 112, 197, 176, 154, 54, 148, 114, 174, 165, 178, 119, 233, 94, 34, 168, 205, 108, 167, 170, 116, 99, 45, 18, 131, 30, 80, 181, 217, 112, 31, 5, 191, 167, 67, 78, 253, 167, 243, 112, 120, 144, 203, 168, 50, 86, 42, 64, 158, 86, 117, 67 },
                            Role = 468255,
                            UserName = "chaymetwa"
                        },
                        new
                        {
                            Id = 3,
                            PasswordHash = new byte[] { 248, 218, 201, 88, 93, 59, 224, 62, 162, 64, 117, 59, 182, 88, 57, 74, 146, 198, 22, 228, 218, 223, 39, 253, 250, 188, 99, 28, 125, 215, 14, 114, 251, 169, 84, 127, 211, 67, 128, 52, 49, 96, 229, 129, 203, 3, 178, 49, 195, 141, 59, 179, 146, 152, 72, 204, 221, 232, 37, 229, 31, 147, 55, 156 },
                            PasswordSalt = new byte[] { 12, 86, 181, 75, 161, 3, 95, 121, 206, 149, 210, 181, 56, 99, 173, 107, 30, 228, 164, 14, 64, 208, 66, 249, 183, 107, 110, 39, 81, 184, 8, 213, 145, 84, 231, 226, 225, 205, 171, 156, 200, 88, 109, 99, 189, 252, 225, 62, 21, 16, 29, 206, 201, 218, 106, 56, 21, 125, 137, 101, 172, 186, 197, 196, 73, 196, 2, 218, 15, 232, 147, 219, 221, 191, 171, 237, 54, 165, 191, 227, 38, 111, 107, 131, 43, 48, 143, 213, 126, 56, 147, 60, 239, 213, 44, 11, 180, 134, 88, 209, 219, 27, 223, 196, 169, 224, 8, 185, 141, 176, 200, 246, 214, 131, 107, 6, 187, 212, 142, 233, 210, 83, 134, 191, 148, 233, 175, 240 },
                            Role = 468255,
                            UserName = "metmoichua"
                        },
                        new
                        {
                            Id = 4,
                            PasswordHash = new byte[] { 82, 96, 43, 221, 214, 100, 215, 214, 63, 170, 228, 144, 202, 220, 20, 187, 72, 228, 117, 77, 9, 21, 204, 57, 90, 237, 45, 133, 97, 162, 157, 211, 152, 40, 80, 4, 235, 240, 195, 231, 129, 62, 60, 253, 35, 172, 138, 79, 17, 225, 8, 230, 177, 126, 201, 74, 204, 9, 60, 155, 176, 46, 97, 116 },
                            PasswordSalt = new byte[] { 195, 30, 199, 26, 109, 187, 78, 158, 44, 75, 95, 205, 3, 167, 23, 186, 227, 145, 117, 197, 240, 177, 247, 0, 138, 216, 173, 21, 223, 139, 236, 208, 243, 137, 224, 66, 137, 54, 252, 141, 159, 140, 151, 151, 112, 68, 3, 63, 88, 136, 201, 1, 217, 73, 183, 50, 21, 71, 62, 120, 251, 139, 187, 76, 250, 46, 45, 234, 242, 210, 74, 144, 232, 135, 73, 6, 147, 10, 236, 239, 136, 138, 212, 93, 63, 120, 73, 168, 114, 38, 84, 234, 48, 21, 181, 185, 43, 4, 210, 194, 247, 84, 156, 74, 254, 246, 37, 110, 109, 253, 46, 148, 111, 89, 172, 226, 251, 201, 57, 111, 13, 4, 11, 167, 151, 114, 97, 75 },
                            Role = 468255,
                            UserName = "hoiaita"
                        });
                });

            modelBuilder.Entity("ShopeeApi.Models.Category", b =>
                {
                    b.HasOne("ShopeeApi.Models.Restaurant", "Restaurant")
                        .WithMany("Categories")
                        .HasForeignKey("RestaurantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Restaurant");
                });

            modelBuilder.Entity("ShopeeApi.Models.Food", b =>
                {
                    b.HasOne("ShopeeApi.Models.Restaurant", "Restaurant")
                        .WithMany("Foods")
                        .HasForeignKey("RestaurantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Restaurant");
                });

            modelBuilder.Entity("ShopeeApi.Models.RelationCategoryFood", b =>
                {
                    b.HasOne("ShopeeApi.Models.Category", "Category")
                        .WithMany("RelationCategoryFoods")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ShopeeApi.Models.Food", "Food")
                        .WithMany("RelationCategoryFoods")
                        .HasForeignKey("FoodId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("Food");
                });

            modelBuilder.Entity("ShopeeApi.Models.Category", b =>
                {
                    b.Navigation("RelationCategoryFoods");
                });

            modelBuilder.Entity("ShopeeApi.Models.Food", b =>
                {
                    b.Navigation("RelationCategoryFoods");
                });

            modelBuilder.Entity("ShopeeApi.Models.Restaurant", b =>
                {
                    b.Navigation("Categories");

                    b.Navigation("Foods");
                });
#pragma warning restore 612, 618
        }
    }
}
